### ISSUE TITLE
easeInSine breaks path animation

### ISSUE THREAD

**Issue by hinok** [juliangarnier/anime#100]
Hey,
While working on some sample animations using `anime` I discovered a weird bug. When I use `easeInSine` as easing, it breaks path animation. If I change it to anything else, everything works correctly.

Here is the codepen that shows this bug http://codepen.io/hinok/full/ObdaRp/

I'm using `anime 1.1.2`.

**Edit**

I've found another equation for `easeInSine` like below

```javascript
easeInSine: (t) => {
  return 1 + Math.sin(Math.PI / 2 * t - Math.PI / 2);
},
```

If I override `anime.easings`, animation looks correctly.

```javascript
const tryToFixEasing = {
  /* @source https://gist.github.com/gre/1650294#gistcomment-1924831 */
  easeInSine: (t) => {
    return 1 + Math.sin(Math.PI / 2 * t - Math.PI / 2);
  },
};

anime.easings.easeInSine = tryToFixEasing.easeInSine;
```

So it seems that there is a problem with easing equation.

**Comment by juliangarnier** [comment]
Weird.
I'm not sure what is the right function to use here, I adapted the ones from jqueryUi.
I updated 1.1.3 with this new easeInSine function, you can try it here : https://github.com/juliangarnier/anime/tree/v1.1.3

2.0 will use a totally different easing system, so this problem should be resoled in the next major release.

Let me know!

**Comment by hinok** [comment]
`v1.1.3` resolved the issue. Could you also publish anime on `npm` because the last available version there is `v1.1.1`?

**Comment by juliangarnier** [comment]
Done!

**Comment by hinok** [comment]
@juliangarnier btw could you unveil when do you plan to release `v2` :)?

**Comment by juliangarnier** [comment]
ASAP :)
Maybe this week
