### ISSUE TITLE
How can I programmatically reverse an animation?

### ISSUE THREAD

**Issue by ockam** [juliangarnier/anime#102]
I have an animation that use translateX and translateY to move a series of divs when I click a button. I would like to have those objects go back to their initial position when I click on the button again.

I have tried to toggle the direction parameter between 'normal' and 'reverse' in my complete function but after going forward and backward once, the sequence becomes fudged.

Here’s the code I use:

```
  var explode = anime({
    targets: '.c-shape',
    translateX: function() { return anime.random(-6, 6) + 'rem'; },
    translateY: function() { return anime.random(-50, -5) + 'rem'; },
    delay: function() { return 400 + anime.random(0, 100); },
    duration: function() { return anime.random(1000, 2000); },
    direction: 'normal',
    loop: false,
    autoplay: false,
    complete: function(a) {
      if (a.settings.direction === 'normal') {
        a.settings.direction = 'reverse';
      } else {
        a.settings.direction = 'normal';
      }
    }
  });

```
And then I call play() on the button click event.

**Comment by ockam** [comment]
I also tried to create an entirely new animation that would reverse the first animation but that didn’t work either.

**Comment by juliangarnier** [comment]
Wrap your explode and reset animations in two functions, like this:

```
function explode() {
  anime.remove('div');
  anime({
    targets: 'div',
    translateX: function() { return anime.random(-6, 6) + 'rem'; },
    translateY: function() { return anime.random(-5, 5) + 'rem'; },
    delay: function() { return anime.random(0, 100); },
    duration: function() { return anime.random(1000, 2000); }
  });
}

function reset() {
  anime.remove('div');
  anime({
    targets: 'div',
    translateX: '0rem',
    translateY: '0rem',
    delay: function() { return anime.random(0, 100); },
    duration: function() { return anime.random(1000, 2000); }
  });
}

document.querySelector('.explode').onclick = explode;
document.querySelector('.reset').onclick = reset;
```

CodePen example : http://codepen.io/juliangarnier/pen/NdGwXw?editors=0010

**Comment by ockam** [comment]
Thanks.

I just found another solution after having a good read in the codebase but your solution makes more sense.

Anyway, if it can help someone else, in the complete function, once you set the animation in reverse direction, you don’t need to set it back to normal, because in reverse, the tweens will be inverted each time you call play().

So the complete function is just:

```
    complete: function(a) {
      a.settings.direction = 'reverse';
    }
```
