### ISSUE TITLE
Publish v2.0 to npm with @beta tag

### ISSUE THREAD

**Issue by exah** [juliangarnier/anime#105]
This can help community to try second version of anime.

```shell
$ npm install animejs@beta 
```

or 

```shell
$ npm install animejs@2.0.0-beta.0
```

Thanks!

**Comment by ngokevin** [comment]
You can install from GitHub: `npm install juliangarnier/anime#v2.0` (or via commit hash).

**Comment by TIMNHE** [comment]
Hi, I'm very excited with the new version, great work!

I have an issue in the process of build the source with the create-react-app:

```
Creating an optimized production build...
Failed to compile.

static/js/main.8a680a56.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [./~/animejs/anime.js:23,1]
```

Any ideas? thanks!

**Comment by exah** [comment]
@ngokevin Ok, thank you, I just thought it would be nice to publish it to npm.)

**Comment by exah** [comment]
@TIMNHE Sorry, I don't think this is relevant to this discussion, please create new issue. 

p.s. May be you can exclude anime.js from parsing by webpack.
