### ISSUE TITLE
Regression v2: Animating transform attribute of svg element

### ISSUE THREAD

**Issue by hinok** [juliangarnier/anime#111]
Hey,
With `1.x` I was able to animate svg elements by animating their attributes like e.g. 'transform'. It has been working with `v2.beta` but it doesn't work anymore with official `v2` release.
I made a simple codepen which shows this issue:

http://codepen.io/hinok/pen/wJvVgJ

Uncomment `<script ...>` with `2.0.0` to see the issue. I'm not sure if this is desired behaviour or just regression? It would be nice to animate svg elements relative to the viewbox.

**Comment by juliangarnier** [comment]
Hey thanks for pointing this out, it should be fixed now!

**Comment by hinok** [comment]
Thanks! Unfortunately animation is wrong when `2.0.1` is used. It's hard to describe and you can easily spot it when you look at both animations at the same time (link below).

What I found:
- If I set `easing` e.g. `linear` in `2.0.1`, animation looks good again but without `elasticity` effect.
- When low `elasticity` is set, it looks like X from `translate(X, Y)` is calculated too fast, there is not stop between end and start of animations (animation is looped).

Comparison loads animation in `<iframe />` with `1.1.3` and `2.0.1`. The same code is used, just different versions of anime.

**Comparison**
http://codepen.io/hinok/pen/PpwRjg

**2.0.1**
http://codepen.io/hinok/pen/wJvVgJ

**1.1.3**
http://codepen.io/hinok/pen/LWEdLd

**Comment by juliangarnier** [comment]
This is not a bug, but a feature :)

Anime's 1.x reverse direction wasn't a real 'reversed' animation. The from and to values were reversed, but not the animation per say.

To achieve the same animation as 1.x, you should try the new keyframes system (square 01) :
http://codepen.io/juliangarnier/pen/BWyeJx/?editors=0100

In that case, the code needed is slightly longer, but it can now be easily extended to longer animation as demonstrated in the second example.

**Comment by hinok** [comment]
Got it. Thanks!
