### ISSUE TITLE
npm package anime is not transpiled

### ISSUE THREAD

**Issue by hinok** [juliangarnier/anime#112]
**Edited**

I'm blind 🙈  I see that `anime.min.js` contains transpiled code, so the only problem is that `main: '...'` in `package.json` points to es6 not transpiled version. It's not a big deal because I can always import minified version, like:

```
import anime from 'anime/anime.min';

// but this could be more obvious

import anime from 'anime';
```

Although It would be nice to have transpiled minified and unminified code on npm.

---

Hey,
Please correct me If I'm wrong but on npm anime should be transpiled because a lot of people are (including me) exclude `node_modules` packages from transpilation process. Right now If I build my project, I get this

```
ERROR in vendors.f10593b858b82529f72b.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [../~/animejs/anime.js:23,1][vendors.f10593b858b82529f72b.js:14891,9]
```

I can include anime and exclude all other packages from transpilation by playing with webpack `exclude`, `include` config rules but I would like to avoid it. What do you think?

**Comment by juliangarnier** [comment]
Goodf point, I changed the main parameter to the .min file.
