### ISSUE TITLE
Time Line data

### ISSUE THREAD

**Issue by htakaoka** [juliangarnier/anime#113]
Time line command's data mast have ['now','next'], now point dos not saved.

**Comment by juliangarnier** [comment]
Not sure to understand what you mean by "time line commands data"?

**Comment by htakaoka** [comment]
sample is 
var basicTimeline = anime.timeline();

basicTimeline
  .add({
    targets: '#basicTimeline .square.el',
    translateX: [0,250],
    translateY: [0,100],
    rotate: [0,720],
    duration: 3000,    
    easing: 'easeOutExpo'
  })
  .add({
    targets: '#basicTimeline .square.el',
    background: ['red','red']
  })
  .add({
    targets: '#basicTimeline .square.el',
    translateX: [250,0],
    translateY: [100,0],
    rotate: [720,0],
    duration: 2000,
    easing: 'easeOutExpo'
  })
  .add({
    targets: '#basicTimeline .square.el',
    translateX: [0,0],
    translateY: [0,0],
    rotate: [0,0],
    background: ['#31FFA6','#31FFA6'],
    easing: 'easeOutExpo'
  });

https://codepen.io/htakaoka/pen/VpYbem

**Comment by juliangarnier** [comment]
I see, you're talking about avoiding having to use initial values on a same target in a timeline?

Take a look a this branch https://github.com/juliangarnier/anime/tree/v2.0.2 and let me know if it solves the problem for you.

**Comment by htakaoka** [comment]
Thank you for your support.

The ad block did not cooperate.
As for each data, it is separated.
When the number of the data of the property is not same
I understood that a program did not work.
thank you.

version up 2017.3.2
https://codepen.io/htakaoka/pen/VpYbem

**Comment by htakaoka** [comment]
It worked on a PC normally wonderfully in v2.0.2.
Thank you.
The problem was settled.
Because CodePen is still v2.0.1, it does not work.

code exp.
https://codepen.io/htakaoka/pen/wJMoLp
