### ISSUE TITLE
Registry returned 404 for GET on https://registry.npmjs.org/animesjs

### ISSUE THREAD

**Issue by peterennis** [juliangarnier/anime#115]
![image](https://cloud.githubusercontent.com/assets/140737/23392482/d30417fa-fd30-11e6-85be-9ec33d0c6783.png)

**Comment by peterennis** [comment]
[npm-debug.zip](https://github.com/juliangarnier/anime/files/805766/npm-debug.zip)

**Comment by hinok** [comment]
@peterennis You made a typo

```
npm install animesjs
```

should be

```
npm install animejs
```

https://www.npmjs.com/package/animejs
