### ISSUE TITLE
It's impossible to animate the 'offset' object property

### ISSUE THREAD

**Issue by dxbykov** [juliangarnier/anime#118]
```js
    let obj = { offset : 0 };

    anime({
            targets: obj,
            offset: 200,
            update: () => {
                console.log(obj)
            }                                        
    });
```

**Comment by juliangarnier** [comment]
Yeah that one is tricky since `offset` is part of the API.
That's the biggest downside of having a unified / flat parameter object.

The only solution is to separate the global parameters from the animation properties, but I prefer keeping the unified syntax.
