### ISSUE TITLE
Anime homepage errors out in IE 11

### ISSUE THREAD

**Issue by blakewatson** [juliangarnier/anime#123]
```
SCRIPT5007: Object expected
anime.min.js (18,295)
```

**Comment by greynor** [comment]
Same error happens after an animation:

var scrollTo = $("#some-element-on-the-page");
            anime({
                targets: "html, body",
                scrollTop: scrollTo.offset().top,
                duration: 1200,
                easing: 'easeOutQuart'
            });

**Comment by mellinger** [comment]
Yeah, same issue here.

**Comment by juliangarnier** [comment]
It was the promise, will be fixed in 2.0.2

**Comment by iseries** [comment]
Error still appears in anime.js v3.0.1
![image](https://user-images.githubusercontent.com/6272363/59764847-ee2d2400-929c-11e9-90e2-78b853f3b5b3.png)

**Comment by amygroshek** [comment]
I see it as well, IE11. 

<img width="309" alt="Screen Shot 2019-09-25 at 1 58 45 PM" src="https://user-images.githubusercontent.com/746182/65631175-a48b5e00-df9c-11e9-9a4e-98d8f018501b.png">

<img width="1176" alt="Screen Shot 2019-09-25 at 1 59 29 PM" src="https://user-images.githubusercontent.com/746182/65631216-b8cf5b00-df9c-11e9-8ef9-5402ca9a1333.png">

<img width="394" alt="Screen Shot 2019-09-25 at 2 00 05 PM" src="https://user-images.githubusercontent.com/746182/65631264-ce448500-df9c-11e9-8cda-41ed356312bf.png">

<img width="520" alt="Screen Shot 2019-09-25 at 2 00 24 PM" src="https://user-images.githubusercontent.com/746182/65631282-d8ff1a00-df9c-11e9-94ac-baddf80b015f.png">

**Comment by Peter-HVD** [comment]
I am also experiencing this issue - exactly the same as previously reported in both v3.0.1 & v3.1.0

**Comment by IrinaShv** [comment]
Have the same issue in v3.1.0 + IE11
