### ISSUE TITLE
is it possible to offset the position in motionPath?

### ISSUE THREAD

**Issue by redon** [juliangarnier/anime#125]
I am experimenting with anime and I like it very well. Thank you!

Now I would like to move an element along an svg path, but offset the element by a fixed value (x, y, ang) and I can not figure out how to achieve this

something like 
   translateX: path('x') - offsetX,
does not work

Can somebody help me?

**Comment by redon** [comment]
myDiv.css('margin', '-' + offsetY + 'px 0 0 -' + offsetX + 'px');

did the trick

**Comment by nicgirault** [comment]
redon's trick is actually not working for curved paths.

I had to hack the path returned by animejs in order to have a start & end to the motion:

```javascript
const adjustedPath = (path, from = 0, to = 1) => {
  const getPointAtLength = (l) => {
    return path.el.getPointAtLength((to - from) * l + from * path.totalLength)
  }
  return {
    ...path,
    el: {...path.el, getPointAtLength},
  }
}

anime({
  targets: '.follow-path',
  translateX: adjustedPath(path('x'), .1, .3),
  translateY: adjustedPath(path('y'), .1, .3),
  rotate: adjustedPath(path('angle'), .1, .3)
})
```
