### ISSUE TITLE
SVG motion path: offset problem

### ISSUE THREAD

**Issue by redon** [juliangarnier/anime#126]
I am experimenting with anime and I am very impressed! Thank you for sharing this animation engine!

I run into a problem when tweening an svg along a path. If both, the element and the path are part of an SVG, there is an x/y offset for the element. 

http://codepen.io/redon77/pen/vxJZee

I can not figure out, how to center the element along the path.
Is there a possibility to set the wanted offset (x, y, rotation)?

**Comment by htakaoka** [comment]
Hi
for  
translateX: path,
translateY: path,
to
( to <
}  to >
 (svg id="red")
     (rect id="myCircle" width="24" height="16" fill="red"/)
 (svg)
and in css
#red {
  position: absolute;
  top:  8px;
  left: 8px;
}

for lotate:path,
to#myCircle {
  transform-origin: 50% 50% 0;
}

Good luck,

**Comment by redon** [comment]
@htakaoka thank you

As you can see, css position and rotation for the element inside the svg does not work
http://codepen.io/redon77/pen/vxJZee
only 
   transform-origin: -50% 50%;
has an effect
That seams logical for me, because anime is tweening top, left and rotation accordingly to the motionPath
So still looking for a solution to offset the element

**Comment by htakaoka** [comment]
Hi
rect id="myCircle" width="24" height="16" fill="red"/
don't set inside sgv for path.
make 2th sgv and set in.

<sgv
 <path------
</sgv 
<sgv id="red
  <rect id="myRect"----
</sgv

Good luck,

**Comment by redon** [comment]
… but I would like to have it inside the same svg

I found a solution:
The element to be moved has to be placed at the registerpoint of the svg with the desired offset (and not for example at the starting point of the path to follow)
http://codepen.io/redon77/pen/vxJZee

![test](https://cloud.githubusercontent.com/assets/3617694/24037844/60ddf7c2-0aff-11e7-8114-3d721fae83f7.png)

However, it would be nice if I could set the offset-values dynamically in anime.js

**Comment by redon** [comment]
other things that I would like

- move along path: from, to
   I can now use 
      var path = anime.path('#motionPath path', 35);
   to move from 0 to 35% of the path length
   something like 
      var path = anime.path('#motionPath path', 12, 35);
   move from 12% to 35%

- and similar for svg line drawing
   draw from 12% to 35%

**Comment by htakaoka** [comment]
at rect inside same svg 
<rect id="myRect" x="-12" y="-8"  width="24" height="16" fill="red"/ >
it's work
Good luck.
