### ISSUE TITLE
"Remove arrow function for better browser compatibility"

### ISSUE THREAD

**Issue by alkhoo** [juliangarnier/anime#127]
Hi, arrow function still exists in anime.js and anime.min.js - hence I take it we are to transpile it to support older browsers? 

In support section, it says IE10+, a bit confusing since it doesn't support IE10+ out of the box.

**Comment by juliangarnier** [comment]
anime.min.js is compiled to ES5 syntax.

**Comment by quietTrojan** [comment]
thanks,this is answer i is seeking.
