### ISSUE TITLE
Include error messaging for common errors

### ISSUE THREAD

**Issue by johnend** [juliangarnier/anime#128]
Had a situation recently where I used `target` rather than `targets` this obviously resulted in my animations not working as expected. However durations, and the `complete:` callback did still continue to run.

It would be good in these cases, as anime needs `targets` to be present, to show an error to aid debugging.

**Comment by juliangarnier** [comment]
Since anime accepts a lot of different properties, il will be hard to check for misspelled prop names.
Also `targets` is not necessary in some cases, so I can't simply check if this property is present or not.
