### ISSUE TITLE
Basic timeline resets element position between each call to .add()

### ISSUE THREAD

**Issue by figuernd** [juliangarnier/anime#131]
Undocumented behavior: I would expect subsequent calls to .add() to leave elements in their last position for a true timeline flow. Even using += notation for a property like translateX, the elements return to their original positions between each .add() call.

CodePen example: http://codepen.io/nfig/pen/mWpBPQ

**Comment by tomsercu** [comment]
This is also reported as issue #121

**Comment by juliangarnier** [comment]
I replied here #121
