### ISSUE TITLE
Start animation if section appear in viewport

### ISSUE THREAD

**Issue by Jimmylet** [juliangarnier/anime#133]
Hello,

I would like to run the anime.timeline () function when my section or the item to be animated appears on the screen. Is it possible ?

I use jquery viewportchecker but it does not seem to do that.

thank you very much !

**Comment by philipyoungg** [comment]
assuming you assign the timeline to variable `tl`:

beforehand, pause the timeline.
```javascript
const tl = anime.timeline({
  autoplay: false,
})
```
then with any viewport trigger, simply use `tl.play()`

**Comment by juliangarnier** [comment]
@Jimmylet @philipyoungg Yes, and you can also use `tl.pause()`when the item leaves the viewport.
