### ISSUE TITLE
Does it support react？

### ISSUE THREAD

**Issue by dushao103500** [juliangarnier/anime#136]
React is the general trend. Maybe it should support react!!   <Anime ...props  />

**Comment by Rosenblad** [comment]
I haven't tried it out with react myself but I've seen [this repo](https://github.com/hyperfuse/react-anime) which has a pre-made react component for working with anime.

**Comment by juliangarnier** [comment]
Yes react-anime is probably what you're looking for, but note that it still use anime v1.x.

**Comment by jduhls** [comment]
An example of updating a javascript object in state inside a class component instead of directly altering the DOM element ref:

```javascript
const style = this.state.style

animejs({
  targets: style,
  scale: 1.005,
  boxShadow: 8,
  update: a => this.setState({ style })
})
```

**Comment by lannex** [comment]
Is it impossible to use 'ref' as the 'targets'?
In my case it was okay.

**Comment by jduhls** [comment]
I think altering the ref node directly is considered antipattern because it bypasses the whole virtual dom magic. I try to avoid it and keep things declarative.

https://reactjs.org/docs/refs-and-the-dom.htm
