### ISSUE TITLE
Using anime for canvas property animation

### ISSUE THREAD

**Issue by renarsvilnis** [juliangarnier/anime#138]
Hi, 
is it possible to use anime for animating a value what is used in a canvas rendering?

I'd like to smoothly move the camera to a new position in a `three.js` scene after I get the new position for it. The target is a variable instead of a DOM node and I listen to an [`update` callback](http://anime-js.com/documentation/#allCallbacks) with the current animation value and I update the camera position and rerender the scene manualy.

**Comment by juliangarnier** [comment]
Yes you can animate a JS variable, see : http://anime-js.com/documentation/#JSobjectProp
