### ISSUE TITLE
Is it possible to set a property on an element without animation

### ISSUE THREAD

**Issue by nintra** [juliangarnier/anime#139]
Sometimes it is good to prepare elements or to set them to specific value (when no animation is needed). I wonder if anime has a method for setting for instance translateX. `anime.setValue(el, 'translateX', 32+'%')`

I know i can do it with plain javascript but the wrangling with different functions like `translate`, `rotate`, `scale` and their shortcuts is a bit tedious. anime probably already uses such function internally.

Anybody interested in such function?

PS: anime is a blast =)

**Comment by Eschon** [comment]
I'd like to have this feature as well.

I have a timeline animation where I move where I move an element out of the top of the screen. Later I want to move it back in from the bottom. It would be nice if I could move it there without an animation.

I tried setting the duration to 0 but then it didn't get moved.

**Comment by JulienJo** [comment]
You could use this code to prepare an element:
`translateX: ["31.999%", "32%"],`

At least, it worked for me.

**Comment by yckart** [comment]
```js
function stamp(params) {
  params.autoplay = false
  const anim = anime(params)
  anim.seek(anim.duration)
  return anim
}
```

**Comment by juliangarnier** [comment]
It's not planned, and Anime can't manage multiple transforms props if you don't specify them in the animation code, so it's basically the same as using plain JS.
