### ISSUE TITLE
Possibility of allowing custom cubic-bezier curves

### ISSUE THREAD

**Issue by lukebatchelor** [juliangarnier/anime#14]
Any chance you'd be willing to allow that? I had a look around and combined a few things into a codepen.
http://codepen.io/hotmilo23/pen/KMWXOQ?

Not sure which solution is giving the right answer, the slower one matches what I see in after effects.

If you didnt want it in anime itself, maybe just allow the use to pass in an easing function?

```
anime({
  targets: 'div',
  rotate: {
    value: 180,
    duration: 1500,
    easing: function(t) {
        return ...;
    }
  },
  direction: 'alternate',
  loop: true
});
```

Either way, we are looking at using this for a major project coming and would be happy to make PRs if you're willing. 

Cheers

**Comment by juliangarnier** [comment]
It's already possible by setting your custom easing to `anime.easings`.

```
anime.easings['myCustomEasing'] = function(t){return Math.pow(t,5)};

anime({
  targets: 'div',
  translateX: 200,
  easing: 'myCustomEasing',
});
```

http://codepen.io/juliangarnier/pen/vKxqmK/

But I like the idea to pass the function directly, it fits perfectly the API.
Definitely something that I'll consider.
