### ISSUE TITLE
Cancel?

### ISSUE THREAD

**Issue by bresson** [juliangarnier/anime#141]
Is there a way to cancel a scheduled animation? For instance, consider the code below. Can I cancel it while the animation is in the delay state? Animation state? Thank you!

```
const pageToTop = anime({
    targets : '.main-content--fullpage', 
    scale: 0,
    delay: 6000, 
    duration: 500, 
    easing: 'linear',
    elasticity: 0,
    complete: function(element) {
        console.log('completed pagetotop')
        document.getElementById('brand__band').classList.add('bounceUp--run')
        document.querySelector('.page').style.opacity = 1;
    }
})
```

**Comment by juliangarnier** [comment]
[animation.pause()](http://anime-js.com/documentation/#playPause) or [anime.remove(el)](https://github.com/juliangarnier/anime#animeremovetarget) ?

**Comment by bresson** [comment]
Great. I think pause() will work
