### ISSUE TITLE
Animate from a value set in CSS

### ISSUE THREAD

**Issue by joshsto** [juliangarnier/anime#143]
I'm probably missing something fundamental here, but when I try to animate something from a value set in css there is no transition.  The properties are still applied though.  Here's a quick codepen that hopefully demonstrates what I'm talking about: http://codepen.io/anon/pen/gmQPPz

The box has it's scale set to 0, and what I expect to happen when the button is clicked is for the box to animate to a scale of 1 - it just kind of pops in though.  I'm certain that I'm missing something though, so any help would be appreciated.

**Comment by luxlogica** [comment]
Workaround: if you explicitly define start and end values, it still works. 

Instead of `scale: 1` try `scale: [0,1]`.

**Comment by joshsto** [comment]
Interesting, thanks for the tip, it's working pretty well!
