### ISSUE TITLE
Safari: anime.setDashoffset causes "getTotalLength is not a function" error on svg circle element

### ISSUE THREAD

**Issue by demsullivan** [juliangarnier/anime#145]
Example:

http://codepen.io/anon/pen/KWbBmy

**Comment by demsullivan** [comment]
I've got a working fix specifically for circles... will elaborate to support other shapes and submit a PR later when I've got some time. Proposed fix:

```
  function setDashoffsetCircle(el) {
    var length = 2 * Math.PI * el.getAttribute('r');
    el.setAttribute('stroke-dasharray', length);
    return length;
  }
```

**Comment by adrianoresende** [comment]
I have this error too.
Reason for this error:
https://github.com/juliangarnier/anime/issues/155

**Comment by jeroenrinzema** [comment]
Got the same problem:
http://jeroen.no

**Comment by jeroenrinzema** [comment]
By looking at the problem did I find a way to solve it. By integrating a check if the given element is a "SVGLineElement" to the setDashoffset function.

```
function dist(x1, x2, y1, y2){
  return Math.sqrt( (x2-=x1)*x2 + (y2-=y1)*y2 );
}

function setDashoffset(el) {
  const isLine = el instanceof SVGLineElement;
  const pathLength = isLine ? dist(el.x1.baseVal.value, el.x2.baseVal.value, el.y1.baseVal.value, el.y2.baseVal.value) : el.getTotalLength();
  el.setAttribute('stroke-dasharray', pathLength);
  return pathLength;
}
```
SVGLineElement is [supported](https://developer.mozilla.org/en-US/docs/Web/API/SVGLineElement) by all modern browsers.
