### ISSUE TITLE
Play method restarts animation

### ISSUE THREAD

**Issue by davferguson** [juliangarnier/anime#146]
I have an animation of a car moving along a path.
If I call pause when the animation is running for the first time, it works fine. I can move the progress bar then call 'play', and the animation continues from that point. 
A problem occurs after the animation has ended. The animation works fine if I restart it by using the 'restart' method, but not when I restart it by calling 'play'. When I call 'pause' after restarting it with the 'play' method, the animation pauses, but when I call 'play' to continue the animation, it restarts from the beginning.

Here is my code: http://codepen.io/davferguson/pen/ZeVVQZ?editors=1010

**Comment by juliangarnier** [comment]
Try updating to 2.0.2.
Play() will no longer play the animation when ended, but the restart() / pause() / play() behaviours should work fine.

**Comment by juliangarnier** [comment]
Closing the issue for now, let me know if updating to 2.0.2 does't work for you.
