### ISSUE TITLE
Animation is not smooth and Caton in Chrom Canary 59

### ISSUE THREAD

**Issue by leuvi** [juliangarnier/anime#147]
browser version 
59.0.3062.1（正式版本）canary SyzyASan （32 位）
anime website is the same

**Comment by PDXIII** [comment]
The animation of the website’s title screen isn’t smooth in the latest Safari, but only in fullscreen view. 🤔

**Comment by juliangarnier** [comment]
I found a bug in Chrome Canary 59 where Array.reduce will return NaN after a few seconds when called inside a requestAnimationFrame.

If I use a polyfill instead of native Array.reduce everything works fine.

Not really sure what to do about it.

**Comment by leuvi** [comment]
@juliangarnier canary is an unstable version, it is possible to fix this bug. thank you!

**Comment by juliangarnier** [comment]
Chromium issue : https://bugs.chromium.org/p/chromium/issues/detail?id=708971#c1

**Comment by juliangarnier** [comment]
Problem solved on Chrome Canary 59.0.3065.0
