### ISSUE TITLE
Remove dependencies, use devDependencies instead

### ISSUE THREAD

**Issue by kritollm** [juliangarnier/anime#149]
Just noticed when installing from npm it adds a huge amount of npm modules because of this line:

```javascript
 "dependencies": {
    "google-closure-compiler-js": "^20170124.0.0"
  }
```

**Comment by juliangarnier** [comment]
Good catch, thanks!

**Comment by IlianYotov** [comment]
Do you plan a new release soon? It still downloads google-closure-compiler-js for 2.0.2 version. Thank you

**Comment by bravecow** [comment]
++, release without google-closure-compiler-js would be awesome.
