### ISSUE TITLE
Set default easing globally or for a timeline

### ISSUE THREAD

**Issue by tomsercu** [juliangarnier/anime#152]
Is there a way to set the default easing either globally,
or a default easing value for a specific timeline?
I imagine something like this:
```
TL = anime.timeline({autoplay:false,
                   easing:'linear',  // DOESNT WORK
                   update: function(anim) {seekbar.value=anim.progress;}  });
```

**Comment by tomsercu** [comment]
Actually uit would make sense to have `anime.setDefaults()` and `anime.timeline()` to set defaults for all `tweenSettings` like default `duration`,  `delay`, `elasticity` etc

**Comment by juliangarnier** [comment]
That's an interesting idea, will look into this.

**Comment by juliangarnier** [comment]
Added timeline parameters inheritance in 2.1.0 (targets, easing, duration, delay, round)
