### ISSUE TITLE
getTotalLength() is no longer supported

### ISSUE THREAD

**Issue by manar-mk** [juliangarnier/anime#155]
According to [this](https://developer.mozilla.org/en-US/docs/Web/API/SVGPathElement/getTotalLength)

SVGPathElement.getTotalLength() has been removed from the Web standards. Can you replace it with something else? It breaks the website

**Comment by adrianoresende** [comment]
I think this lib can be an alternative:
https://github.com/rveciana/svg-path-properties

**Comment by adrianoresende** [comment]
Tip:
In browser Chrome, use option `[anime.strokeDashoffset, 0]`, copy atribute `stroke-dasharray` generated and paste in HTML.
With `stroke-dasharray` in HTML, use this option:
```
anime({
    targets: '#signAdriano .st0',
    easing: 'easeInOutSine',
    strokeDashoffset: function(el) {
        return [el.getAttribute('stroke-dasharray'), 0]
    },
    duration: 700,
    delay: function(el, i) { return i * 250 }
});
``` 

iPhone and Safari work fine! ;)

**Comment by juliangarnier** [comment]
Will look into this, thanks for reporting it.

**Comment by leiserfg** [comment]
It method was not deleted, just moved to SVGGeometryElement, so in the future all geoms will have it. For now, we should use math for lines and circles.

**Comment by juliangarnier** [comment]
Looks like `SVGPathElement.getTotalLength()` will simply be replaced by `SVGGeometryElement.getTotalLength()`, so I don't see the need of changing anything here.

@manar-mk  can you share an example where this break something?

**Comment by juliangarnier** [comment]
Related #145
