### ISSUE TITLE
Does it work with zIndex?

### ISSUE THREAD

**Issue by evgeny-t** [juliangarnier/anime#156]
Hi,

I'm trying to update zIndex during the animation transition like following:

```
anime({
  targets: '.box',
  rotate: [45, 45],
  scale: [0, 5],
  zIndex: [1, 5],
  loop: true,
  duration: 10000,
});
```

but it seems that zIndex doesn't get changed. Here is a pen: http://codepen.io/evgeny_t/pen/VbLLBE

Is it possible to do with anime.js?

**Comment by juliangarnier** [comment]
z-index property doesn't accept decimals, that's why it jumps directly to 5.
Try rounding the value, like this :
````
anime({
  targets: '.box',
  rotate: [45, 45],
  scale: [0, 5],
  zIndex: {
    value: [1, 5],
    round: true
  },
  loop: true,
  duration: 10000,
});
````
