### ISSUE TITLE
Anime drawing not work

### ISSUE THREAD

**Issue by adrianoresende** [juliangarnier/anime#157]
Code: 
https://codepen.io/zullcore/pen/GmpGpQ

Why this code not work? This code is same of documentation.

Could it be the cause of imperfect path?
I just tested only the line (`#elSign2`) and it did not work either.

**Comment by snc** [comment]
You don't have specified any attributes to animate... I assume that you want to animate `strokeDashoffset` (like in the example).

**Comment by adrianoresende** [comment]
This work! Thanks a lot! ;)
