### ISSUE TITLE
Animating dollar amounts leaves out the decimal value when .00

### ISSUE THREAD

**Issue by cshomo11** [juliangarnier/anime#163]
I am using AnimeJS to animate donation totals changing after more donations have been received. The animation works great however when the new donation amount is a full dollar amount, like $50.00, the animation ends by cutting off the .00. I am using the numeral npm package to format all of my data coming in from a JSON call. Here is the code, it is part of a timeline.

`.add({
      targets: self,
      total: newValue.formatted,
      round: 100,
      easing: 'easeInOutQuad'
});`

I've also noticed when animating up, say from $20.00 to $40.00, every time the number animates to another .00, the number appears as $30. This throws off the width of the label and makes the animation look a little jittery.

**Comment by juliangarnier** [comment]
_Anime_ doesn't provide any formatting options.
What you can do instead, is format the value using _numeral_ in the `update()` function, like this:

```
var dols = {
  total: 0
}

anime({
  targets: dols,
  total: 100,
  round: true,
  easing: 'easeInOutQuart',
  duration: 3000,
  update: function(a) {
    var value = a.animations[0].currentValue;
    var formated = numeral(value).format('$0,0.00');
    console.log(formated);
  }
});
```

https://codepen.io/juliangarnier/pen/57c7ca4ab926fb551e5475723a0e04c4/?editors=1111

**Comment by cshomo11** [comment]
Ah that is what I needed, thank you very much!
