### ISSUE TITLE
【boxShadow,textShadow】 Shadow animation support

### ISSUE THREAD

**Issue by hetian9288** [juliangarnier/anime#164]

**Comment by juliangarnier** [comment]
related to #119 
Will look into this soon.

**Comment by satoshionoda** [comment]
Hi, is this implemented already?

I cannot animate text-shadow.
https://codepen.io/satoshionoda/pen/paEJKm

**Comment by monolithMktg** [comment]
Wow, no reply yet?

**Comment by different55** [comment]
There was a reply 6 years ago when it was opened, and then it was closed as completed along with the issue that was mentioned to be related.

**Comment by monolithMktg** [comment]
Ok i got it working. So apparently hex color values seem to have an issue. I converted that hex code to rgb() and it works with boxShadow, textShadow. Hope this helps you :)
