### ISSUE TITLE
Error: <rect> attribute transform: Expected ')', "rotate(0 NaN NaN)"

### ISSUE THREAD

**Issue by pastelsky** [juliangarnier/anime#167]
When I try to animate the `transform` attribute of a svg element, I get a series of following error - 
```bash
anime.min.js:25 Error: <rect> attribute transform: Expected ')', "rotate(0 NaN NaN)"
```
My tween looks like - 
```js
anime({
      targets: '#rect-top',
      x:[13, 0, 7, 1, -0.784, 0],
      y: [15, 4, 15, 1, 8.628, 0],
      width:[23, 54, 19, 55, 30, 49.5],
      transform: [
        'rotate(0 0 0)',
        'rotate(0 0 0)',
        'rotate(0 0 0)',
        'rotate(0 0 0)',
        'rotate(-30 14.215 10.88)',
        'rotate(0 0 0)',
      ],
  })
```

I'm not sure why it thinks the 3rd value is `NaN`, even though the format is correct.

**Comment by rd4k1** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate3d

**Comment by juliangarnier** [comment]
Will be fixed in next reelease. 
Related #119, #174
