### ISSUE TITLE
SVG Morph multiple paths

### ISSUE THREAD

**Issue by piskello** [juliangarnier/anime#168]
Hi,

I would morph multiple SVG path and I wrote this code following the documentation. The problem I found is that your example uses "polygon" instead of "path", and I can't understand how to make it work with paths. Here the code I'm using >> https://pastebin.com/sQWWYqQS

Thank you in advance,
matteo

**Comment by alexchantastic** [comment]
Here's what you're looking for: https://codepen.io/alexchantastic/pen/YQyoBN

Each of your path definitions don't need to be an object, they just need to be a array of strings. For example:

```
[
  'M1052.6,551.3c0,207.1-345,663.1-375,375s-375-167.9-375-375s297,93,375-375S1052.6,344.2,1052.6,551.3z',
  'M1036,542c240,141-167.9,375-375,375s39-228-375-375s167.9-375,375-375S796,401,1036,542z',
  'M865.2,302.7C1219,11,1044.9,1028.3,831.9,832S439.6,954,302.6,798.7S40.8,492.8,335.9,269.4S511.4,594.4,865.2,302.7z'
]
```

**Comment by juliangarnier** [comment]
#213 related
