### ISSUE TITLE
function for duration time is not working?

### ISSUE THREAD

**Issue by wposcars** [juliangarnier/anime#171]
When I tried to use anime with lettering for text, I just want to use function for duration but it's not run, I don't see it running inside duration function.
Demo at line 63: https://codepen.io/wposcars/pen/mmYWYL/

Thanks

**Comment by juliangarnier** [comment]
It's because you set the duration two times :
- globally with a function (line 63)
- individually to each keyframes (line 69 to 74)

Since each keyframe has their duration specified, the global duration will be ignored.

**Comment by wposcars** [comment]
ah yes, thanks Juliangarnier for quickly answer.
But I just want the text second, three,.. should later appear as you can see I did it with velocity: https://codepen.io/wposcars/pen/WjZoWm
can you suggest me any idea?
Thanks

**Comment by juliangarnier** [comment]
Duration doesn't help in that case, you have to change the initial delay.
Simply set the first keyframe delay to a function that will set deferent values for each element.

function textDelay(el, i) {
	return 0.2 * time + (i * 150);
}

```
var bouncingBall3 = anime({
	targets: '#testtext span',
	loop: true,
	translateY: [
    { value: -30, delay: textDelay, duration: 0.2*time, elasticity: 0, easing:[0.215, 0.610, 0.355, 1.000] },
		{ value: 0, duration: 0.1*time, delay:0.03*time,elasticity: 0, easing:[0.215, 0.610, 0.355, 1.000] },
		{ value: -15, duration: 0.27*time, elasticity: 0, easing:[0.755, 0.050, 0.855, 0.060] },
		{ value: 0, duration: 0.1*time, elasticity: 0, easing:[0.215, 0.610, 0.355, 1.000] },
		{ value: -4, duration: 0.1*time, elasticity: 0, easing:[0.755, 0.050, 0.855, 0.060] },
		{ value: 0, duration: 0.1*time, elasticity: 0, easing:[0.215, 0.610, 0.355, 1.000] }
  ]
});
```

https://codepen.io/juliangarnier/pen/6b380c32bf6fae88c36558ba31de07f1/

**Comment by wposcars** [comment]
OK, thanks Juliangarnier for quickly support,
This is good suggestion, let me try use it.

Thanks you again.
