### ISSUE TITLE
String paramaters to CSS properties

### ISSUE THREAD

**Issue by dpw1** [juliangarnier/anime#173]
Hi!

How could I set the "left" CSS property to "auto" within anime js?

Thanks!

**Comment by juliangarnier** [comment]
Hey,

You can't, _anime_ needs at least one digit in the value parameters in order to work.

**Comment by dpw1** [comment]
Hmm could I possibly add a class to the element on a 'complete' callback?

**Comment by juliangarnier** [comment]
Yes you can add a class on a `complete` callback, but I'm not sure to understand how this will help you animating to `auto`

**Comment by nassimdonald** [comment]
@dpw1 has a good point. Animating to an `"auto"` value could be very handy in Anime. Consider a use case like jQuery's `slideDown()` animation, where an element's is animated from `0` to `"auto"`, without having to show the element and manually calculate it's final height before hiding again and animating - very cumbersome!
