### ISSUE TITLE
IE11 Seek not working

### ISSUE THREAD

**Issue by rstadler333** [juliangarnier/anime#176]
Expected: open http://animejs.com/documentation/#seekAnim in IE11 and works as in any other browser

Actual result: no animation when using progress bar to seek. if timeline controls are used, play, pause, restart work. However the progress bar does nothing.

**Comment by huwllewellyn** [comment]
Edge and Internet Explorer have an inbuilt transition animation of about 0.2 seconds on their range inputs. So each call to update the range value starts a new transition request.
update: function(anim) { controlsProgressEl.value = anim.progress; }

This results in a divergence from the position of the timeline and the position of the thumb in the input type=range.

**Comment by huwllewellyn** [comment]
You'll have to look for 'change' as well as 'input' to get this working on IE and edge
`controlsProgressEl.addEventListener('change', function() {
  TLcontrols.seek(TLcontrols.duration * (controlsProgressEl.value / 100));
});`

**Comment by juliangarnier** [comment]
Fixed.
