### ISSUE TITLE
seek(0) does not set element properties

### ISSUE THREAD

**Issue by unstoppablecarl** [juliangarnier/anime#177]
Expected `translateX` to be set to `10` on element but was not set at all. 
```js
var seekAnim = anime({
  targets: '#seekAnim .el',
  translateX: [10, 250],
  autoplay: false
});

seekAnim.seek(0);
```

This creates desired effect but is unexpected.

```js
var seekAnim = anime({
  targets: '#seekAnim .el',
  translateX: [10, 250],
  autoplay: false
});

seekAnim.seek(1);
seekAnim.seek(0);
```

**Comment by TomS-** [comment]
Hey I was also having this problem, the hotfix I've found was deleting `&& insCurrentTime !== 0` from line 755.

I have no idea what implications this has though as I don't know exactly why we check if insCurrentTime isn't 0, just some lazy debugging.

This will make sure that the initial tween is set in your case translateX: 10px
