### ISSUE TITLE
Problem when no values unit is specified on Safari

### ISSUE THREAD

**Issue by towry** [juliangarnier/anime#18]
I have a div with those styles:

```css
position: absolute;
font-weight: normal;
line-height: 1.2;
text-align: center;
transition: opacity 0.4s ease;
z-index: 1;
```

Then I want to animate this element.

```js
 anime({
	targets: this.$els.tooltip,
	left: 116,
	duration: 500
});
```

I found that it is not working on safari, then I put some console in the anime.js, for example, in `setAnimationProgress` function, 

```js
var id = animatable.id;
console.log(progress);
switch (tween.type) {
// ...
```

The output is like this in safari:

![screen shot 2016-06-30 at 3 07 22 pm](https://cloud.githubusercontent.com/assets/8279858/16479660/67ae4e0a-3ed4-11e6-89b5-13f4c0f49085.png)

The output in Chrome is:
![screen shot 2016-06-30 at 3 08 35 pm](https://cloud.githubusercontent.com/assets/8279858/16479700/a6201c0e-3ed4-11e6-89a3-0804692e00b2.png)

Solution I found, change `left: 116` to `left: '116px'`.

**Comment by juliangarnier** [comment]
This is not really a bug, but its wasn't really clear in the documentation.
It's recommended to use the full value e.g. '100px' on properties that aren't specified in the CSS.
I updated the doc and example
