### ISSUE TITLE
SynatxError with Gulp

### ISSUE THREAD

**Issue by mmason33** [juliangarnier/anime#180]
Experiencing syntax errors during gulp task. I imagine I am most likely doing something wrong. Figured I would open up an issue anyway. Great library btw!
Using:
Sage Starter Theme  v8.5.1
Gulp v3.9.1
Bower 1.8.0
NPM v4.0.5
Node v6.10.3

![gulp-error](https://cloud.githubusercontent.com/assets/22351595/26797800/fbb0cc6c-49e2-11e7-898a-9830a5257c5b.PNG)

**Comment by juliangarnier** [comment]
What file are you using?

anime.js uses ES6 syntax, try using anime.min.js (ES5).

**Comment by mmason33** [comment]
That's definitely my issue. I don't have ES6 support. Thank you for the quick reply. I should be able to fix my workflow appropriately with this information. Really appreciate it and again, great library!
