### ISSUE TITLE
Seek and timeline doesn't work together?

### ISSUE THREAD

**Issue by JulienJo** [juliangarnier/anime#181]
Hi!
I would like to have the ability to skip an animation made with a timeline. Seek seems to not work. Restart does.
Anybody has an idea why?
https://codepen.io/Julien-Jolly/pen/pwobjM

Cheers!

**Comment by juliangarnier** [comment]
Hi,

`seek()` uses ms, not percents.
Try using `loginAnimation.seek(loginAnimation.duration);` instead.

**Comment by JulienJo** [comment]
Nice!
Thanks!
