### ISSUE TITLE
Animating text with the CSS transform "scale" property results in slightly jittery movement

### ISSUE THREAD

**Issue by AaronBeaudoin** [juliangarnier/anime#182]
CSS transitions using `transform: scale(num)` are perfectly smooth. Is there any way to get the beautiful rendering that results from CSS while using Anime.js?

I'm using Chrome on Windows 10.

**Comment by juliangarnier** [comment]
Can you provide an example?
I tried animating some text with scale using both technics and I don't see any differences.

**Comment by AaronBeaudoin** [comment]
Your example actually does show a difference for me actually! The Anime text on the left jitters as it scales but the CSS is perfectly smooth. This issue is driving me crazy because I can't figure out what's causing it.

I don't know much about browser rendering. I don't know if this is the wrong place to discuss this issue, but I can say that all the animations runs perfectly on my iPhone. It's just on my Windows 10 laptop that the text scaling is jittery.

**Comment by juliangarnier** [comment]
I see, I'm on a retina macbook pro, that's probably the reason why the jittering is less visible on my side.

You can try adding `will-change: transform;` on your text see if it changes something.

**Comment by AaronBeaudoin** [comment]
Adding `will-change` seemed to cause the text to go blurry, I'm assuming that's due to hardware acceleration.

I have a theory. Maybe the frame by frame animation is causing the text to be re-rendered in a way that causes the jittering. I checked how the animation looked on my retina Macbook Pro as well, and if you look really closely there is actually a tiny bit of jitter, but it's barely noticeable due to the high resolution.

What I don't get is how the CSS scaling is so buttery smooth. There must be some sort of anti-aliasing technique or something making it run so nicely. Again though, my rendering knowledge is super low.

**Comment by JulienJo** [comment]
Interesting....
You could try this way: 
- add will-change
- instead of growing try to reducing
https://codepen.io/Julien-Jolly/pen/RLjZyW

**Comment by juliangarnier** [comment]
Closed since I don't think this is anime.js related.
