### ISSUE TITLE
Update an animation

### ISSUE THREAD

**Issue by NiklasLazinbee** [juliangarnier/anime#183]
Hello,
I want to update an animation but it don't work. Here I change the duration after the animation is complete:

https://jsfiddle.net/0mLnp66p/

-> Line 39

But the effect is more than like delay? Is there any chance to update an animation?

Beste regards 
Lazinbee

**Comment by juliangarnier** [comment]
No you can't.

You have to create both open and close animations, set the close animation `autoplay` parameter to `false`, and call `closeAnimation.play()` on `openAnimation.complete`.

**Comment by NiklasLazinbee** [comment]
Thanks for the reply. It would be a good feature to update an animation. In one project I have about 20 different animations, if there is a chance to update some of this it will reduce the code.

But first of all anime.js is a great work!

**Comment by juliangarnier** [comment]
You can also wrap your animation in function like this :
```
  function animate(el, x, duration) {
    anime({
      targets: el,
      translateX: x,
      durarion: duration
    });
  }

  animate('.mydiv', 200, 2000);
```

or

```
  function createAnimation(el, x, duration) {
    return anime({
      targets: el,
      translateX: x,
      durarion: duration
    });
  }

  const myanimation = createAnimation('.mydiv', 200, 20000);
```

**Comment by NiklasLazinbee** [comment]
Thanks a lot, this is verry helpful.

Beste regards 
Niklas
