### ISSUE TITLE
Best way to convert my animation into high quality animated .gif 

### ISSUE THREAD

**Issue by gidimaker** [juliangarnier/anime#185]
Dear Julian and all other Experts,

Please let me know what is the best (right) way to save the animation, made with anime.js, as high quality animated .gif? 
Just like Julian did here: [http://animejs.com/documentation/assets/img/readme/animejs-logo.gif]

Thank you in advance for your advice.

**Comment by MichaelRise** [comment]
You can record screen and convert video to gif.
Sometimes I use Open Broadcaster Software and Adobe Media Encoder.

**Comment by gidimaker** [comment]
Thank you very much.
I'm on Linux, so I'll try Open Broadcaster.

**Comment by leeoniya** [comment]
https://github.com/colinkeenan/silentcast

**Comment by gidimaker** [comment]
Thank you, leeoniya.
I'll make a try with this one too.

**Comment by juliangarnier** [comment]
I recommend http://gifbrewery.com/, but it's Mac only.

**Comment by alexchantastic** [comment]
In you're looking for a command line tool, I like [gifify](https://github.com/vvo/gifify).

**Comment by gidimaker** [comment]
Thanks for suggestions.
I have to make video first, so I spent all day playing with Open Broadcaster Studio trying to record the animation. Unfortunately I wasn't able to achieve reasonable quality.
Maybe the problem is my laptop's screen resolution (1366x768) or simply Mac does all the tricks?

**Comment by gidimaker** [comment]
So probably my question wasn't right from the beginning?
I had to ask you how to make video file first ...

**Comment by juliangarnier** [comment]
I don't think this is the right place for asking this.
I'm closing the issue.
