### ISSUE TITLE
[Suggestion] Transform properties inherit current set properties

### ISSUE THREAD

**Issue by TomS-** [juliangarnier/anime#187]
If something is set to translateX(-50%) for example, when you choose to translateY() it will forget translateX() set in CSS. 

Unlike things like background will animate from the CSS property to the new colour.

**Comment by alexchantastic** [comment]
I believe this is a dupe of #77.

**Comment by TomS-** [comment]
@alexchantastic yup sorry, definitely worth doubling the size of the library for this. 11KB over TweenMax's 110KB (I'm amazed).
