### ISSUE TITLE
Zurb Foundation6 : Uncaught TypeError: Cannot set property 'anime'

### ISSUE THREAD

**Issue by tkyndsn** [juliangarnier/anime#190]
Have this error when compiled with Foundation 6 gulp ([Zurb Stack](http://foundation.zurb.com/sites/docs/starter-projects.html)) :
<img width="349" alt="capture d ecran 2017-06-14 a 23 44 15" src="https://user-images.githubusercontent.com/10993236/27159526-432a146e-515d-11e7-9c94-289380a788ba.png">

**Comment by juliangarnier** [comment]
Sorry I don't use foundation, but I'm pretty sure this is related to the way the gulp file is configured and has nothing to do with anime.js codebase.
