### ISSUE TITLE
The "function based values" example on the documentation page shows an unexpected behaviour

### ISSUE THREAD

**Issue by owenders** [juliangarnier/anime#191]
The "function based values" example on the documentation page shows an unexpected behaviour. Indeed, we can see that the translateX and translateY are not animating in parallel (so the div don't move diagonally but vertically then horizontally or vice versa) it seems that there is a different delay between these properties animation though the documentation mentions that function based property parameters get different values (of delay for example) for every target and not for every target and property. Could you please clarify? Could you also please explain why the duration property is mentioned twice (one with anime.random(1200, 1800) and the other with anime.random(800, 1600)) and what is its effect (it isn't explained in the documentation).
Thank you in advance for your explanations.

**Comment by juliangarnier** [comment]
You're right, it was misleading, but having different values for every target and property is the correct behaviour.

Will be fixed in next release.

(The double duration was a typo)

**Comment by owenders** [comment]
Thank you very much for these clarifications !
