### ISSUE TITLE
Target element's transform 'scale' properties from css overidden

### ISSUE THREAD

**Issue by fariskas** [juliangarnier/anime#192]
I'm trying to animate my circle from scale 0 to scale 1 (or any other values) with anime.
But im having issue where the initial 'scale 0' is not respected at all, and thus the circle already starts with scale 1 (default).

How can i animate the circle from from 0 to 1

```
.circle {
    width: 213px;
    height: 213px;
    transform: scale(0);
}

var toCenter0 = anime({
  targets: '.circle',
    scale: [ { value: 1 }, { value: 2 }, { value: 3 }, { value:4 } ],
    duration: 1500,
    easing: 'easeInOutQuad'
});


```

**Comment by juliangarnier** [comment]
Hello

`{value: [0, 1] }`

http://animejs.com/documentation/#specificInitialValue
