### ISSUE TITLE
Timeline Controls won't track properly on Edge/IE range input

### ISSUE THREAD

**Issue by huwllewellyn** [juliangarnier/anime#193]
Edge and Internet Explorer have an inbuilt transition animation of about 0.2 seconds on their range inputs. So each call to update the range value starts a new transition request. 
`  update: function(anim) {
    controlsProgressEl.value = anim.progress;
  } `

This results in a divergence from the position of the timeline and the position of the thumb in the input type=range.

**Comment by juliangarnier** [comment]
Related #176
