### ISSUE TITLE
animate multiple objects around same path with different starting points

### ISSUE THREAD

**Issue by eliteproxy7** [juliangarnier/anime#195]
can i animate multiple objects to the same path but each object has a different starting point?

<img width="347" alt="screen shot 2017-06-22 at 7 55 16 pm" src="https://user-images.githubusercontent.com/5486268/27460983-82183312-5785-11e7-8bdc-9c31c5653a15.png">

**Comment by MichaelRise** [comment]
Hey,

Yes this is possible.
You must add data attributes to each item in HTML.
You must create loop and get data attribute for each item - for position, delay, time etc.

Example:
```
var el = document.getElementsByClassName('animejs-element');
for (var i = 0; i < el.length; i++) { // No caching - faster
//for (var i = 0, len = el.length; i < len; i++) { // Caching
	var animatedElement = el[i];
	animation(animatedElement);
}

function animation(animatedElement) {
	var animationDuration = parseInt(animatedElement.getAttribute('data-duration'), 10) || 400,
		animationDelay = parseInt(animatedElement.getAttribute('data-delay'), 10) || 0,
		animationOffset = animationDuration + animationDelay;
	
	timelineOffset
		.add({
			targets: animatedElement,
			duration: animationDuration,
			delay: animationDelay,
			width: '100%'
		})
		.add({
			targets: animatedElement,
			duration: animationDuration,
			width: '0',
			offset: animationOffset
		});
}
```

**Comment by juliangarnier** [comment]
Something like @MichaelRise suggested should work.
But this isn't the right place to ask for help for your animations.
Try https://stackoverflow.com/search?q=anime.js instead.
