### ISSUE TITLE
Stop a looping animation

### ISSUE THREAD

**Issue by Rowanism** [juliangarnier/anime#198]
Hello,

I have had very good experience with anime.js so far. It's really simple and powerful.
A thing I noticed while working with it:

If an animation is set to loop, and at some point another animation is played on the same target, after the second animation has finished, it resumes with the first, looping, animation.

Example:
[https://codepen.io/Rowanism/pen/mwqWZp](https://codepen.io/Rowanism/pen/mwqWZp)
(Mouseover for simple demonstration)

This is a good thing, but I have yet to find out how to make the 2nd animation permanent.
i.e. stop/pause the looping animation.

Any ideas? Thank you very much.

**Comment by snc** [comment]
Change your `loopAnim.pause;` to `loopAnim.pause();`

**Comment by Rowanism** [comment]
> Change your loopAnim.pause; to loopAnim.pause();
Thank you. Unfortunately, I have tried this before and it yielded the same result.

**Comment by snc** [comment]
With `loopAnim.pause();` it works like expected by me. The loop animation stops on `mouseenter` and the hover animation is played once. So what exactly do you expect?

**Comment by Rowanism** [comment]
Oh I see. I figured to put `loopAnim.pause();` at the completion of the hover animation, but you have to pause the loop, then play the hover animation. Thank you very much.

Knowing that, the thing has become much more versatile.
