### ISSUE TITLE
opacity animation 

### ISSUE THREAD

**Issue by robbisy** [juliangarnier/anime#199]
Hi I've got an issue with opacity. I wanted to make an opacity animation on click like when you click the opacity of a span go from 0 to 1 with a duration of 3 second and a delay of 3s too. But something the animation bugs and flash like opacity go 0 to 1 to 0 to 1. 
Made a demo here : [codepen](https://codepen.io/anon/pen/XgVYoj)

**Comment by snc** [comment]
The default easing might be a problem here, you can try to add `easing: 'linear'` for example.

**Comment by bravecow** [comment]
+1, i think this issue should be covered in docs 😶

**Comment by juliangarnier** [comment]
I added the opacity property to the CSS property example animation in the doc.
Should helps people understand what to do in order to have nice opacity transition.
