### ISSUE TITLE
Grouping all animations into one single RAF

### ISSUE THREAD

**Issue by juliangarnier** [juliangarnier/anime#20]
Right now every `anime` instance will create a new RAF.
I started doing some performance test with a single RAF, and the results are really good (up to 20/30% faster when a lot of animation are running simultaneously).
You can test it here https://github.com/juliangarnier/anime/tree/single-RAF.

My only concern is the use of performance.now(), not sure if it's still too early to use http://caniuse.com/#feat=high-resolution-time.

Some tests:
Old:
http://codepen.io/juliangarnier/full/545d66779d81ee68062bc8db018f6ee1/

New with a single RAF:
http://codepen.io/juliangarnier/full/f56c939864ea6b1b6efa8726e7ea8119/

Feedbacks are welcome.

**Comment by devmario** [comment]
If you use single RAF, I have an idea
For example
```js
var factory = new animeFactory();
var aim = new anime();
factory.add(anim);
factory.tick(timeElepse/* avail negative */);
``` 
We can create slow-motion animation and invert animation, as applied to all animation on browser.

**Comment by devmario** [comment]
@juliangarnier 
How about this
http://jsfiddle.net/devmario/9d8orpg5/12/

**Comment by juliangarnier** [comment]
@devmario It's an interesting idea, but I cant think of any real use cases of this.
Looks cool though.

**Comment by ngokevin** [comment]
Creating multiple RAFs is bad for performance. I was using it for 3D/VR, but had to switch back to Tween.js because I wasn't able to control when the animations ticked.

**Comment by juliangarnier** [comment]
Anime only creates one single RAF, and stop ticking when there is nothing to animate.
I also use the update() callback whenever I need a RAF call, like this:

```
var loop = anime({
  update: function() { do stuff.. },
  duration: Infinity
});

loop.play();
loop.pause();
```

That way I'm not creating extra RAF, and I can control when something is running or not easily.

Regarding performance, V2 will considerably improve speed on complex animations, around 1.5x faster. (You can try it here: https://github.com/juliangarnier/anime/tree/v2.0)

**Comment by ngokevin** [comment]
Awesome! It won't work for my cases though. For 3D/VR scenes, there's already an existing RAF (the render loop), and for those cases, we want to control the animation to update only once per frame. Something like:

```js
render: function (time) {
  // ...
  anime.tick(time);
  // ...
}
```

**Comment by juliangarnier** [comment]
I think it's actually possible to do what you described.
Anime expose the .tick() function of an animation, and you can do things like this :

```
var myAnimation = anime({
  targets: '.particule',
  translateX: 100,
  autoplay: false
});


function render(time) {
  myAnimation.tick(time);
  requestAnimationFrame(render)
}

render();
```

**Comment by ngokevin** [comment]
Thanks, that looks perfect! Will give it a try.
