### ISSUE TITLE
Question: duration

### ISSUE THREAD

**Issue by CoderSquirrel** [juliangarnier/anime#205]
Hi i already ready here that duration cant be change on runtime but if i, using angular, define the duration as a $scope.duration when the animate is created the $scope.duration will be converted by time?
or anime will keep using the variable and thus, changing the variable i change the animation time?
thx

**Comment by aminmeyghani** [comment]
Hey @juliangarnier, given an animation object, is it possible to change the duration in the `begin` callback?

**Comment by juliangarnier** [comment]
No, It's not possible to change the duration on runtime.
Related #210
