### ISSUE TITLE
Setting perspective value for a rotate transform

### ISSUE THREAD

**Issue by aminmeyghani** [juliangarnier/anime#207]
When setting the perspective property, the transform string ends up with a semi colon:

Given:

```
var front = anime({
  targets: '.my-front-card',
  perspective: '800px',
  rotateY: [0, -179.9],
  delay: 1000,
  duration: 500,
  easing: 'easeInOutSine'
});
```
Result:

`transform: rotateY(-179.9deg); perspective: 800px;`

I have tried the following as well just to set the perspective value for the rotate:

```
var front = anime({
  targets: '.my-front-card',
  rotateY: [0, -179.9],
  perspective: ['800px', '800px'],
  delay: 1000,
  duration: 500,
  easing: 'easeInOutSine'
});
```

But the inline style turns out to be like this:

`perspective: 800px; transform: rotateY(-179.9deg);`

How can I set the perspective?

Thanks!

**Comment by juliangarnier** [comment]
Will be fixed in next release.
