### ISSUE TITLE
[Feature Request] Set and Read properties

### ISSUE THREAD

**Issue by TomS-** [juliangarnier/anime#208]
AnimeJS is amazing, however for this current project I need to set transform properties without animating them. I can do this using javascript however it becomes problematic when I need to set TranslateX, TranslateY and Scale. 

duration: 0 doesn't work, I was wondering if anime.set() function could be made available and maybe anime.css() to read a value. 

I am making a drag and drop module for a website, something that I would like to use the power of AnimeJS for.

something like
```
anime.set({
    targets: ".block",
    translateX: current.x + (e.clientX + mouse.x),
    translateY: current.y + (e.clientY + mouse.y),
    scale: anime.css(".block", "scale")
});
```
or
```
anime({
    targets: ".block",
    translateX: current.x + (e.clientX + mouse.x),
    translateY: current.y + (e.clientY + mouse.y),
    scale: anime.css(".block", "scale"),
    duration: 0
});
```

**Comment by glomotion** [comment]
+1!
I'm just now also trying to do something similar - and the only way I can see to find is to use a tiny duration, like 1ms. 
eg:

```
anime({
    targets: els,
    translateX: 300,
    duration: 1
});
```
It would kinda be nice to be able to use a simple set method.

**Comment by juliangarnier** [comment]
`duration: 0` and `seek(0)` will be fixed in the next release.
Related #177, #228
