### ISSUE TITLE
Smooth staggered repetition with overlapping elements, or Only delay the first loop?

### ISSUE THREAD

**Issue by Splendorr** [juliangarnier/anime#209]
I'm really enjoying Anime! I'm trying to do something that seems possible, and yet I can't figure it out.

Basically: I want to have a steady loop of 4 elements, where the first starts at 0, and each subsequent element begins 1 second after the one prior. I can do that. But then I want the whole animation to loop on top of itself, so that the first element loops before the last element finishes.

Here's a pen that approaches the goal, but does not reach it: https://codepen.io/splendorr/pen/dRxjOy

You can see that on the first pattern, they begin in sequence. However, each repetition of each element is delayed _again_ by its initial delay value, which immediately throws them out of sequence. I've tried to dynamically change the element's delay after it runs the first time but maybe I'm not doing that right? It seems like the simplest solution would be, "Delay on first run, but don't delay when looping." Is that possible?

I've tried all kinds of things. This example starts with an existing element, clones it, and applies an animation to each element (following the example here: https://codepen.io/juliangarnier/pen/PpoboR). I've tried to distill this from my real-world implementation as simply as I could. No matter what I do, no matter where I've tried to re-assign the delay, I can't get them to smoothly loop without getting further and further out of sync.

I also tried starting each animation within a setTimeout of 1000, but that drifted out of sync also. Maybe I should just do that, but with requestAnimationFrame instead of setTimeout? I just don't know why I can't get this to happen within Anime itself?

Thanks for your help!

**Comment by juliangarnier** [comment]
I might add a new direction mode, `direction: 'staggered'` for looping back to the delay value instead of 0, that ways multiples animations can loop smoothly.

What do you think?

**Comment by juliangarnier** [comment]
Finally found a way to achieve this effect by fixing some begin() callback issues in 2.2.0.
Take a look at this animation https://codepen.io/juliangarnier/full/rGjMyW/ and let me know if it was what you were looking for?

**Comment by Splendorr** [comment]
@juliangarnier This looks great! This works differently from anything I'd tried; I haven't played with the begin() callback or calling tl.restart() on complete. But this achieves the effect! And it's really pretty, too. 😄 

I made something work for my project by putting each instance into its own function that called the next animation on complete(), with the last calling the first. Nowhere near optimal, but it worked for the project. I appreciate you taking the time, and will see about re-implementing with this technique in 2.2.0!

**Comment by zjjjjjjjjjjd** [comment]
can not
