### ISSUE TITLE
Question: setting animation properties dynamically

### ISSUE THREAD

**Issue by aminmeyghani** [juliangarnier/anime#210]
Is it possible to set the properties of an animation (eg duration) dynamically? For example, I'm trying it out with Angular, using an input field I'm trying to change the duration of the animation dynamically. But it seems like once the animation properties is set, you can't change it ... . I have tried resetting the animation, and emptying the running instances ...

**Comment by thammin** [comment]
Function based parameters was supported. You can use function to return dynamic value to anime.
http://animejs.com/documentation/#functionBasedDuration

**Comment by juliangarnier** [comment]
No, once the instance is created, you can't change the duration.
You have to create a new animation from scratch.
