### ISSUE TITLE
Animate complex DOM attributes

### ISSUE THREAD

**Issue by Disorrder** [juliangarnier/anime#211]
Well, animejs is good and simple animation lilbrary. It looks perfect with DOM attributes and CSS properties at all. I love `anime.timeline` to animate objects on 3D scene. But! I'm developing WebGL applications with A-Frame (based on three.js) and have a trouble to animate complex attributes. Example:
```html
<a-sphere id="sphere" position="1 2 3" radius="1" material="opacity: 1;"></a-sphere>
```
Now, I want to make difficult animation with change position and radius of sphere. Opacity is just example, there is can be any component.
```
var timeline = anime.timeline()
```
Now, change radius, it's piece of cake:
```
.add({
  targets: '#sphere',
  radius: 5
})
```
But I have trouble with `position` because it's Vector3 and coordinates are serialized to DOM property like `x y z`. Look here:
```
let sphere = document.getElementById('sphere');
let spherePosition = sphere.getAttribute('position'); // returns {x: 1, y: 2, z: 3}
timeline.add({
  targets: spherePosition,
  y: 10,
  run() {
    sphere.setAttribute('position', spherePosition); // serialize back animating object to attribute each animation's tick
  }
})
```
Looks weird :( I need to alloc extra memory and manipulate with extra objects to make such simple animation. I don't asking to realize such feature, I'm asking to think how to make plugins for animejs to allow such options like serialization or smth like that. Format what I want:
```
timeline.add({
  targets: '#sphere',
  position: {x: 1, y: 10, z: 3}
})
```

**Comment by juliangarnier** [comment]
You're not the first to ask for this, but it's not possible.
Objects are already used as animation values for specific property timings.
I prefer to keep things simple for now.
