### ISSUE TITLE
Begin callback in tween sometimes not called

### ISSUE THREAD

**Issue by siassaj** [juliangarnier/anime#215]
animejs 2.0.2

https://gist.github.com/siassaj/b67808452361ddc307b5262a3f93904b

This happens only when my browser is busy during page load, but _after_ all of my js code has been loaded entirely and the button on the page that triggers it has been bound.

Aside from that, it behaves completely normally... very odd that the first tween's complete fires and the last one's complete fires but it's begin doesn't.

**Comment by siassaj** [comment]
I don't get any weird behaviour when I move the functions i want called on tween 2 begin to tween 1 complete.

**Comment by juliangarnier** [comment]
The Timeline callbacks code has been rewritten and improved, it should be fixed in 2.1.

**Comment by siassaj** [comment]
@juliangarnier cheers. I'll let you know if it occurs after migrating over.
