### ISSUE TITLE
addEventListener does NOT work with animejs

### ISSUE THREAD

**Issue by czelusniakdawid** [juliangarnier/anime#216]
I want to make images bigger on hover. Could you help me what I am doing wrong ?

https://jsfiddle.net/8d0gp1v5/2/

**Comment by thammin** [comment]
You should pass the bound function instead of executing it before pass to `addEventListener`.
https://jsfiddle.net/8d0gp1v5/3/

**Comment by czelusniakdawid** [comment]
Thank you for your response! Now it works!
