### ISSUE TITLE
Animation on mobile not working

### ISSUE THREAD

**Issue by zixxus** [juliangarnier/anime#219]
Hello, I have problem with rotate animation on my website. Normally rotation work perfect but when I try to run it on mobile I have problem because animation not running.

You can test it on my www: [http://twsoft.pl/avoria/index.php/home](url)

My code:

`
function animate(target) {
	var przelicznikProcentowy = 75;
	var wspolczynnik = (75*1)/count_array.length;

	if(wspolczynnik > 2){
		wspolczynnik = 2;
	}

	// console.log(wspolczynnik);
	// console.log(przelicznikProcentowy);
	// console.log(count_array.length);

	// 75 - 1
	// count_array  - x%

	// if (verifyDataCheck() == 0) {
	// 	return false;
	// }

	// if (nowBlockAnim == 1) {
	// 	return false;
	// }

	if (run_anim_after == 0) {
		run_anim_after = 1;

		$('.kolotexty').find('span').removeAttr('style');

		var basicTimeline = anime.timeline({
			autoplay: true,
			// direction: 'alternate',
			loop: false,
			update: function(anim) {
				// console.log(anim.progress);
				// console.log(+'::::::'+);
				if (anim.progress == 100) {
					matematyka1(target);
				}
			},

			complete: function(anim) {
				// console.log(anim)
				// // matematyka1(target);
				// matematyka1(target);
			}
		});

		fake_rotate = actual_rotate;

		// var dv1 = random(40, 200),
		// 	dv2 = random(240, 450),
		// 	dv3 = random(460, 750),
		// 	dv4 = random(800, 1000),
		// 	dv5 = random(450, 750),
		// 	dv6 = random(240, 440),
		// 	dv7 = random(40, 200);
		var dv1 = Math.floor(random(400, 600)*wspolczynnik),
			dv2 = Math.floor(random(300, 400)*wspolczynnik),
			dv3 = Math.floor(random(120, 300)*wspolczynnik),
			dv4 = Math.floor(random(55, 100)*wspolczynnik);

		fake_rotate = fake_rotate + dv1 + dv2 + dv3 + dv4 ;

		var cachedegre = Math.round((fake_rotate/20))+1;
		console.log('cachedegre '+cachedegre);
		end_degree = (cachedegre*20)+10;
		console.log('cachedegre20 '+(cachedegre*20));

		console.log('pierdole'+end_degree);

		// end_degree = dv7 + 8;
		// end_degree = fake_rotate;

		basicTimeline
			.add({
				targets: target,
				'rotate': [{
					value: '+=' + dv1,
					duration: 700,
					elasticity: 1000
				}, {
					value: '+=' + dv2,
					duration: 700,
					delay: 0,
					elasticity: 1000
				}, {
					value: '+=' + dv3,
					duration: 700,
					delay: 0,
					elasticity: 1000
				}, {
					value: '+=' + dv4,
					duration: 900,
					delay: 0,
					elasticity: 1000
				},  {
					value: end_degree,
					duration: 900,
					delay: 0,
					elasticity: 1000
				}, {
					value: '-=2',
					duration: 500,
					delay: 0,
					elasticity: 500
				},  {
					value: '+=1',
					duration: 800,
					delay: 0,
					elasticity: 500
				}, ],
				easing: 'linear',
				offset: 0
			});
		console.log('eddd' + end_degree);

		basicTimeline.play();
		$('.kolotexty').removeClass('withoudDrag');

	}
}
`

**Comment by juliangarnier** [comment]
Hey, sorry but this isn't the right place to ask for help for your animations.
https://stackoverflow.com/search?q=anime.js
