### ISSUE TITLE
SVG morphing - yoyo support

### ISSUE THREAD

**Issue by patrickbjohnson** [juliangarnier/anime#221]
Here's a quick demo of an SVG morphing between shapes: https://codepen.io/pbj/pen/rzYJNG

At the end of the animation sequence it "snaps" back to the original path value and then starts over again. 

Is there any api option that allows it to not snap back but "yoyo" or seamlessly morph back to the original shape without any abrupt change of the SVG?

**Comment by thammin** [comment]
http://animejs.com/documentation/#alternate
Maybe `direction: alternate` fits your need.

https://codepen.io/anon/pen/eEyeMX

**Comment by juliangarnier** [comment]
@thammin is right.
