### ISSUE TITLE
Calc for width??

### ISSUE THREAD

**Issue by Crashtor** [juliangarnier/anime#223]
Why can't I use calc(100% - 50px) for setting width and other things?

**Comment by juliangarnier** [comment]
It's a bug, #119 related.

**Comment by Crashtor** [comment]
Perfect!!! Thanks Julian! Do you have a patreon page or somewhere I can donate?

**Comment by lpeppe** [comment]
Hi, I'm sorry to reopen this issue but I'm still facing this bug.

**Comment by Theo-Rige** [comment]
Same, "calc(100% + ((100vw - 1024px) / 2))" for translate doesn't work for me.
