### ISSUE TITLE
Conversion to pixel

### ISSUE THREAD

**Issue by sainf** [juliangarnier/anime#225]
Hi

Is it possible to use `right: ['50%', '100px'],` ? for now it converts % to px.

**Comment by juliangarnier** [comment]
Hey, nope, not possible, both values must have the same unit.

**Comment by eybarta** [comment]
Hi @juliangarnier, thanks for all your work. piggybacking on this issue, will this be possible in future versions?

animating from px to % is a pretty common need in my experience, for example, a sequenced animation to open a menu, which starts off as a round hamburger menu icon and when clicked opens up to full width.. The initial size of the menu is in px and opens up to 100% > Is there a recommended alternative way to achieve this type of animation without using two unit types? thx!
