### ISSUE TITLE
Animating the Property Offset of an SVG Gradient

### ISSUE THREAD

**Issue by edenprojectde** [juliangarnier/anime#229]
Well .. as the name 'offset' is taken by the animating properties it seems impossible to me to animate it per the usual way.

**Comment by juliangarnier** [comment]
Yes, that's the downside of having a single object for both animatable properties and settings.
Prior to 2.x there weren't too much "locked" properties.
I might change some of the property names, or change the API style in the future.

Any suggestions are welcome.

**Comment by edenprojectde** [comment]
Maybe changing it to this style:
```
css: { offset: x, height: x,... }
html: { offset: x, height: x,... }
```
or this one:
```
css-offset: x,
tag-offset: x / html-offset: x
```

^ this style doesn't have to be the main way to declare these kind of properties; the old way works pretty dandy. Just as another notation way. Love the way it is. I got a workaround to get this to work now too.

_Can't really help with the code though. Never really used Github to make Pull Requests(i suppose thats how you call code submissions right?)_

**Comment by iconexperience** [comment]
Offset can relate to many dimensions: xOffset, yOffset, timeOffset. So maybe in the next major update renaming `offset` to `timeOffset` would be a way to solve this.

**Comment by zanetaylor** [comment]
Would it make sense to add a prefix to the property that could also be used consistently across the other settings properties, to prevent future name conflicts? Something like `animOffset`?

**Comment by juliangarnier** [comment]
The offset property has been replaced by timelineOffset in V3.
