### ISSUE TITLE
Animate with no special easing

### ISSUE THREAD

**Issue by StrangerPings** [juliangarnier/anime#232]
I am trying to animate a circle going around using just anime.js.  All is good for the rotation except for the easing.  I do not want any custom easing so it rotates around in a seamless loop.  How can I stop anime.js from adding a tween effect to the element?

Here is my JS
```
var wheel = anime({
	targets: '#wheel',
	duration: 10000,
	rotate: 360,
        direction: 'reverse',
	loop: true,
});
```

**Comment by alexchantastic** [comment]
You can specify an [easing function](https://github.com/juliangarnier/anime#easing-functions). Maybe try `easing: 'linear'`?

**Comment by StrangerPings** [comment]
Thank you!
