### ISSUE TITLE
Responsive Motion Path?

### ISSUE THREAD

**Issue by eiranix** [juliangarnier/anime#234]
Is it possible to calculate a motion path that is scaled with the parent width?
Or perhaps some way to get the x/y position before it's applied to the element and use some math to scale down?

**Comment by e-g-b** [comment]
This might help resolve your issue? I had what sounds like a similar issue where I had a responsive SVG and tried using motion path. Really simple solution was to add an SVG circle inside the parent SVG group and the circle followed along the path no matter the size of the SVG scene.

This thread helped me - https://github.com/juliangarnier/anime/issues/126

**Comment by eiranix** [comment]
Oh ok, so I need to use an element within the SVG to follow the scaled path? Is there no way to do it to an element outside the SVG?

**Comment by eiranix** [comment]
In case anyone is wondering, I came up with a work around so I can make an element outside the svg follow a scaled path. Simply have two paths for the smallest and largest and use morph path and seek to a percentage between the paths based on the parent width. It's not ideal, but it works.

**Comment by petero-dk** [comment]
I have made a pull request #301 that makes it both responsive and viewbox aware,

**Comment by juliangarnier** [comment]
V3 now support responsive motion path !
