### ISSUE TITLE
Insert comma into numeric value strings not working

### ISSUE THREAD

**Issue by e-g-b** [juliangarnier/anime#235]
Just trying to insert commas into numeric value stings (example: 1,000) not working. 

HTML lang is set to lang="en-US"

var calcNumber = $('.data-number.data-paid input').attr('value');
calcNumber.toLocaleString('en-US');

Can't seem to inject any commas. Is it something with Anime.js not working with Number.toLocaleString('en-US')? Is there a proper way to do this with Anime.js?

**Comment by alexchantastic** [comment]
I don't think anime supports this. You'd probably be better off with creating your own number tween function which adds formatting.

**Comment by pinksharpii** [comment]
I'm late to the party but in case anyone else has the same question I did, I found a way around it, using the update function. It's probably kind of hacky but it works.

`update: function(anim) {
			  	if(anim.animatables[0].target.innerText >= 1000)
			  	{
			  		anim.animatables[0].target.innerText = parseInt(anim.animatables[0].target.innerText).toLocaleString('en');
			  	}
			  }`

**Comment by juliangarnier** [comment]
Added to the doc : https://animejs.com/documentation/#tick

**Comment by juliangarnier** [comment]
Anime.js doesn't support this kind of formatting, but you can use a custom function to foramt the value the way you want.
