### ISSUE TITLE
Percentage unit starting value miscalculated

### ISSUE THREAD

**Issue by HauntedSmores** [juliangarnier/anime#238]
When animating to a percentage value without explicitly giving the starting value, anime.js calculates the starting value incorrectly.

CodePen: https://codepen.io/HauntedSmores/pen/EwaKwR

You can comment/uncomment between the two anime definitions and see the difference. The two definitions should act the same but they do not.

Using just an end value, the starting value should be correctly taken from the CSS. This works for all other units except percentage, it seems. Using the codepen provided, if you simply change the css to `left: 10px` and in the anime definition change it to `left: 50px` it works as intended.

**Comment by juliangarnier** [comment]
Fixed in 2.2.0!

**Comment by HauntedSmores** [comment]
@juliangarnier Awesome thank you! Sorry for the duplicate if that was the case

**Comment by dasmikko** [comment]
This still seems to be an issue, even in the codepen.

**Comment by MightyRevenge** [comment]
I get this issue for `height`. Without explicitly mentioning the start height, it doesn't animate.
