### ISSUE TITLE
Binding animation to scroll event

### ISSUE THREAD

**Issue by StrangerPings** [juliangarnier/anime#239]
Are there any example of binding an animation to a scroll event?

Like http://scrollmagic.io/

**Comment by alexchantastic** [comment]
I don't think the docs contain an example for triggering an animation on scroll, but you can repurpose the [seek example](http://animejs.com/documentation/#seekAnim) to fire on a scroll event.

**Comment by Cleecanth** [comment]
As @alexchantastic said, you can just use the seek property. For ScrollMagic specifically, something like this works:

```js
// Assuming you've already set up your scroll magic controller and anime timeline
// var timeLine = anime.timeline({...});

new ScrollMagic.Scene({
  duration: timeLine.duration
}).on('progress', function(event){
  timeLine.seek(timeLine.duration * event.progress)
});
```

For a manual approach, just trigger the timeline seek on scroll.

**Comment by roeeyossef** [comment]
@Cleecanth can you be a bit more specific on how to do so? i cannot get it to work.. 

i have the following Js but get no results, i dont really know how to debug that: 

`    const animeObject = anime.timeline({
        targets: '.myTargets',
        translateX: function(el) {
            return el.getAttribute('data-x');
        },
        translateY: function(el, i) {
            return el.getAttribute('data-y');
        },
        rotate: function(el) {
            return el.getAttribute('data-r');
        },
        autoplay: false,
        duration: 3000
    });


    $(function () { // wait for document ready
        // init controller
        var controller = new ScrollMagic.Controller();

        // build scene
        new ScrollMagic.Scene({
            duration: animeObject.duration
        }).on('progress', function(event){
            animeObject.seek(animeObject.duration * event.progress)
        }).addTo(controller);
    });`
