### ISSUE TITLE
timeline waits for all animations inside to loop

### ISSUE THREAD

**Issue by rareslupascu** [juliangarnier/anime#240]
Hi

so i have a timeline that should last for 5 sec and that should loop
the animations inside have offsets so if i play my timeline ... it waits for all the animations inside to finish and then it loops again .. 

any idea on how to make this continous?

thanks

**Comment by alexchantastic** [comment]
Does `loop: true` on the `timeline` not make it loop infinitely?

**Comment by wowzaaa** [comment]
not at all :) i ended up using gsap :)

**Comment by alexchantastic** [comment]
`loop: true` works fine for me: https://codepen.io/alexchantastic/pen/YrqZyK?editors=1111

**Comment by wowzaaa** [comment]
my use case was a bit different:
http://pipple.foove.nl/

i am creating a path depending on the number of people that should be displayed and in my case the reverse functionality was behaving like a rewind .. so not looping forever

i have to be honest and say that i did not give anime the same amount of time i offered gsap so maybe i missed something :)

thanks

**Comment by alexchantastic** [comment]
Ah I see what you're saying now. You should be able to achieve the same results with anime, but I'm glad you were able to get things working with gsap.

**Comment by wowzaaa** [comment]
do not get me wrong ... it was no easier with gsap ... i tested like 9-10 different animation libs ... anime and gsap are the most powerful ... i found gsap first ... i think this was the only reason i gave gsap more time than anime ...

for who is reading this ... anime is awesome in more ways than one :)

**Comment by juliangarnier** [comment]
Hey, I improved the way looping timelines are working in 2.2.0, take a look at this animation https://codepen.io/juliangarnier/full/rGjMyW/

**Comment by gblok** [comment]
how to arrange a circular offset?
