### ISSUE TITLE
Syntax error on IE11

### ISSUE THREAD

**Issue by SndrL** [juliangarnier/anime#243]
Getting a Syntax error in IE11,
console leads me to line 23 in the non-minified script. 
`}(this, () => {`

Any ideas?

**Comment by Cleecanth** [comment]
This is an ES6 syntax. You'll need to transpile anime with something like babel to get it to work in older non-ES6 browsers.

**Comment by juliangarnier** [comment]
Or use the ES5 compiled anime.min.js file :)
