### ISSUE TITLE
Subsequent motion path animations follow incorrect path

### ISSUE THREAD

**Issue by alexchantastic** [juliangarnier/anime#245]
Calling an animation on a motion path via function more than once causes the animation to follow an incorrect or partial instance of the defined motion path. This used to work fine in `v1.1.x`.

Codepen example: https://codepen.io/alexchantastic/pen/WZxpYZ

Defining the animation outside of the function and calling it via `animation.restart()` seems to work fine though.

**Comment by juliangarnier** [comment]
Fixed in 2.2.0!

**Comment by alexchantastic** [comment]
👍  confirmed fixed!
