### ISSUE TITLE
[2.2.0] reduce size

### ISSUE THREAD

**Issue by leeoniya** [juliangarnier/anime#246]
@juliangarnier

i think you can reduce the size quite a bit by transpiling to es5 via https://buble.surge.sh/ and then running the result through Closure:

```
java -jar compiler.jar --language_in=ECMASCRIPT5_STRICT --language_out=ECMASCRIPT5 --js anime.es5.js --js_output_file anime.min.js
```

it gets rid of a bunch of the `$jscomp` stuff from the output. did not test the functionality though. this repo has no tests?

**Comment by juliangarnier** [comment]
I tried this but the code minified doesn't work.
V3 use a new compression method.
