### ISSUE TITLE
Fading Between SVG Fill Jumps to Black

### ISSUE THREAD

**Issue by alexmccabe** [juliangarnier/anime#248]
Fading between SVG fills jumps to black at the start of the loop. Looking at the values that anime is changing, it tries to set `rgba(23.457894375835,` (and tweens between numbers), before then setting the values correctly.

I'm not sure why it is doing this, but I seem to be able to replicate it more often than not.

Example: https://codepen.io/alexmccabe/pen/EwZNer

**Comment by alvarotrigo** [comment]
I guess you never managed to solve the problem and opted to go for CSS for it?
