### ISSUE TITLE
Node modules' main scripts shouldn't be minified

### ISSUE THREAD

**Issue by callumlocke** [juliangarnier/anime#249]
This package sets [`"main": "anime.min.js"`](https://github.com/juliangarnier/anime/blob/ae9eb90ab66e92f89dad8f9b59e9df3928c16991/package.json#L5). This breaks npm convention and makes debugging stack traces almost impossible. It's ok to include a minified version in the published package, but please consider changing the main script to `"main": "anime.js"`.

**Comment by alexchantastic** [comment]
I've issued a PR for this change: https://github.com/juliangarnier/anime/pull/253

**Comment by juliangarnier** [comment]
Merged in [v3.0.0 branch](https://github.com/juliangarnier/anime/tree/3.0.0).
