### ISSUE TITLE
Change the tempo/speed

### ISSUE THREAD

**Issue by JulienJo** [juliangarnier/anime#250]
Hi!
It would be nice to set up speed: sometimes you know that something is not perfect but you don't know what. If you could decrease speed (like what you can do in Chrome for CSS animations), you will easily see what's wrong. 
Moreover, sometimes, you think that your animation is a little too slow or speed. Instead of changing every parameters, a global speed/tempo variable would be a nice feature.

**Comment by alexchantastic** [comment]
Does the helper [`anime.speed`](https://github.com/juliangarnier/anime#animespeed--x) solve this issue for you?

**Comment by JulienJo** [comment]
Exactly @alexchantastic 
Thanks!
