### ISSUE TITLE
delay doesn't work

### ISSUE THREAD

**Issue by 8703303** [juliangarnier/anime#254]
i'm using anime for showing or hiding some block.
i need to change delay value related to anime direction play(reverse for hiding).
it didn't work when i change the delay value in some function later and it play with init delay value(0):
`var animePrimaryInfos = anime({
        targets: '.primaryInfos',
        translateX: [200, 0],
        opacity: [0, 1],
        autoplay: false,
        complete: function () { animePrimaryInfos.reverse(); }
    });

function hidePrimaryInfos()
{
    animePrimaryInfos.delay = 3000;
    animePrimaryInfos.play();
}
`
if i set value delay in initiation it work but later it doesn't work.

**Comment by alexchantastic** [comment]
I don't think you can override parameters of an animation that has already played. You probably just want to put the animation in a function that you can call.

**Comment by robizzt** [comment]
Delay doesn't work when direction is reverse.

**Comment by nekosaur** [comment]
> Delay doesn't work when direction is reverse.

By design, or as a known bug?

**Comment by robizzt** [comment]
I don't know. Probably by design.

**Comment by juliangarnier** [comment]
By design, reversed animation will play entirely in reverse, so the delay will be at the end.
I'm thinking about adding an `endDelay` parameter to the API. This will allow delayed animation animations in reverse.

**Comment by juliangarnier** [comment]
Added endDelay parameter in V3.

**Comment by ninofiliu** [comment]
@juliangarnier thanks for adding `endDelay`! It works perfectly.

*However* I think it would be great if the docs for neither [delay][delay], [endDelay][endDelay] nor [direction][direction] precise what you just said! How about updating the direction doc text from

```txt
Defines the direction of the animation.
```

to

```txt
Defines the direction of the animation.

By design, reversed animation will play entirely in reverse, so the `delay` will be at the end, and the `endDelay` will be at the beginning. 
```

?

[delay]: https://animejs.com/documentation/#delay
[endDelay]: https://animejs.com/documentation/#endDelay
[direction]: https://animejs.com/documentation/#direction
