### ISSUE TITLE
How to animate dash lines along a path?

### ISSUE THREAD

**Issue by naivefun** [juliangarnier/anime#258]
The dash line shall be filled along the path all the way, how should I do that?

**Comment by alexchantastic** [comment]
There is an example in the docs: http://animejs.com/documentation/#lineDrawing

**Comment by naivefun** [comment]
in case you need it:

```
var svgAttributes = anime({
    targets: '#line, #banner-svg',
    easing: 'linear',
    strokeDashoffset: (el, i) => -(100 + (i * 100)),
    duration: 1100,
    loop: true
});
```

**Comment by zebapy** [comment]
I also found this helpful so maybe others will https://www.visualcinnamon.com/2016/01/animating-dashed-line-d3
