### ISSUE TITLE
Custom Easing not working

### ISSUE THREAD

**Issue by thapliyalshivam** [juliangarnier/anime#261]
Morphing paths with custom easing is not working
while morphing paths the easing parameter works fine when given a string easing while a custom curve doesn't work. Here's the link to pen.
Please resolve this or let know if there's any wrong implementation.
https://codepen.io/thapliyalshivam/pen/XexQoG

**Comment by alexchantastic** [comment]
Your pen is using an older version of anime.js which does not support custom bezier functions. You can use `https://rawgit.com/juliangarnier/anime/master/anime.js` as the external JavaScript to include the latest verison which does support custom bezier functions.
