### ISSUE TITLE
stopping animation when elem is removed by vdom

### ISSUE THREAD

**Issue by siassaj** [juliangarnier/anime#262]
Does animejs have a strategy for this; a way to stop the animation when the elem is removed by the vdom engine allowing GC to clean up?

**Comment by juliangarnier** [comment]
I don't think I will add a way to detect if the element has been removed.
I'm not sure about the performance issue here.

if the element is removed before the animation end, you should also pause the animation or use `anime.remove()` at the same time to be sure.
