### ISSUE TITLE
[Enhancement] Add an option to the remove() method to also strip leftover inline styles

### ISSUE THREAD

**Issue by HauntedSmores** [juliangarnier/anime#264]
Looking at the source, it seems like it may be challenging to remove styles that were only added/manipulated by anime, but I still find myself not really caring about that and wanting to simply remove the element from the animation and get rid of all inline styles. More often than not the only inline styles are the ones from anime anyway.

For this reason, it might be simply a really useful option argument passed to the `remove()` method to indicate the desire to also strip all inline styles on those elements.

**Comment by juliangarnier** [comment]
`remove(targets)`will remove the targets from their animations and pause them.
If you remove inline styles, it will also reset their current state, which is not what `remove()` is supposed to do.
