### ISSUE TITLE
There's something wrong with the CSS properties 'vw'

### ISSUE THREAD

**Issue by G-Veigar** [juliangarnier/anime#265]
when i use CSS properties 'vw', For example, 
`
.mydiv {
  width: 40vw;
  height: 10vw;
}
`
then i write in vue`s mounted

`
this.animeTimeline = anime({
      targets: '.mydiv',
      borderRadius: '5vw',
      backgroundColor: '#cca4e3',
      width: '10vw',
      color: '#666',
      easing: 'easeInOutExpo',
      duration: 500,
      autoplay: false
})
`
but  i  found that '.mydiv' s  width is not '40vw' like i set frist，It's more than 40vw

**Comment by luglio7** [comment]
using the browser inspector tool will solve the dilemma.

**Comment by juliangarnier** [comment]
Should be fixed in V3.
