### ISSUE TITLE
Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by ChristopherSant** [juliangarnier/anime#270]
I've been trying to animate some personal work but im stumbling with these errors.

![image](https://user-images.githubusercontent.com/9400679/32077317-fcfc2824-ba70-11e7-9854-7b6dc77bdc22.png)

Could it be a conflict with my scripts?

**Comment by alexchantastic** [comment]
Can you post an example? Seems like the error is originating from `animations.js`.

**Comment by ChristopherSant** [comment]
Here you go

![image](https://user-images.githubusercontent.com/9400679/32079167-9eef1b90-ba77-11e7-9353-5028ab3abd35.png)

**Comment by jeffcato** [comment]
I was having this issue also - I think it is related to using css word-colors like "red" on ln27 of your example.

**Comment by alexchantastic** [comment]
@ChristopherSant, I believe @jeffcato is right. Try using a hex code instead for colors (e.g., `#FF0000`).

**Comment by ckipp01** [comment]
I'm getting this same error when trying to use it with `textDecoration: 'underline'`.

**Comment by marko-mlinarevic** [comment]
I'm getting the samer error when using `visibility: 'visible'`

**Comment by devanflaherty** [comment]
@marko-mlinarevic : Same here.

`visibility: 'visible'`

`undefined is not an object (evaluating 'd[d.length-1].end')`

**Comment by juliangarnier** [comment]
`'visible'`, `'underline'` are not valid values since they don't contain any number, and anime only accepts hex, rgb, rgba, hsl and hsla color values, no color names like `'red'`.

`visibility` can be replaced by `opacity`.
Not sure about `text-decoration`, by maybe `border-bottom`?
And of course `red` can be replaced by `#F00`.

**Comment by mudlabs** [comment]
I get it when trying to scroll a container on click!

```js
const container = document.getElementById("brands");
prev.addEventListener("click", e => {
  anime({
    targets: container,
    scrollLeft: 240,
    easing: "easeInOut",
    duration: 600
  });
});
```

But I know the above can be done, because of this [CodePen](https://codepen.io/rukiadia/pen/qYyLdw) I found.

**Comment by mudlabs** [comment]
Oh, I'm a fool. It was the `easing`. I just assumed `easeInOut` was a value, it's not.
  - [Easing](https://animejs.com/documentation/#pennerFunctions)

**Comment by sunco007** [comment]
This is very old, but I had the same issue with display:none. I solved using the begin and complete callbacks

This was the one that helps me - https://codepen.io/Shokeen/pen/XgKbKK?editors=0010

First I use the opacity, but the object is still there, so I can click the object under it. zIndex doesn't help either
