### ISSUE TITLE
Change animation target on event

### ISSUE THREAD

**Issue by dlebedynskyi** [juliangarnier/anime#274]
Is there a way to to change animation target values on even while animation is running? 

**Example**  
Lets say we do scroll
1. user scrolls down
2. animation start 
3. user scrolls  up. 

How to stop animation in its current state and change target of animation to new scroll position? 

I've tried to do 
```
anime.remove(target);
anime({
target,
...rest
})
```
but it seems only last animation is actually happening. And while user scrolls nothing is moving.

**Comment by juliangarnier** [comment]
Hey, this is not a issue related to anime.js source code, and this isn't the right place to ask for help for your animations.
Please use https://stackoverflow.com/search?q=anime.js instead.
