### ISSUE TITLE
synchronous start

### ISSUE THREAD

**Issue by AlexGalays** [juliangarnier/anime#28]
If I add a new element to the document and want to play an animation with opacity: [0, 1] it will flicker because we will see the element with opacity 1 (the default) during one frame.

Could the start of an animation be synchronous when autoplay is true ? This way the element would immediately be set to opacity = ~0

**Comment by juliangarnier** [comment]
What do you mean exactly by "synchronous"?
Since the element is created before being animated, it should be visible before the animation run.
To avoid flickering in your example, the default opacity of the element should be 0 when created, and animated to 1 with anime.

**Comment by AlexGalays** [comment]
I expected such a reply :)
synchronous = doing the very first property setting immediately, not in a RAF. But I'm fine either way, I indeed worked around it by setting opacity to 0 before starting the animation.
