### ISSUE TITLE
Since 2.2.0, unable to set empty value to css properties in animation

### ISSUE THREAD

**Issue by KevinCaro** [juliangarnier/anime#280]
For example, in this code : 
```
      anime.timeline().add({
        targets: '.targeted-class1',
        opacity: [0, 1],
        duration: 400,
        easing: 'linear'
      }).add({
        targets: '.targeted-class2',
        translateY: [50, 0],
        opacity: [0, 1],
        color: [
          {value: 'white'}, // problem here
          {value: 'rgb(128, 128, 0)},
          {value: ''}, // and here
        ],
        elasticity: 700,
        duration: 1000,
        offset: 200,
        delay: function (el, i) {
          return i * 100;
        }
      });
    }
```

Before 2.2.0, the color value could be 'cleared'/removed from the inline styles of the affected elements if given an empty string. Also, you could use color names as their values ('white'). In this code, the end value for color is rgb(128, 128, 0) (the last 'valid' value I guess).

To be honest, I can't seem to find if this behavior change is a bug or not since I couldn't find this information in the documentation (I could understand these changes aren't bugs, though having it work that way could be useful in my opinion).

It seems that this behavior changed for other attributes too (problem is there too with opacity, didn't test on other attributes though). 

By the way, great job on this library! It's very well made on many aspects (great ease of use, features and docs), and to me, is very enjoyable to work with!

**Comment by alexchantastic** [comment]
I can't speak to earlier versions, but the docs [mention](https://github.com/juliangarnier/anime#property-values) that colors should specifically use hex, rgb, or hsl values.

As for clearing the style value with an empty value (`''`)... I'm not sure if that is valid behavior either. If you want to do that, you can write a function to remove the value with a `complete` [callback](https://github.com/juliangarnier/anime#callbacks). Or, you can use a [function based parameter](https://github.com/juliangarnier/anime#function-based-property-parameters) and set it to use the original value as the last value.

**Comment by juliangarnier** [comment]
@alexchantastic is right, color names never were supported, and clearing inline styles using an empty value is not supposed to work also.

Using a callback function to clear inline styles sounds like the best way of doping that.
But just by curiosity, why are you clearing the inline styles?
Thanks!

**Comment by KevinCaro** [comment]
@alexchantastic using a callback function sounds good to me, will try that, thank you!

@juliangarnier so that the color from my element's class would take over after the animation is over. I have a list of elements having an active or disabled class, which have their own colors.

Thank you for your answers guys!
