### ISSUE TITLE
Non-UMD version

### ISSUE THREAD

**Issue by lukasoppermann** [juliangarnier/anime#285]
Hey @juliangarnier,

maybe the issue #134 with the es6 modules could be lessened if you provide a version without the UMD. When trying to import the current I get the error: `The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten`. 

However you could probably add the UMD in the build-step and thus have a source version without it (which people like me could than use to import into es6 files/using es6 import statements).

What do you think?

**Comment by juliangarnier** [comment]
Merged in [v3.0.0 branch](https://github.com/juliangarnier/anime/tree/3.0.0).
