### ISSUE TITLE
SVG Motion Path Help

### ISSUE THREAD

**Issue by drnhzn** [juliangarnier/anime#290]
I can't seem to animate an svg object directly to the path I made but when I use a div box it works. Thanks! 

https://codepen.io/drnhzn/pen/YEOjRZ

**Comment by Dan9boi** [comment]
+1 i have a similar issue, with a path element i a svg. Is the issues something with the transform-origin?

**Comment by drnhzn** [comment]
Tried using transform-origin on the svg pen. It also is not working.

**Comment by Loque-** [comment]
The same as this? https://github.com/juliangarnier/anime/issues/126

**Comment by drnhzn** [comment]
Yup. Tried transform-origin property already still not working.

**Comment by juliangarnier** [comment]
For questions related to animation problem or help regarding animation techniques, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
