### ISSUE TITLE
stroke animation Help: Starts at wrong Direction

### ISSUE THREAD

**Issue by thapliyalshivam** [juliangarnier/anime#294]
https://codepen.io/thapliyalshivam/pen/pdQaeg

I am trying to animate merry to draw from M to Y. It starts with Y to m which isn't what I am trying to do. I trying offset but because of Bounce thing, it doesn't look good as a few part of the stroke still is visible at the ends. Is there any value flag?

**Comment by jeroenrinzema** [comment]
The SVG path of merry is exported in the [wrong direction](https://codepen.io/jeroenrinzema/pen/gXqJvK). You can easily change the direction of your SVG path by installing [this script in Illustrator](https://forums.adobe.com/message/6714293#6714293). If you want to change the easing of the animation please check out the [documentation](http://animejs.com/documentation/#penner).

**Comment by juliangarnier** [comment]
For questions related to animation problem or help regarding animation techniques, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
