### ISSUE TITLE
Some problems when using 

### ISSUE THREAD

**Issue by geyingauv** [juliangarnier/anime#295]
I want do something like this, given a list of item ,when I foucs on it , it will change some properties, when I leave , It will reset ,
There is some code I have tried
https://codepen.io/geyingauv/pen/eeXpyR

If anyOne can help me, thank you !

**Comment by alexchantastic** [comment]
You probably need to pause or stop the current animation before the next one fires. Anime doesn't include any kind of state/queue management so you will need to manage that yourself.

For simple animations like in your example, you may want to use simple [CSS transitions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions) instead.

**Comment by geyingauv** [comment]
@alexchantastic okay I know your means , I will try to solve it 
I want make a complete effect, It's just a simple example ,I am not sure css transitions can make it , but I will try , thanks a lot !

**Comment by Loque-** [comment]
Here you go; https://codepen.io/loque_k/pen/YYXqRv

I googled `hover effects with anime` and then used [this result](https://codepen.io/juliangarnier/pen/aWERWX) as a reference

**Comment by geyingauv** [comment]
@Loque-  
Thanks very much,
It's a good way to do the effect,I don't know the code can write by this way before.
I am a new guy in international community,
Honestly,I don't know how to get the result i want,may be they's words so profession,
so i find the library ,all people used this library here,may be someone has met this problem.
Fortunately, i can read some code  XD. I will take your suggestion ,try to ask in StackOverflow first

Forgive my bad English,thanks again!
