### ISSUE TITLE
Single DOM node passed as variable to callback doesn't animate. Array does.

### ISSUE THREAD

**Issue by jamespatrikrichards** [juliangarnier/anime#296]
Hope this isn't me being stupid, but it feels like a bug. Please forgive any obtuse code - still a relative noob.

Using animejs to simply animate a nav menu. On a simple list of a items, the clicked one is set to grow and the others to shrink following the animation. I'm set up to pass the `navActive` and `navInactive` variables to the final animation callback, but the `navActive` target (a single DOM node) doesn't animate. The array of `navInactive` items does. It all works fine if I use a selector in the `targets` argument. Docs seem to suggest it should work both ways, so opening an issue. Regardless, animejs is absolutely amazing.

```
// Grow / shrink selected nav item
$('.nav-item').on('click', 'a', function() {
  // Prevent uncontrollably following link
  event.preventDefault();
  var navItem = $(this);
  navClick(navItem, animateNav);
});

function navClick(navItem, callback) {
  // Add class to identify the selected link
  navItem.addClass('active');
  callback(runNavAnimation);
}

// Callback to run the animation after setting the a.active class
function animateNav(_runNavAnimation) {
  // Get active & inactive nav-items
  var navInactive = $('.nav-item a').not('.active').toArray();
  var navActive = $('.nav-item a.active');
 
  // Get the href of the selected link
  var href = navActive.attr('href');

  // Run callback
  _runNavAnimation(navActive, navInactive, href);
}

// Callback to define and run the menu animation
function runNavAnimation(_navActive, _navInactive, _href) {
  // Grow / shrink animations
  var navSelect = anime.timeline();
  navSelect.add({
    targets: 'a.active',              // this works
    targets: _navActive,              // this doesn't
    fontSize: ['4vw','5vw'],
    ease: 'linear',
    duration: 1000,
    complete: function() {
      window.location = _href;
    }
  }).add({
    targets: _navInactive,
    fontSize: ['4vw','3vw'],
    ease: 'linear',
    duration: 1000,
    offset: '-=1000'
  });
  navSelect.restart;
}
```

**Comment by alexchantastic** [comment]
I believe it's because you are passing a jQuery object (assuming that is the library you are using). To pass the node itself, you can reference `navActive[0]` instead of `navActive` on line 25.

**Comment by jamespatrikrichards** [comment]
@alexchantastic somehow missed that comment, and just encountered the same thing. You're spot on - thanks.
