### ISSUE TITLE
SVG animation not working in IE and Edge

### ISSUE THREAD

**Issue by manoj1991** [juliangarnier/anime#297]
I've created a path animation using Animejs, it works fine in Chrome and other browsers but when it comes to Internet Explorer and Edge it doesn't work. Could you please help me out with this issue?
here's my pen
https://codepen.io/manoj1991/pen/RjdXjN

**Comment by manoj1991** [comment]
@juliangarnier does anime support SVG line animation on Internet Explorer and MS Edge?

**Comment by juliangarnier** [comment]
You are using an out of date version of anime.js, please upgrade to V3 and try again.
Thanks

**Comment by manoj1991** [comment]
Thank you @juliangarnier
