### ISSUE TITLE
animateplus comparison

### ISSUE THREAD

**Issue by jimblue** [juliangarnier/anime#299]
Hi there,

I'm using `anime.js` for all my website for some time and I've just discovered [animateplus](https://github.com/bendc/animateplus).

This library weight less than 10ko and seems to have the same features and performance as `anime.js`.

I was wondering if some of you did some comparaisons tests?

@juliangarnier I guess you already know this library, what do you think about it?

Cheers

**Comment by juliangarnier** [comment]
Actually the first animateplus version has been a great inspiration for animejs API.
But I think animejs has few more features is more flexible.

**Comment by jimblue** [comment]
ok tks for your answer and congrat for the V3, it looks awesome 💯
