### ISSUE TITLE
getComputedStyle can return null on Firefox when called within iframe

### ISSUE THREAD

**Issue by gcadeado** [juliangarnier/anime#300]
As stated in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=548397)

On Firefox, getComputedStyle(el) returns null if the script is loaded in an iframe with `display: none`

I've tried some workarounds (like this one https://github.com/marcj/css-element-queries/issues/148) with no success. Any ideas?

**Comment by juliangarnier** [comment]
You can use `[from, to]` values instead of relying on `getComputedStyle(el)` for the "from" value.
