### ISSUE TITLE
Reverse Direction 

### ISSUE THREAD

**Issue by sdefrancesco** [juliangarnier/anime#302]
Hi I am using anime.js to animate a modal. I am using the direction: 'reverse' in order to animate the element to its original position. For some reason the element starts off at its original position and than the animation happens. I need for the element to start off where the animation is happening from. Can somebody tell me what I am missing?

```
function activatePreview() {
    var bgModal = document.createElement('div')
    var innerModal = document.createElement('div')
    bg.classList.add('custom-modal-container')
    document.body.appendChild(bg)
    var selector = anime({
        targets: '.custom-modal-container',
        translateY: 1000,
        direction: 'reverse',
        easing: 'easeInQuart',
        opacity: 0,
        duration: 500,
        height: 20,
        complete: function() {
            thing.classList.add('preview-inner')
            bg.appendChild(thing)
            var inner = anime({
                targets: '.preview-inner',
                translateY: 200,
                direction: 'reverse',
                easing: 'easeInQuart',
                height: 300,
                opacity: 0,   
            })
        }
    })
}
```

**Comment by alexchantastic** [comment]
You probably want to use the [playback controls](https://github.com/juliangarnier/anime#playback-controls) for this instead. There is a `reverse()` method that looks like it will fit your use case.
