### ISSUE TITLE
Timeline animations reset transform once over

### ISSUE THREAD

**Issue by scarlac** [juliangarnier/anime#303]
If first step in a timeline has `duration: 0`, then animation will revert the `transform` once timeline is over.

### How to reproduce:
1. Go to: http://animejs.com/documentation/#relativeOffset
2. Open web inspector and inspect an object
3. Run the code in the console:

```
anime
  .timeline({ duration: 1000, targets: $0 })
  .add({ duration: 0, translateX: 0, zIndex: 10 }) // set a starting point
  .add({translateX: 100, zIndex: 5})
  .add({zIndex: 20});
```

I would expect it to bounce to the right and stay there, and it does indeed bounce but instead of staying, it resets the transform to original position (ie. `translateX: 0`). Seems zIndex stays fine. So resulting style is: `z-index: 20; transform: translateX(0px);`.

The workaround is to change `duration: 0` to `duration: 1` which also immedately fixes the issue.

**Comment by andreas-vvv** [comment]
Instead of adding an initial timeline entry you should use initial values in the corresponding entry:
```
.add({
    targets: '.row:nth-child(1)',
    translateY: -50,
    opacity: [0, 1], // initial value is 0
    easing: 'easeOutExpo',
    offset: 0,
    duration: 3000
})
```
This also avoids the short flicker when using `duration: 1`

**Comment by juliangarnier** [comment]
Should be fixed in V3 !
