### ISSUE TITLE
Individual begin and complete event in group of elements

### ISSUE THREAD

**Issue by iShankarG** [juliangarnier/anime#304]
```
var cuber = {
	targets: '#cuber .cube',
	translateY: 300,
	delay: function(el, i, l){
		return i * 500;
	},
	begin: function(anim) {
		console.log('begin');
	}
};
```

the count of target elements will be 15, i would like to track individual elements begin and complete events.

**Comment by juliangarnier** [comment]
Not possible since callbacks are specific to one instance.
But wrap the anime instance in a function with one argument for your element and call the function 15 times using a loop.
