### ISSUE TITLE
Question: Disable easing functions?

### ISSUE THREAD

**Issue by ninja542** [juliangarnier/anime#306]
Hello! I'm animating something for a physics simulation, and I would like to animate something translating in the X direction. I would like to disable easing and just have the train move from point A to B at a constant velocity.

I know that it is possible to do a css animation, but I would like to use the timeline feature of anime.js

Thank you!

**Comment by alexchantastic** [comment]
Not sure if I understand exactly what you're asking, but there are a few built in [easing functions](https://github.com/juliangarnier/anime#easing-functions) you can use. Perhaps try `linear` if you are looking for something constant.

**Comment by ninja542** [comment]
I think linear easing works, that's what I put in my code. I guess I somehow thought that it still had easing. Thank you for the response!
