### ISSUE TITLE
Is it possible to change animatable properties during animation

### ISSUE THREAD

**Issue by stenvdb** [juliangarnier/anime#307]
For example the x and y values? Can they be changed during the animation?

**Comment by alexchantastic** [comment]
I think you would need to instantiate a new animation with the new properties.

Can you give an example of what you're trying to do?

**Comment by Stenvdb** [comment]
When the properties you need to animate to, change during the animation. 
For example we have a page that automatically scrolls to the bottom of the page when a new element (dynamically) appears. It’s possible that a new element appears during the scroll animation, which means that the position to scroll to changes during the animation

When starting a new animation with the new end value, you’d expect it to kill the previous animation.

I would like the movement to continue, so the end value change is seamless.

**Comment by juliangarnier** [comment]
No it's not possible, you have to stop the animation and create a new one.
