### ISSUE TITLE
Question: Undefined / null in targets array

### ISSUE THREAD

**Issue by mimamuh** [juliangarnier/anime#308]
Hi,

right now, when my targets option is undefined or null, it simply ignores the animation.

```js
const timeline = anime
        .timeline()
        .add({
            targets: null, // <--- ignores my animation as target us null/undefined
            translateY: ['-160px', 0],
        });
```

But when I pass an array with an undefined / null value, it throws an error:
```js
const timeline = anime
        .timeline()
        .add({
            targets: [null], // <--- Throws an error "Uncaught TypeError: Cannot read property 'nodeType' of null"
            translateY: ['-160px', 0],
        });
```

Shouldn't it be consistent and ignore the animation for this `entry` also?? Or is it on purpose to throw an error then?

Thx for this greate lib.

**Comment by juliangarnier** [comment]
Why are you using `targets: null / [null]`?
