### ISSUE TITLE
use Transalte3d Hack

### ISSUE THREAD

**Issue by UYEONG** [juliangarnier/anime#31]
This project has been using will-change property for GPU Optimization.
But many browsers doesn't support it.
So, why don't you provide translate3d hack workaround?
If you don't like that tricky way, it could be offered an option. like this.

```
anime({
    useTranslate3d: true
});
```

**Comment by lukebatchelor** [comment]
For reference, only IE and Edge don't support it.
http://caniuse.com/#search=will-change

**Comment by UYEONG** [comment]
Yes. but also older version mobile browsers don't support it.
Does this project determined to doesn't mind older versions?

**Comment by juliangarnier** [comment]
No, and it's a lot of code to add to the library for little benefits.
Especially when it can be added manually with one line of CSS, or adding a translateZ: 0 to you animation.
