### ISSUE TITLE
Help: Animating props in Vue

### ISSUE THREAD

**Issue by dpschen** [juliangarnier/anime#310]
Hello,
I built a simple counter component with anime and vue js: https://jsfiddle.net/3m6t4nvg/

I'm unsure about animating props of vue.js with anime.
As you can see in the fiddle I used the whole component as target (`this`).
After this i select the value I want to animate with: `renderedValue: newCounterValue,`
Now I'm unsure because like this the danger of collision is super high right?

I don't get why I need an array or object to animate when I just want to animate a number.
What would be the right way to animate props in Vue with animejs?

**Comment by juliangarnier** [comment]
Simply pass the object containing the value you want to animate in the targets parameter : https://animejs.com/documentation/#JSobjProp

**Comment by dpschen** [comment]
If somebody has problems with this just pass `this.$data` (https://vuejs.org/v2/api/#vm-data).

I got that inspiration from that slide: https://fritz.netlify.com/slides/viz-in-vue/37
