### ISSUE TITLE
round property does not accept negative powers of 10

### ISSUE THREAD

**Issue by Loreno10** [juliangarnier/anime#311]
Hello,
I want to animate a numerical text displayed on the screen. The text I want to animate is a decimal (for example 4.52). Problem is that unless I specify the 'round' property, during animation my value becomes for example 3.2323244343 during animation until it finally becomes 4.52.
So i thought I could add: round: 0.01, so that during animation my value always had 2 decimal places. Unfortunately the result is that instead of 4.52 I get 100 (all the time, it's not even animated). 
Documentation says that round property accepts powers of 10. It seems that it accepts only positive powers.

**Comment by sszczep** [comment]
Hi, I know it's a bit late but i encountered the same problem. Maybe the solution will be useful for others. That's the line responsible for rounding:
`value = Math.round(value * round) / round;`

If you want to round to the second decimal place, round property must have a value of 100 (eg. 1,126 becomes 1,13). Negative number doesn't change anything, first you multiply by minus and then divide by it, so the result is still positive. Hope it helps. 

I think it can be closed now
