### ISSUE TITLE
Morphing animation issue

### ISSUE THREAD

**Issue by thapliyalshivam** [juliangarnier/anime#312]
Hey, A few days back, I tried morphing a a letter svg to another. It was "w" to "r". It didn't work well as it distorted the shapes after morphing. Do I need to have equal number of anchor point in both the target and the starting shape svg? It was clearly not a syntax error. Looking forward to hearing back from you. Please let me know if there are any supporting cases or examples.

**Comment by koder12** [comment]
Yes, you need to have same no. of anchor points in both the target and the starting shape SVG.

Here's an example: [https://codepen.io/anon/pen/OzaKwK](url)

So, try to create SVG's of letters 'W' and 'R' with same no. of anchor points.
