### ISSUE TITLE
using .add() to timeline to add to the end of an animation without resetting the entire timeline.

### ISSUE THREAD

**Issue by TomS-** [juliangarnier/anime#314]
I've got blocks that fade in, I want to be able to stagger the fade in as this happens when in viewport (so two blocks don't fade in at the exact same time).

I currently have a timeline, and each time a new object comes into viewport it uses .add() to add the animation to the timeline. The only issue is, each time a new object is added the timeline gets refreshed.

How would I achieve this? I've tried seeking to the end of timeline before the new .add is called however, it still resets.

**Comment by TomS-** [comment]
Resolved this by counting the animating objects and setting a delay based on that. 

When an animation starts I use animating++; and on complete I use animating--; and use delay based on that return animating * 300;

Seems to work well.

**Comment by juliangarnier** [comment]
Should be improved in V3.
