### ISSUE TITLE
scale as attribute instead of transform

### ISSUE THREAD

**Issue by jbach** [juliangarnier/anime#316]
Hey,
I want to animate the [`scale`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/scale)-attribute of [`<feDisplacementMap>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDisplacementMap) within SVG.
How can I force anime to animate as attribute rather than transform, as `scale` is listen in `validTransforms `?

**Comment by juliangarnier** [comment]
Will look into this for v3.

**Comment by juliangarnier** [comment]
Should be fixed in V3.
