### ISSUE TITLE
Stop some elements in timeline while letting others go

### ISSUE THREAD

**Issue by Kelsch** [juliangarnier/anime#318]
I am pulling data through, in the form of circles, and having the circles follow a path. However, I need some of the circles to stop at certain locations along the path, based on parameters that I have set. But I can't seem to figure out how to stop them with out stopping the entire timeline.

**Comment by Kelsch** [comment]
I changed my code to have multiple timelines in order to pause one and have others continue, but I cannot seem to stop one without stopping all of them.

**Comment by juliangarnier** [comment]
Hey, this will be addressed in 3.0.

But note that you don't always need to create timeline, did you try with simple anime instances?

**Comment by Kelsch** [comment]
I did try to use just an anime instance, but I couldn't get it to pause. But I was able to find the issue, I was creating a new instance of a timeline every single time I pulled data through, simple mistake with a pretty simple solution. Thank you for your response.
