### ISSUE TITLE
Is there a way to instantly move back after animation complete?

### ISSUE THREAD

**Issue by FateRiddle** [juliangarnier/anime#320]
I use it with React, and find it funny that when I animate one `<div>`, then rerender the whole thing, another `div` moved.

One easy solution will be reset the animation and the end, don't keep the change of the animation. How do I do it?

**Comment by juliangarnier** [comment]
How are you targeting your `div`?
Because if you use something like

```
anime({
  targets: 'div',
  ...
});
```

it will simply animate all the divs on the page, you have to use a more specific selector if you only want one div to animate.
