### ISSUE TITLE
Can't change backgroudImage property

### ISSUE THREAD

**Issue by LucasZheng** [juliangarnier/anime#322]
How to change backgroudImage property like backgroundColor?  I did this as below but it doesn't work:

`import person1 from '../assets/images/c6-person-1.png';`
`import person2 from '../assets/images/c6-person-2.png';`

    backgroundImage: [
          { value: `url(${person1})` },
          { value: `url(${person2})` },
          { value: `url(${person3})` },
          { value: `url(${person4})` },
    ],

**Comment by juliangarnier** [comment]
This is not the right place to ask for help for your animations.
-> https://stackoverflow.com/

Images are not valid animation values...

You should try to animate the background position instead.

https://github.com/juliangarnier/anime/issues/172
