### ISSUE TITLE
Seek will invalid after blur from the page

### ISSUE THREAD

**Issue by linhuiw** [juliangarnier/anime#324]
Like this demo [codepen](https://codepen.io/juliangarnier/pen/ZOkmzr)

when start the page , the seek works well.
![image](https://user-images.githubusercontent.com/722603/35606628-2387fe80-068b-11e8-9756-8d1d3135fd40.png)

But when i change the tab, and change the tab back, the box is overlaped.
![image](https://user-images.githubusercontent.com/722603/35606647-3d820272-068b-11e8-9412-4e3fc6d0f052.png)

I don't have any mind to solve this

**Comment by juliangarnier** [comment]
will be fixed in v3.0

**Comment by juliangarnier** [comment]
Should be fixed in V3.
