### ISSUE TITLE
Problem with strokeDasharray

### ISSUE THREAD

**Issue by mrKorg** [juliangarnier/anime#325]
Hi. I have some code:

`<svg version="1.1"
  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="545.6px" height="545.6px" viewBox="0 0 545.6 545.6" style="enable-background:new 0 0 545.6 545.6;" xml:space="preserve">
  <circle class="circle" fill="none" stroke='white' stroke-miterlimit="10" stroke-dasharray="3%, 3%" cx="272.8" cy="272.8" r="272.3"/>
 </svg>`

and

`anime({
                        targets: '.circle',
                        strokeDasharray: [
                            {value: '3%, 3%'},
                            {value: '10%, 20%'},
                            {value: '3%, 3%'},
                        ],
                        elasticity: 1000,
                        easing: 'easeOutQuad',
                        duration: 1000,
                    });`

But in browser I see next after finish animation:
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="545.6px" height="545.6px" viewBox="0 0 545.6 545.6" xml:space="preserve"><circle fill="none" stroke="white" stroke-miterlimit="10" stroke-dasharray="3%, 3%" cx="272.8" cy="272.8" r="272.3" class="circle" style="stroke-dasharray: 3%, 3;"></circle></svg>`

Where ` style="stroke-dasharray: 3%, 3;"` - second value without "%". 
Why it is happened?
How I can fix it? I need only %.

**Comment by juliangarnier** [comment]
This is not the right place to ask for help with your animations code.
-> https://stackoverflow.com/

(`value: '3%, 3%'` => `value: ['3%, 3%']`)

**Comment by mrKorg** [comment]
Sorry, I thought this is a bug)
`{value: ['3%', '3%']},
{value: ['10%', '15%']},
{value: ['3%', '3%']},`
