### ISSUE TITLE
Animate 1 transform from a multi-transform CSS statement

### ISSUE THREAD

**Issue by bryanberger** [juliangarnier/anime#326]
I'm trying to make a circular preloader animation such as:
![loader-contract-expand](https://user-images.githubusercontent.com/940022/35634567-012613ba-067a-11e8-8506-3e6986a41ac2.gif)

Each element I want to animate has multiple transforms applied to align it to the curve of the circle via a SCSS mixin.

eg: a loop 
```
&:nth-of-type(#{$i}) {
    transform: 
    rotate($rot * 1deg) 
    translate($circle-size / 2) 
    rotate($rot * -1deg);
}
```

which produces something like:
```
:nth-of-type(3) {
    transform: rotate(90deg) translate(16px) rotate(-90deg);
}
```

How would I affect only the `translate(16px)` to set it to 0 (so it collapses to the center as shown in the gif), but keep the `rotate` statements intact?

Something like this:
```
var circles = anime ({
  targets: ['.circle'],
  easing: 'linear',
  duration: 1000,
  translateX: 0,
  translateY: 0
});
```
Doesn't work, as it blows away all transforms. What are some approaches to this type of animation?

**Comment by gaou-piou** [comment]
Here is an approach
https://codepen.io/gaougalos/pen/xYGMdj

**Comment by juliangarnier** [comment]
I know i'm super late to this, but @gaou-piou approach is good.

But since it's not directly related to a bug in the library, please consider using [stackoverflow](https://stackoverflow.com/) instead in the future.

Thanks!
