### ISSUE TITLE
Flickering and sizing issues when animating with VH values

### ISSUE THREAD

**Issue by Soundwubz** [juliangarnier/anime#328]
When using vh values in an animation, instead of animating from 20vh to 0vh, the div goes to 40-60vh and then back to 0.

`var dropDownClose = anime({ targets: ['.mydiv'], height: '0vh', easing: 'easeOutExpo', duration: 1000              });`

I tried setting the div to have `.mydiv{ max-height: 25vh }` but it flickers and lags really bad. I ended up using px instead and that works perfectly, but I don't know if this problem with vh is an established issue or if it's just me.

**Comment by juliangarnier** [comment]
Should be fixed in V3.
