### ISSUE TITLE
Error with remove() and transform against a larger range of targets

### ISSUE THREAD

**Issue by demipixel** [juliangarnier/anime#330]
Try the following:

```js
anime({
  targets: 'a',
  scale: 2.0,
  duration: 1000
});

setTimeout(() => anime.remove($('a')[0]), 100);
```

The goal here is to scale all `a` elements to size 2, but then remove the animation from the first element. While the animation seems to get removed, we get an error in console from attempting to animate the transforms.

Small, but it could cause other issues.

**Comment by juliangarnier** [comment]
This should be improved in V3.
