### ISSUE TITLE
Problems animating percentages and other relative css units

### ISSUE THREAD

**Issue by NotARobit** [juliangarnier/anime#331]
Example: https://codepen.io/notarobit/pen/gvLeOv

The cause is that getInitialTargetValue() uses getComputedStyle(). [getComputedStyle() converts all values to px](https://developer.mozilla.org/en-US/docs/Web/CSS/resolved_value). Thus, the target will try to animate from 250px to 100%.

**Comment by NotARobit** [comment]
I've looked into possible solutions using the fact that getComputedStyle will give you the percentage value if you hide the element or its parent. https://codepen.io/notarobit/pen/PQpmaG

I could see it as a possible solution except in cases where it would break pseudo classes like :first-child. Maybe we could get around that using some kind of shadow dom.

**Comment by juliangarnier** [comment]
[[from, to] values](http://animejs.com/documentation/#specificInitialValue) can fix this kind of problem.
But since this is a recurrent issue, I'll implement a basic unit converter system for CSS and transforms in v3.0 that will cover most of the basic conversion, like the one in your example.

**Comment by juliangarnier** [comment]
Should be improved in V3!
