### ISSUE TITLE
Animation stops playing when browser tab is changed

### ISSUE THREAD

**Issue by supermandrew** [juliangarnier/anime#335]
I'm sure this is intentional in order to keep anime running smoothly/efficiently, but is there any way we could add some sort of flag/setting to a timeline that it should continue to run even if the browser tab changes?

I've noticed that if an animation is in progress, it will continue when the browser tab changes.  However, new animations (the next animation in the timeline) will not start, and the "begin" or "complete" functions will not be called until the tab regains focus.

**Comment by Splode** [comment]
This is a limitation of the `requestAnimationFrame()` implementation in most browsers: 

> requestAnimationFrame() calls are paused in most browsers when running in background tabs or hidden <iframe>s in order to improve performance and battery life.
[MDN window.requestAnimationFrame()](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)

I'm not sure that it would be possible for Anime.js to override this. However, it might be useful to detect if the current tab has focus by using the `window.onfocus` and `window.onblur` events.

- [MDN window.focus](https://developer.mozilla.org/en-US/docs/Web/API/Window/focus)
- [MDN window.onblur](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onblur)

**Comment by juliangarnier** [comment]
Yep, animations are stopped when the tab or window is inactive.
