### ISSUE TITLE
Remove an entire timeline?

### ISSUE THREAD

**Issue by delaneyj** [juliangarnier/anime#338]
In a situation where I need to stop and rebuild a timeline.  
```
if(this.timeline){
    anime.remove(this.timeline)
  }
```
Gives odd behavior.  Is there a better way to handle this?

**Comment by juliangarnier** [comment]
`anime.remove()` helps removing all or specific targets from a running animation.

In v3.0 (coming real soon) you will be able to use `anime.remove()` on timeline targets.

Did you try `myTL.pause()`?

**Comment by juliangarnier** [comment]
Should be fixed in V3.
