### ISSUE TITLE
Unable to create svg <path> of my file.

### ISSUE THREAD

**Issue by Syedwaheed** [juliangarnier/anime#339]
hi, Great feature i really want to use my web-application heading page with this just like anime with fill option. I have created file in illustrater but i m unable to see `<path/>` attribute in it. Below is my .svg file:
[https://pastebin.com/FXBtpcT2](url)
Please paste above link in browers. Clicking on it having issues.
Can anyone help me out with this how to change it with path values? Thanks in advance.

**Comment by Syedwaheed** [comment]
I m creating Svg path in illustrater but it isn't working as line drawing. My svg file is below:
`<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 400 150" style="enable-background:new 0 0 400 150;" xml:space="preserve">
<g class="lines">
	<path id="XMLID_3_" d="M36,14.5h1.3v8.4h4.4v1H36V14.5z"/>
	<path id="XMLID_5_" d="M43.9,14.5v5.6c0,2.1,1,3,2.4,3c1.5,0,2.5-0.9,2.5-3v-5.6h1.3V20c0,2.9-1.7,4.1-3.9,4.1
		c-2.1,0-3.7-1.1-3.7-4v-5.5H43.9z"/>
	<path id="XMLID_7_" d="M52.4,23.9v-9.4h1.4l3.3,4.8c0.8,1.1,1.3,2.1,1.8,3.1l0,0c-0.1-1.3-0.2-2.4-0.2-3.9v-3.9h1.2v9.4h-1.3
		l-3.2-4.8c-0.7-1-1.4-2.1-1.9-3.1l0,0c0.1,1.2,0.1,2.3,0.1,3.9v4H52.4z"/>
	<path id="XMLID_9_" d="M64,21l-1.1,3h-1.4l3.5-9.4h1.6l3.5,9.4h-1.4l-1.1-3H64z M67.4,20l-1-2.7c-0.2-0.6-0.4-1.2-0.5-1.7h0
		c-0.2,0.6-0.3,1.1-0.5,1.7l-1,2.7H67.4z"/>
	<path id="XMLID_12_" d="M74.7,19.7v0.9h-3.7v-0.9H74.7z"/>
	<path id="XMLID_14_" d="M76.3,23.9v-9.4h1.4l3.3,4.8c0.8,1.1,1.3,2.1,1.8,3.1l0,0c-0.1-1.3-0.2-2.4-0.2-3.9v-3.9h1.2v9.4h-1.3
		l-3.2-4.8c-0.7-1-1.4-2.1-1.9-3.1l0,0c0.1,1.2,0.1,2.3,0.1,3.9v4H76.3z"/>
	<path id="XMLID_16_" d="M94,23.5c-0.6,0.2-1.8,0.5-3.1,0.5c-1.5,0-2.8-0.4-3.8-1.2c-0.9-0.8-1.4-2-1.4-3.5c0-2.8,2.1-4.9,5.5-4.9
		c1.2,0,2.1,0.2,2.5,0.4l-0.3,1c-0.5-0.2-1.2-0.4-2.3-0.4c-2.5,0-4.1,1.4-4.1,3.8c0,2.4,1.6,3.8,3.9,3.8c0.9,0,1.5-0.1,1.8-0.3V20
		h-2.1v-1H94V23.5z"/>
</g>
<g id="XMLID_2_">
</g>
<g id="XMLID_18_">
</g>
<g id="XMLID_19_">
</g>
<g id="XMLID_20_">
</g>
<g id="XMLID_21_">
</g>
<g id="XMLID_22_">
</g>
</svg>`
And my line drawing javascript is below:
 var lineDrawing = anime({
  targets: '#lineDrawing .lines path',
  strokeDashoffset: [anime.setDashoffset, 0],
  easing: 'easeInOutSine',
  duration: 1500,
  delay: function(el, i) { return i * 250 },
  direction: 'alternate',
  loop: true
});

**Comment by alexchantastic** [comment]
I think you might be misunderstanding how SVG line drawing works. Here's a good article to get familiar with the concept: https://css-tricks.com/svg-line-animation-works/.

**Comment by juliangarnier** [comment]
For questions related to animation problem or help regarding animation techniques, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
