### ISSUE TITLE
React Integration

### ISSUE THREAD

**Issue by sandysaders** [juliangarnier/anime#34]
What would be the best strategy to integrate anime, into [react](http://github.com/facebook/react)? I really want to use anime however I'm not sure about what the best strategy to do this. Any feedback would be helpful.

**Comment by rohan-deshpande** [comment]
You can easily integrate it with React by using refs and something like `ReactDOM.findDOMNode(this.refs.animeTarget)`. Anime's `targets` prop takes DOM elements and that's exactly what you pass it if you get the target via `findDOMNode`

**Comment by kennetpostigo** [comment]
Couldn't you also make anime a component? And just wrap the components you want to animate?

**Comment by juliangarnier** [comment]
I'm not familiar with React and the virtual dom, but like @rohan-deshpande said, as long as you're using a valid DOM element as a target, it should work.

**Comment by muratgozel** [comment]
This may be helpful. It is a demonstration of button hover effect. 
```javascript
import anime from 'animejs'
...
const JoinWaitlistButton = ({ href, title }) => {
  return(
    <div>
      <a
        href={ href }
        onMouseOver={e => {
          anime({
            targets: e.currentTarget,
            backgroundPositionX: '10px',
            scale: {
              value: 1.05,
              delay: 300,
              duration: 500
            }
          })
        }}
        onMouseOut={e => {
          anime({
            targets: e.currentTarget,
            backgroundPositionX: '0px',
            scale: {
              value: 1,
              delay: 300,
              duration: 500
            }
          })
        }}>
        { title }
      </a>
    </div>
  )
}
```

**Comment by adrianmcli** [comment]
Given that React is becoming such a dominant player in frontend web development, I suggest that @muratgozel's example be put on the README somewhere.

**Comment by kennetpostigo** [comment]
@adrianmcli @muratgozel check out [react-anime](http://github.com/hyperfuse/react-anime)

**Comment by adrianmcli** [comment]
@kennetpostigo awesome! thanks for the link. Maybe there should be a link to it on the README then.

**Comment by jduhls** [comment]
An example of updating a javascript object in state inside a class component instead of directly altering the DOM element ref:

```javascript
const style = this.state.style

animejs({
  targets: style,
  scale: 1.005,
  boxShadow: 8,
  update: a => this.setState({ style })
})
```

**Comment by fcor** [comment]
An example of anime.js in react without any other libraries:

`import React, { Component } from 'react'
import anime from 'animejs'

class Killpop extends Component {
  componentDidMount(){
    anime({
  targets: '.anim',
  translateX: [
    { value: 100, duration: 1200 },
    { value: 0, duration: 800 }
  ],
  rotate: '1turn',
  backgroundColor: '#FFF',
  duration: 2000,
  loop: true
});
  }
  render() {
    return(
      <div class="anim">
       Here goes the element you want to animate!
      </div>
    )
  }
}

export default Killpop`
