### ISSUE TITLE
Allow `target` property in timeline.

### ISSUE THREAD

**Issue by RyoIkarashi** [juliangarnier/anime#341]
Hi, first off thank you for creating this great lib.

I think it's inconsistent not to allow to have `target` property of an added animation conf in timeline while not timeline animations can have `target` or `targets` property.

[Here is the line](https://github.com/juliangarnier/anime/blob/master/anime.js#L956)

In timeline, `target` property is not allowed.

```js
anime.timeline().add({
   // not allowed and will raise an error `Cannot read property 'targets' of undefined`
   target: '.className',
});
```

But without timeline, `target` property is allowed.

```js
anime({
   // while this is allowed
   target: '.className',
})
```

What do you think on this? @juliangarnier

**Comment by juliangarnier** [comment]
It's because you use `target` instead of `target`.tho

And the error `Cannot read property 'targets' of undefined` in the timeline will be fixed in v3.0!

**Comment by RyoIkarashi** [comment]
Thanks for the quick reply @juliangarnier! 
But what do you mean by "`target` instead of `target`"?
What's the difference between the two?
What I mean is why an animation in timeline does not have an `target` property while `targets` property is only allowed.

**Comment by juliangarnier** [comment]
Hahaha sorry, I made a typo, the correct property is `targets`.

There is no `target` property in both `anime({})` and `anime.timeline({})`.
Always use `targets`.

**Comment by stephan281094** [comment]
@juliangarnier Do you have some more information on the `Cannot read property 'targets' of undefined` error? We're experiencing this error in a project and would love to find a workaround we can use before 3.0 is out.

**Comment by juliangarnier** [comment]
You forgot or misspelled a `targets`property somewhere in your code.
