### ISSUE TITLE
how to correctly 'scale' with <patch>?

### ISSUE THREAD

**Issue by ogoagency** [juliangarnier/anime#343]
Hi:
https://codepen.io/juliangarnier/pen/dXNgVB
update code HTML:
<path fill="none" stroke="#FFF" style="transform:scale(2)" ...

**Comment by alexchantastic** [comment]
I think this is more of a general CSS/SVG question. You'll want to put the `transform` on the `<svg>` element rather than the `<path>` otherwise it will clip due to the `viewBox` definition.

**Comment by juliangarnier** [comment]
For questions related to animation problem or help regarding animation techniques, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
