### ISSUE TITLE
Animation for filters

### ISSUE THREAD

**Issue by metalfox6383** [juliangarnier/anime#344]
Hi: I like this tool. It's too easy to use. Thanks!

I would like to animate filters like blur. Actually I use a object for this effect, but it would more easy if it be possible to use a property like 'blur', for example.

Thanks.

**Comment by juliangarnier** [comment]
You can, see this example: http://animejs.com/documentation/examples/anime-complex-properties.html

**Comment by metalfox6383** [comment]
Oh WOW! Ok, sorry. I go to check the documentation.

Thanks!

**Comment by ganlanyuan** [comment]
> 

This page is not available.

**Comment by Pulse-Git** [comment]
@ganlanyuan here is the source: [https://github.com/juliangarnier/anime/blob/master/documentation/examples/complex-properties.html](https://github.com/juliangarnier/anime/blob/master/documentation/examples/complex-properties.html)
