### ISSUE TITLE
Prestaging animation in a object 

### ISSUE THREAD

**Issue by sononix** [juliangarnier/anime#346]
Trying to lower overhead while initiating an animejs object by prestaging it 

SlideContent: anime({
          targets: '.slide1',
          translateY: 500,
          autoplay: false,
          duration: 1000
      })

and then trying to call using 

SlideContent.play()

All this code was in a callback function which was causing issues on the position on the div,

creating the anime object inside the callback was fine even when I was deep cloning the props using lodash 

Any ideas how to initialise an element starting position - interrupting the reverse() method call within a click event is causing problems for me trying to debug is tricky 
tks

**Comment by alexchantastic** [comment]
I think you'll likely need to move the animation instantiation outside of the callback or replicate the starting animation properties in the element's CSS declarations.

**Comment by juliangarnier** [comment]
You can now sets values directly using `anime.set()` https://animejs.com/documentation/#set
