### ISSUE TITLE
Uncaught TypeError: Cannot set property 'anime' of undefined

### ISSUE THREAD

**Issue by meiskv** [juliangarnier/anime#347]
Hi,

First, thank you for this awesome library. I hope you could help me sort out what could be wrong in my script. I am using jointswp on npm and I am getting this error, also when I click the error it points me to the anime.js file on this line. I even tried putting it on header as a normal script tag but it still didn't work.

  } else {
    // Browser globals (root is window)
    root.anime = factory();   <------
  }

Regards,
Mikhail

**Comment by meiskv** [comment]
I manage to make it work on header now. But is it possible to put it onto my npm builder? so it will be compressed just like the other modules that I am using?

Cheers!

**Comment by alexchantastic** [comment]
You can include anime as part of your `package.json` dependency list, but you will need to use a bundler like webpack to import it into your actual app/site code.

**Comment by juliangarnier** [comment]
For questions related to animation problem or help regarding animation techniques, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
