### ISSUE TITLE
How do you animate only once?

### ISSUE THREAD

**Issue by FateRiddle** [juliangarnier/anime#348]
I'm doing a scroll animation, in css, we can do:
``` js
if( element is visible ) {
  element.addClass('fade-in')
}
```
Then the animation will only run once.

But I don't know what to do, 
```js
if( element is visible ) {
  anime({
    ...
  })
}
```
the animation will run every time I scroll, if it is visible.

**Comment by juliangarnier** [comment]
```
var myanim = anime({
  ...,
  autoplay: false,
});
```
Then 
```js
if (element is visible) {
  myanim.play();
}
```

**Comment by FateRiddle** [comment]
@juliangarnier 
I tried and it didn't work.
Logically it shouldn't either.
```js
if (element is visible) {
  myanim.play();
}
// real code will be like
...
container.addEventListener('scroll', () => {
   const el = document.querySelector('el')
   const el_top = el.getBoundingClientRect().top
   if(window.innerHeight > el_top + 100) {
      myanim.play();
   }
})
```
If elment is visible, whenever I scroll, the function handling scroll will be triggered, and `myanim` will be played.

**Comment by lucasbaze** [comment]
@FateRiddle Using InterceptorObserver, I did effectively the same thing, but added an extra `played` check: 

```
if(window.innerHeight > el_top + 100 && !played) {
  myanim.play();
}
```
