### ISSUE TITLE
Is there a way to keep the aspect ratio of an animated Element contents?

### ISSUE THREAD

**Issue by distante** [juliangarnier/anime#349]
I am animating a button on click to be full screen and I want to know if is possible to keep the aspect ratio of button contents (in this case a couple of divs and div childs).

Is it possible? I haven't found anything related in the docs but maybe I have overlook something. 

Thanks.

**Comment by distante** [comment]
Hello, sorry since then I ditched animation altogether mostly because I want to focus on other parts of my code.

I can thought explain a little bit more.  I had a rectangular div like **200px width and 100px height** with some text inside.
On click it grow to the 100% viewport width and height of an regular Smartphone. While transitioning the text inside the div was also changing proportions. And that is what I wanted to avoid.

**Comment by juliangarnier** [comment]
For questions related to animation problem or help regarding animation techniques, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
