### ISSUE TITLE
Shake / Wiggle / Vibrate

### ISSUE THREAD

**Issue by stevenchu** [juliangarnier/anime#35]
Update:  I got most of the way: http://codepen.io/stevenchu/pen/KrXyZW
(this codepen above i nested all the other var functions. i know i could have kept them separate, but i wanted to try it and it worked out nicely)
*Need help to restart the entire loop!*

How?
I tried experimenting and modifying the callbacks.html demo example to give one of the animations a fixed number of loops, but have not been able to get the original loop to replay.

* * * * * * * 

Novice in need of help! I want to achieve a suspended explosion effect that comes to a halt and reverses itself like a vacuum (the type you might see with star wars / star trek / matrix)

I'm attempting to create this action sequence by:
1) boxes rumbling shake with a realistic easing
2) boxes explode.. translateX translateY with an easing that feels like you're catching explosion midmotion  (i used the random target values demo as my base..)
3) boxes reverse back to starting position , and have this repeat on a loop

Pen1: I have the rumble going into explosion here:
http://codepen.io/stevenchu/pen/akLpNE
Pen2: And I have the isolated suspended motion on an easing loop here:
http://codepen.io/stevenchu/pen/VjrPyg

but I'm not really sure how to put the two together! I would love to play it in reverse from here.

As an alternative, Pen3: I got it to rumble > explode swing motion which returns back to beginning > 2nd rumble doesn't really work though > how to loop back to beginning and play again on loop?:
http://codepen.io/stevenchu/pen/WxkRKo

--
General Pen1 Issues:
*could the shaking start out slow then increase?
*I'm having trouble getting the explosion (translateX/rotate/scale from the random target values demo) to play the easing as well as follow the duration?

Thank you!!

**Comment by juliangarnier** [comment]
Hey,

So I think I found a bug with the loop count when you try to replay ou restart the animation, I'll look into that.

But for the effect you're trying to achieve, if understand correctly, you can simply wrap both effect into one function, and call this function when the last one ends.

See : http://codepen.io/juliangarnier/pen/BzmyWQ?editors=0010

**Comment by stevenchu** [comment]
Ah! Thank you! 
i didn't think to put the translateX between [2 values] like that.

is it possible to have the easing effect apply to all the rumbles.. so that the rumbles increase over time?

**Comment by juliangarnier** [comment]
No sorry, the easing only works between 2 values.
But you can try wrapping the shaking animation into a function without the `loop:10`, and re-run the function 10 times while increasing the value.

Hope that helps!
