### ISSUE TITLE
Unable to draw lines by using anime js

### ISSUE THREAD

**Issue by Syedwaheed** [juliangarnier/anime#350]
I m having problem with creating more paths by using anime library. I have created the text in abode illustrator and convert it to paths for anime drawing line.I can see that i m able to create 6 characters but more than 6 are not showing up. Here is my code pen any help would be greatly appreciated.
https://codepen.io/waheedshah/pen/ZxWZMW
@juliangarnier Please help. Thanks  in advance

**Comment by tcjr** [comment]
I think it's unrelated to anime.  Your svg viewbox is wrong.  Try changing it.  For example:
```
<svg viewBox="0 0 560 70" preserveAspectRatio="xMaxYMax meet">
```

**Comment by juliangarnier** [comment]
Please use [stackoverflow](https://stackoverflow.com/) for this kind of questions.
Thanks
