### ISSUE TITLE
Animate svg stroke 

### ISSUE THREAD

**Issue by nicoladl** [juliangarnier/anime#352]
Hi, how can I animate color of a svg?

`strokeColor.add({
        targets: '.contact-init svg circle',
        stroke: '#DB3E34',
        offset: 0
      })`

What I'm going wrong?

This is the svg code:

`<svg class="cta-icon" x="0px" y="0px" viewBox="0 0 30 30">
	<circle cx="15" cy="15" r="13" stroke-width="2" fill="transparent" />
</svg>
`

Thank you

**Comment by juliangarnier** [comment]
You're targeting `circle`, not `line`

**Comment by nicoladl** [comment]
@juliangarnier Fixed typo.

I tryed some combination like:
`targets: '.contact-init svg'`
`targets: '.contact-init svg circle'`

It doesn't works.

**Comment by nicoladl** [comment]
Fixed
