### ISSUE TITLE
Clip-path on Safari

### ISSUE THREAD

**Issue by nicoladl** [juliangarnier/anime#353]
Hi guys!
I can't animate clip-path on Safari. I provide a pen:
https://codepen.io/nicoladelazzari/pen/NYBEmZ

Safari doesn't animate div like Chrome

Thanks you!

**Comment by Mohsen-Khakbiz** [comment]
I think you need to use the prefixed clipPath as well. it's webkitClipPath https://codepen.io/Mohsen-Khakbiz/pen/qoMJpw

**Comment by nicoladl** [comment]
Thanks @Mohsen-Khakbiz, you made my day!

**Comment by DrZivil** [comment]
How can i use webkitClipPath in addition?
Tried it like this but it seems to do nothing - only animating the usual clipPath attribute.
`clipPath: ['inset(0 0 0 0)', 'inset(30% 0 0 0)'],
            webkitClipPath: ['inset(0 0 0 0)', 'inset(30% 0 0 0)'],`
thankd
