### ISSUE TITLE
Animation inside setTimeout function not firing

### ISSUE THREAD

**Issue by developer-jox** [juliangarnier/anime#354]
Hi, I'm having issues firing a animation inside a setTimeout function. My code looks like this: 
```js
function resize_functions() {
    resize_timeout_ID = window.setTimeout(function () {
        anime({
          begin: function () {
            $('.floating-button').removeClass('resizing-hide');
          },
          targets: '.floating-button',
          opacity: [0.2, 1],
          duration: 100
        });
        // other code
    }, 150);
}
```
So the code is supposed to show a semi-hidden button when the window has stopped resizing. resizeFunctions() is called each resize via a resize event listener and the timeout is cleared if the window is still resizing. However, the animation is not firing when it is inside the setTimeout function. Does anyone have any idea what could be the problem? Is this a known issue? (Great library btw, love it so far) 

Regards, 
jox

**Comment by alexchantastic** [comment]
I think the issue may stem from instantiating the animation inside of your event handler. A better approach might be to instantiate the animation outside the handler and then use the included [playback controls](https://github.com/juliangarnier/anime#playback-controls) to start the animation.

**Comment by developer-jox** [comment]
Thank you for the tip, it solved the problem. A heads up for anyone who encounters a similar issue in the future: If the animation is not firing the best approach would be to use playback controls or if that is not possible, you could also use a slight delay with the setTimeout function. Thanks again @alexchantastic
