### ISSUE TITLE
jumping/glitching issue

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [juliangarnier/anime#355]
hey there.

first of all thanks for this awesome plugin.

I was trying to create animations triggering by mouse events. but had some issues. it's like jumping values or glitching. and mostly happening when an animation isn't fully done and the next animation is triggered. here's an example https://codepen.io/Mohsen-Khakbiz/pen/bvmKbN
and an screenrecord https://www.dropbox.com/s/8kp794d89wbtvzc/anime-issue.mov?dl=0

**Comment by juliangarnier** [comment]
Use `anime.remove(el)`before triggering an other animation.

**Comment by Mohsen-Khakbiz** [comment]
awesome. that worked. thanks a lot!
