### ISSUE TITLE
Animation isn't smooth.

### ISSUE THREAD

**Issue by andrewnoskov** [juliangarnier/anime#358]
In that [example](https://codepen.io/AndrewNoskov/pen/LdXBbw) I see an **explicit freezes** in comparing to GSAP. Animation **doesn't seem to be smooth**. It looks like an object is animating with small jumps. Lib is amazing. I like its API, but that obstacle with performance is very annoying. Any ideas?
![Test](https://user-images.githubusercontent.com/19951773/38460234-746e7b8c-3abe-11e8-9a20-51595587efd2.gif)

**Comment by atomiks** [comment]
GSAP is using `translate3d` instead of regular `translate`.

Quote from him:
>[3D-related transforms] generally forces the browser to "layerize" that element (think of it like taking a photo of its pixels and storing them on the GPU) which is then faster to manipulate since its pixels are separated from the rest of the screen's/layers'. Typically you'll see smoother animations with this technique. However, there's a small cost to layerize something initially (shuttle the pixels to the GPU).

You can explicitly hardware accelerate the layer by using `will-change: transform;` which should achieve smooth results.
https://codepen.io/anon/pen/oqRaPz

**Comment by AndrewNoskov** [comment]
So, why animejs doesn't use translate3d?

**Comment by AndrewNoskov** [comment]
@atomiks I don't feel comfortable to add css property
```
will-change
```
to every animateble target before  and after animation (for performance purposes).

**Comment by atomiks** [comment]
I agree, it  should default to `translate3d`. 

Also note: there is a bug in Firefox with subpixel translation (ongoing issue for 6 years). It's jerky in both GSAP and anime even with `will-change: transform`. You need to add a hack: `rotate: 0.01` for it to be smooth in FF.

**Comment by juliangarnier** [comment]
You can add `'translateZ: 0'` in your animation or `will-change: transform` in the CSS to force hardware accelerated animations.

Forcing hardware acceleration is not always recommended, that's why I prefer to let the user decide.

**Comment by rnnyrk** [comment]
We also experience performance issues when animating multiple `translateX` / `translateY` values of elements on the screen. Any tips to improve performance? Already tried adding `will-change`, but we can't add the `translate3d` anyhow..

**Comment by reunefe** [comment]
@rnnyrk any improvements found?
I'm having the same difficulty. Spawning at random positions items, then creating another random point and let the item rotate in the right direction and move it to that point. At the end of the animation, again create another random point and start rotating and moving etc etc.
It's extremely lagging and jumping when doing this with 100 items :/

**Comment by rnnyrk** [comment]
@reunefe didn't really found a solution. Made the animation smoother by animating lesser elements.

**Comment by dangelion** [comment]
Is there something new on this? For example an option to force hardware accelerated animations?

Otherwise, as a workaround, is there a way to **globally** set `translateZ: 0` for all animations?
