### ISSUE TITLE
Morph svg with clip-path not works on Safari

### ISSUE THREAD

**Issue by nicoladl** [juliangarnier/anime#359]
Hi guys!
I'm trying to morph an svg. The problem is that the clip-path property not woks on Safari.
I provide a pen: 

https://codepen.io/nicoladelazzari/pen/PRVEPp

Thanks!

**Comment by alexchantastic** [comment]
Not sure if this is an anime issue. Safari seems to need a vendor prefix on `clip-path` (`-webkit-clip-path`) to work: https://caniuse.com/#feat=css-masks.

**Comment by nicoladl** [comment]
Hi @alexchantastic thanks for your answer.
How can I add vendor prefix in this particular case?

**Comment by nicoladl** [comment]
Thanks @alexchantastic 
I need vendor prefix during anime morph. If I add vendor prefix as your suggestion morph doesn't show.

I have update pen link: https://codepen.io/nicoladelazzari/pen/PRVEPp

**Comment by alexchantastic** [comment]
I think this might be an issue with `clip-path` support on Safari. Here is the related webkit bug: https://bugs.webkit.org/show_bug.cgi?id=126207

A way around this would be to force a repaint like so:

```js
anime({
  targets: '#axure-svg .anime',
	points: [
    { value: '625.1,-3.7 237.2,0 197.2,0 166.6,0 0,0 0,361 50,361 60.3,361 80.5,361 139.5,361 197,361 237,361 267.5,361 306.5,361 343.5,361 389.6,361 431.4,361 470.2,361 524.9,361 582.6,361 625.1,361 ' },
    { value: '175.6,17.9 48.1,291.7 29.9,291.7 166.6,0 145.6,0 0,310.7 60.2,310.7 60.3,310.7 175.6,63 282.4,291.7 264.4,291.7 176.2,103.8 78.9,310.7 139.2,310.7 184.6,213.4 163.6,213.4 127.1,291.7 108.9,291.7 176.2,148.5 252.3,310.7 312.2,310.7 ' }
	    	  ],
  duration: 2000,
  loop: true,
  update: () => {
    const el = document.querySelector('.background-content');
    
    el.style.display = 'none';
    el.offsetWidth;
    el.style.display = 'block';
  }
})
```

**Comment by nicoladl** [comment]
Thanks @alexchantastic it works! 

:rocket:
