### ISSUE TITLE
Delay Timing?

### ISSUE THREAD

**Issue by Crisfole** [juliangarnier/anime#365]
I didn't see anything in the documentation or issues about this: is there a way to indicate when you'd like a delay to happen? (For example: only *between* loops).

**Comment by Crisfole** [comment]
So far my best bet *appears* to be:

```
// Animate the sun across the sky...rather quickly for this purpose
return anime({
	targets: this.el,
	translateX: [
		{ value: endLeft + width, easing: "linear"  }
	],
	translateY: [
		{ value: "-=100", easing: "easeOutCirc", duration: 5000 },
		{ value: "0", easing: "easeInCirc", duration: 5000 },
		{ value: "0", delay: 5000, duration: 0 }
	],
	loop: true,
	duration: 10000,
}).finished;
```

Unfortunately this means (and not a big deal really) that I have to manually calculate the duration of each Y translation...

**Comment by juliangarnier** [comment]
[(anime v3)](https://github.com/juliangarnier/anime/tree/dev) will add an `endDelay` parameter.
This let you add some delay in between tweens or loops.

You can try the beta, it's pretty stable, but can breaks 2.x animations since I changed a few things in the API.

**Comment by Crisfole** [comment]
Wow, awesome. Thanks!
