### ISSUE TITLE
** Question ** Animate CSS transforms

### ISSUE THREAD

**Issue by zzseba78** [juliangarnier/anime#367]
Hi!
First of all, congrat for this awesome library. It´s amazing! Great performance, easy to use, and very lightweight. I come from GSAP, and for the tiny size this baby makes magic, really.

I have one question, because i´m learning some basics and i want to have some concepts clear from the begining.

I´m doing a animated bar for testing, the css for it´s very simple:
```
.bar-left {
	position: fixed;
	top: 0;
	bottom: 0;
	width: 300px;
	padding: 30px;
	background-color: #222;
	color: white;
	z-index: 1;
	transform: translateX(-100%);
}
```
And i want to animate the bar to translateX 0, so:
```
var leftBar = anime({
  	targets: '.bar-left',
  	translateX: 0
});
```
The bar show, and get the style, but without animation, but if i use:
```
var leftBar = anime({
  	targets: '.bar-left',
  	translateX: [ '-100%', 0]
});
```
It works perfect, so, **my question is**:

I have to set the initial css value always? It doesn´t take some defined property in css as a starting point? I´m doing it right?

Thanks and congrats again!
Sebastián.

**Comment by juliangarnier** [comment]
Hey,

Yes, in the case of transforms, if the initial value is not 0,  you have to use the "from to" style array.
Or specify the transform value using inline styles: `style="transform: translateX(-100%)"`.

In [v3](https://github.com/juliangarnier/anime/tree/dev) you will be able to specify initial styles using Anime, like `anime.set('div', {'translateX: -100%'});`.

**Comment by zzseba78** [comment]
Thanks for your response @juliangarnier ! 
Perfect, and great to add the option to set initial styles 👏 

One more question, Anime can deal with different sizes? For example, i have a 100px width box and want to animate it to 100 vw, it change without animation too ( i ask because GSAP deal with this things ). What units can i mix and animate?

Thanks for your work, excellent library!

**Comment by juliangarnier** [comment]
Unit conversion will works in v3 (you can try it [here](https://github.com/juliangarnier/anime/tree/dev/lib)) :)

**Comment by zzseba78** [comment]
@juliangarnier Awesome!! When it will be available approx?

**Comment by juliangarnier** [comment]
It's almost ready!
But I need some time to clean up the documentation and redesign the website.
I want to release it before the summer!

**Comment by zzseba78** [comment]
@juliangarnier Amazing!
