### ISSUE TITLE
the opacity and scale bug

### ISSUE THREAD

**Issue by ggwork** [juliangarnier/anime#37]
1/ the opacity changing time is different from the duration whitch I set
2/ in the begin I uses css set  transform:scale(0),then  I use anime to scale my target to 2,but when the anime inited,it will change scale to 1
my English is not good .promise you can understant. thank you.

**Comment by juliangarnier** [comment]
I don't understand, please provide an example.

**Comment by ggwork** [comment]
I konw what`s  worng  I did . thank you.
