### ISSUE TITLE
Draw and then undraw path?

### ISSUE THREAD

**Issue by MonsterDeveloper** [juliangarnier/anime#370]
I wonder if Anime is able to draw a path, and after for example 10px undraw it, so it is like moving path?

**Comment by juliangarnier** [comment]
Yes, using dashArray.
Have a look a this article that explain how to achieve the "moving path" effect.

https://blog.prototypr.io/how-to-create-the-snake-highlight-animation-with-anime-js-bf9c6cb66434

**Comment by MonsterDeveloper** [comment]
Thanks! P.S I started to make plugin demo page, and maybe we can chat @juliangarnier somewhere, like Telegram?

**Comment by cworf** [comment]
Im sorry to post on a closed thread, but I feel it didnt properly address the question for me. the example given above uses absolute values for the offset and array length, however does not give an example for how to achieve it with an unknown stroke length using `anime.setDashoffest`
