### ISSUE TITLE
For each

### ISSUE THREAD

**Issue by Marianissimus** [juliangarnier/anime#371]
EDIT: Ok, my bad, this error appears when trying to use anime with inviewport.js from here: https://github.com/ianrogren/javascript-inViewport
Hi, I got this error when trying to include anime.js or anime.min.js in an external file or even in the same js file:
anime.min.js:30 Uncaught TypeError: d[f.type].forEach is not a function
    at anime.min.js:30
    at anime.min.js:31
    at anime.min.js:10
    at anime.min.js:10
I've been using anime with no problems for 2 weeks now; what I've been trying today is to use it with an inviewport js library. Thanks.

**Comment by mikicho** [comment]
@Marianissimus please close this issue

**Comment by Marianissimus** [comment]
I chose another way in viewport library. Thanks, anyway.
