### ISSUE TITLE
Scrolling SVG anigmation "jumps"

### ISSUE THREAD

**Issue by mathiasselleslach** [juliangarnier/anime#372]
Dear,

I am converting a polygon from a rectangle to a triangle on scroll.

This is the AnimeJS code that I have currently
```
var position2 = '300,0 300,35 150,35 150,' + coef;
        var morphing2 = anime({
            targets: '.polymorph2',
            points: [
                { value: position2 },

            ],
            // easing: 'easeOutQuad',
            duration: 350,
            loop: false,
            autoplay: true
        });
```

This is located in my eventlisteren on scroll.
All works fine when you scroll fairly slowly...The rectangle redraws itself into a triangle nicely.

But when I scroll more quickly, it animates properly but then at the very end there is some kind of a "flicker" where the triangle jumps back up to a rectangle for a split second and then goes back to its triangular shape.

I was reading something about setting a timeout here, but that does not solve the problem :(

Any suggestions on this one?

**Comment by juliangarnier** [comment]
Sounds like you are triggering the animation on every scroll events.
That means that you're creating multiple animations on the same element that overlaps on scroll.

You should use `autoplay: false` then morphing2.play() when you want the animation to start.

This way only one animation is created.

**Comment by mathiasselleslach** [comment]
Hi @juliangarnier ,

Thanks for you superfast response.
Well, that is kinda tricky, as I want the animation to gradually shape the rectangle into a triangle as you scroll...

So if you scroll down, it shaped (morphs) into a triangle, if you scroll back up (even only halfway through for example) i want it to reverse back into a rectangle.

Or am I misunderstanding your API? :)

**Comment by juliangarnier** [comment]
Ok so you should use `.seek()` based on the scroll position.
something like 
```
var scrollProgress = .6; // From 0 to 1
morphing.seek(morphing.duration * scrollProgress);
```
http://animejs.com/documentation/#seekAnim

**Comment by mathiasselleslach** [comment]
many thanks @juliangarnier 
I was unaware of this.
I will have a look and see if I can figure out how to map this to the scroll event listener.
