### ISSUE TITLE
anime.js and morphing SVGs

### ISSUE THREAD

**Issue by BarKchris** [juliangarnier/anime#375]
Hy everybody :) 

I am getting started with SVG and Animations and trying anime.js to get work, but I do something wrong -  I guess. Basically i try to morph the Anchor-Points like it is done in this tutorial: https://www.youtube.com/watch?v=2wr1iixy20I. Please, anyone know what I am doing wrong? Nothing happens at all. 

````
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Unbenanntes Dokument</title>

<link rel="stylesheet" href="style.css">
<script src="anime.min.js"></script>
</head>

<body>
	
	
	
	<svg viewBox="0 0 300 100">
		<rect class="polymorph" width="100%" height="100%"/>
		<polygon class="polymorph" points="300,100 0,100 0,0 58.7,0 300,0"/>
	</svg>

	
	
	<script>
		
var morphing = anime({
  targets: '#morphing .polymorph',
  points: [
    { value: '300,100 0,100 0,0 58.7,0 78,70' }
    
  ],
  easing: 'easeOutQuad',
  duration: 2000,
  loop: true
});
</script>
	
	
	
</body>
</html>
```
`

**Comment by juliangarnier** [comment]
I don't see any ID `#morphing` in your SVG.
You're not targeting anything, try `targets: '.polymorph',` instead.

Please use [stackoverflow](https://stackoverflow.com/) in the future if your question is not related to a bug in the library.
