### ISSUE TITLE
[Request] Functionality to duplicate DOM node

### ISSUE THREAD

**Issue by mesqueeb** [juliangarnier/anime#377]
I'd love a parameter like "`duplicateNode: true`"
That would make it so the dom node is duplicated on the spot and the animation is only done on the duplication.

Great to make items fly into a cart but keep the original dom item in place!

**Comment by everdimension** [comment]
@mesqueeb You can do it yourself though, can't you?
I'm currently doing this as well where I need to

Something like

```js
anime({
  targets: targets.map(n => n.cloneNode(true)),
  /* other options */
});
```

**Comment by mesqueeb** [comment]
Wow! What a great hint! This should be added to the readme!! : D

**Comment by everdimension** [comment]
As I understand, this library is more low level and shouldn't be responsible for decisions like this. It's up to you do decide which dom nodes to animate and whether you need to clone the existing ones or not.

**Comment by mesqueeb** [comment]
Since I believe a lot of people would need this I just thought that it would be great to add it to the readme. I don't think many people know about the magic you did there: `targets.map(n => n.cloneNode(true))`.
I didn't know that was possible myself! : D

**Comment by juliangarnier** [comment]
This is more JS related than anime.js related, and way too specific to be added in to the doc.
Thanks @everdimension for the solution !
