### ISSUE TITLE
Restart animation

### ISSUE THREAD

**Issue by Piero87** [juliangarnier/anime#380]
Hi,
I have just discovered this library, and it's amazing, really great work, I have a question about the usage, I have connected on the click of a button a simple animation:

          var cssSelector = anime({
           targets: '.js-search-icon',
           rotate: '1turn'
          });

When I press it the first time I can see it, but if I press it another time the animation no longer works, can anyone explain me why?

**Comment by juliangarnier** [comment]
The animation rotates the element from `0` (default) to `'1turn'`.
Then if you animate it again, it will try to animate the element from '1turn' (the new value) to '1turn'.

Some options:

Force the initial value:
```
var rotateIcon = anime({
  targets: '.js-search-icon',
  rotate: ['0turn', '1turn']
});
```

Or add one more turn each time:
```
var rotateIcon = anime({
  targets: '.js-search-icon',
  rotate: '+=1turn',
  autoplay: false
});
```

Or create your animation outside the click event:
```
var rotateIcon = anime({
  targets: '.js-search-icon',
  rotate: '1turn',
  autoplay: false
});
```
then call it on click or whatever:
```
rotateIcon.restart()
```
This will restart the animation, from 0 to 1.

Next time look the documentation http://animejs.com/documentation/#restartAnim

**Comment by Piero87** [comment]
Thank you very very much!
