### ISSUE TITLE
update Callback is always running

### ISSUE THREAD

**Issue by plakadiva** [juliangarnier/anime#381]
I tried to animate an SVG Element by using the timeline. Because i needed to morph a Shape with different number of points i tried to combine AnimeJS with flubber (https://github.com/veltman/flubber) which worked well exactly for 1 Animation with the update-callback. As I tried a multipart timeline Animation i found the update - callback being always fired and not limited to an animation-part. I´m not sure if it´s intended to function that way or if it´s a bug because all other callbacks are limited to their animation part and duration.

Anyway, on line 846 in the source-code of animejs the update is fired without any conditions, so i changed 
`setCallback('update');`
to
`
  if (engineTime < insDuration && insTime > insStart){
        setCallback('update');
 }
`
It limits the update Function to the time an animation-part is runnig. I´m not sure if i destroy any peace of code doing something else with that condition.
Maybe it helps making animeJS even greater, maybe i´m the only one who needs that...

**Comment by juliangarnier** [comment]
Is this still and issue in V3?

**Comment by plakadiva** [comment]
V3 solves that problem and much more - thank you!
