### ISSUE TITLE
Change layers during animation

### ISSUE THREAD

**Issue by babacry** [juliangarnier/anime#382]
I am wondering is it possible to make layers change during animation:
I am trying to animate planets rotating a star with planets passing **behind** star and passing **above** star alternating with each other. But I don't want to separate the animation into several parts cause I may have multiple planets.

**Comment by alexchantastic** [comment]
You could look into changing the `z-index` of each of the layers in an `update()` callback.

**Comment by babacry** [comment]
Thanks, that works!
