### ISSUE TITLE
Anime on WordPress

### ISSUE THREAD

**Issue by victagon** [juliangarnier/anime#387]
I'm trying to use Anime.js on a WordPress page but getting nowhere. Loading it according to WordPress standards: in functions.php using wp_enqueue_script(), then add_action(). That works fine, in Developer Tools you can see the <script> tags appear on the page. But when I call it from another script file (loaded the same way, and visible on the page) nothing happens: no error messages in the console, no animation. Same setup on a regular basic HTML page works fine, as expected. I've tried loading Anime from a CDN and also from the back-end; no difference. Deliberate typos in the code give the expected error message in the console.

Have done quite a bit of Googling but can't find any references. (Same goes for Velocity.js by the way, can't get it to work.)

What I can get to work without problems is Typed.js by Matt Boldt. Not sure if it's relevant but with Typed you instantiate an object and work with that (new Typed(elementId: string, options: object): object). (I'm an intermediate JS'er, definitely no expert.)

Any ideas, leads would be most welcome!

Thanks in advance,
Ruud.

**Comment by victagon** [comment]
...did some more experimenting: GSAP works as expected when used as described above. Although having GSAP available more or less solves my problem I would prefer Anime, because i'm quite used to it.

Also this makes me curious...why does one library work out of the box, the other not so much?! Probably some language issue I'm not aware of...so any ideas still most welcome!

Thanks,
Ruud.

**Comment by alexchantastic** [comment]
This is probably more of a WordPress question than an anime question. If you can point me to your WordPress instance, I can try to help you out. However, if you are including anime correctly, `anime` should be available at the global scope.

**Comment by victagon** [comment]
I guess it is, was just hoping someone reading here might recognize the issue. In the meantime I found out what the problem is.

One of the parameters to wp_enqueue_script() determines where a script is loaded: in the <head> or just before </body>. If you load it in the <head> (which is a bit counter-intuitive to me) it works fine. Don't really get why, but that definitely is a WordPress question, so I won't ask it here...

**Comment by alexchantastic** [comment]
@victagon glad you were able to figure it out.

On the topic of loading anime in `<head>` vs before `</body>`. The issue could be that there are some dependencies needed before the DOM is fully loaded. The specifics are hard to say without having a peak at the instance.
