### ISSUE TITLE
Update values on the timeline

### ISSUE THREAD

**Issue by byelik** [juliangarnier/anime#389]
Hello. How to update an animation on the timeline?
Thanks in advance?

**Comment by alexchantastic** [comment]
Do you mean change animation values in an existing timeline?

**Comment by byelik** [comment]
yes

**Comment by alexchantastic** [comment]
I don't believe you can modify an animation that has already been instantiated, but you can add another child to an existing timeline.

If you are looking to modify the animation properties based off of some condition, you can also pass a function instead of a value.

**Comment by eruecco87** [comment]
@juliangarnier I was checking the API on how to do that, I need to animate an element that will have different heights dynamically from 0 to element.innerHeight() so when the animation runs the element will have different heights than before.

Right now I managed to do this by with a really hacky solution. Is there a better way to do this?

Timeline declaration
```
let timeline = anime.timeline({
      autoplay: false
    });

    timeline
      .add({
        targets: '#lower-third',
        opacity: '1',
        duration: 1,
        easing: 'linear'
      })
      .add({
        targets: '#lower-third .title',
        left: 0,
        offset: '+=1',
        duration: 1000,
        easing: 'easeOutElastic',
        elasticity: 100
      })
      .add({
        targets: '#lower-third .line',
        width: {
          value: '500',
          duration: 600,
          easing: 'easeOutElastic',
          elasticity: 200,
        },
        opacity: {
          value: 1,
          duration: 700
        },
        offset: '-=300'
      })
      .add({
        targets: '#lower-third .content',
        height: function (el, i , l) {

          return $('.content').find('p').innerHeight();

        },
        duration: 1000,
        easing: 'easeOutElastic',
        elasticity: 500
      });
```

Update value hack
```
$title.text(message.title);
      $content.text(message.content);

      timeline.children[3].animations[0].tweens[0].to.numbers[0] = $('.content').find('p').innerHeight(); // HACK
      timeline.children[3].animations[0].tweens[0].to.original = $('.content').find('p').innerHeight() + 'px'; //HACK

      if (timeline.reversed) {

        timeline.reverse();

      }

      timeline.play();
```

**Comment by juliangarnier** [comment]
Hey, there are currently no way to update values of an animation after its initialisation other than changing its values in the object (like @eruecco87 did) but this won't update whole keyframes or next timeline animations value accordingly.
