### ISSUE TITLE
Promise after restart

### ISSUE THREAD

**Issue by oscarotero** [juliangarnier/anime#392]
Hi, thanks for this awesome library!
I have this code:
```js
const anim = anime({
    targets: 'rect',
    width: 200,
    height: 400
});
anim.finished.then(() => console.log('Animation finished'));

btn.addEventListener('click', e => {
    anim.reverse();
    anim.play();
    anim.finished.then(() => console.log('Reversed animation finished'));
});
```

The first promise works fine, the console.log is executed just after the animation is finished. The seconds promise is executed when the second animation starts. I guess it happens because it is the same promise than the first animation, not a new promise. Is there a way to have a promise resolved after the second animation ends?

I made a pen reproducing this issue: https://codepen.io/oscarotero/full/MXVpYJ

Thanks in advance

**Comment by tbranyen** [comment]
Found the bug with the Promise implementation and found a bug in anime where it does not reset the `completed` property when `play()` happens. 

Sorry this took so long to respond to, but I'll issue a PR soon (if one isn't already there).
