### ISSUE TITLE
Delay between animations?

### ISSUE THREAD

**Issue by mxmtsk** [juliangarnier/anime#395]
I have created a simple timeline but there seem to be a delay between the first animation (red words) and the second one (big headline). Is this intended, can this prevented or am I doing something wrong? I'd expect to fire the second animation immediately.

![x](https://user-images.githubusercontent.com/4848184/41813411-1f0a1e94-7736-11e8-827f-b65f60e99673.gif)

```Javascript
      anime
        .timeline({ complete: function() {
            resolve();
          } })
        .add({
          targets: ".article__header h2",
          translateY: [100, 0],
          translateZ: 0,
          opacity: [0, 1],
          easing: "easeInOutCubic",
          duration: 1000
        })
        .add({
          targets: ".article h1 .letter",
          translateY: [100, 0],
          translateZ: 0,
          opacity: [0, 1],
          easing: "easeInOutCubic",
          duration: 1400,
          delay: function(el, i) {
            return 300 + 30 * i;
          }
        });
```

**Comment by acemir** [comment]
You should apply `offset: 0` in the seconda animation.

**Comment by mxmtsk** [comment]
@acemir Thanks, that did solve it for me. :)
