### ISSUE TITLE
Trigger animation by adding class

### ISSUE THREAD

**Issue by Gloosecap** [juliangarnier/anime#396]
Hi,

I'm wondering if its possible to play an animation when an element enters the viewport. Lets say I were using something like Scrollspy to detect when a div enters the viewport, a class would added to the div such as "in-visible". Is it possible to start the animation once the class is added? Any thoughts on how to play an animation based on a class being added?

Thanks

G

**Comment by alexchantastic** [comment]
It's probably best to trigger the animation through a callback instead. Monitoring a class using a polling or DOM monitoring method seems quite heavy.

**Comment by agnieszkabugla** [comment]
I have got a function that checks if an element is scrolled into view, then, in simple if-statement I check if the element is in viewport, if yes, I trigger an animation. 
Have a look at my code below:

```javascript

  function isScrolledIntoView(elem) {
      var docViewTop = $(window).scrollTop();
      var docViewBottom = docViewTop + $(window).height();
      var elemTop = $(elem).offset().top;
      var elemBottom = elemTop + $(elem).height();
      return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
  }
```

```javascript 
 $(window).scroll(function () {
       if (isScrolledIntoView('section#therapy .praluent-flex .box-1') === true) {
        var relativeOffset = anime.timeline();

        relativeOffset
            .add({
              targets: '.praluent-flex-anime .box-1',
              translateY: -200,
              easing: 'easeOutExpo',
            })
            .add({
              targets: '.praluent-flex-anime .box-2',
              translateY: -200,
              easing: 'easeOutExpo',
              offset: '-=600' // Starts 600ms before the previous animation ends
            })
            .add({
              targets: '.praluent-flex-anime .box-3',
              translateY: -200,
              easing: 'easeOutExpo',
              offset: '-=800' // Starts 800ms before the previous animation ends
            });
       }
  });
```

**Comment by equinusocio** [comment]
@agnieszkabugla What about intersectionObserver?
https://developers.google.com/web/updates/2016/04/intersectionobserver

**Comment by agnieszkabugla** [comment]
@equinusocio That's also an option 👍  :)

**Comment by equinusocio** [comment]
Any update to support IO natively with the lib? I find very useful a way to trigger each element animation only if in viewport using the intersection observer. 

For example, it's very useful in lists with infinite elements, where each item should be animated only when scrolled in (applied also for containers with overlflow.)

**Comment by bhavikji** [comment]
@juliangarnier I agree with @equinusocio please provide support for IO this thing seems very promising!
