### ISSUE TITLE
Change animation destination with inertia?

### ISSUE THREAD

**Issue by everdimension** [juliangarnier/anime#397]
Hello! I like your library a lot so far, but there is a feature that I'm missing. Or may be I just don't know how to implement it.

Here's a demo: https://codepen.io/everdimension/pen/LraLLj?editors=0010

Here's a gif that explains the problem: https://imgur.com/a/cZPCu0n
(sorry for the quality, but fortunately this demo is not about performance)

The thing is, if I'm in the middle of an animation and I decide that I need to move the element to another place, I wish that the element wouldn't change its direction so abruptly and instead the new animation would account for current velocity.

Is it possible with animejs?

**Comment by juliangarnier** [comment]
No sorry this is not currently possible.
