### ISSUE TITLE
Home animation - Give access to the buttons

### ISSUE THREAD

**Issue by bichotll** [juliangarnier/anime#398]
Hi there,
I may be because I'm a quick developer, but that animation is actually bothering me...😅
I just want to see the buttons.

Any chance you can change the homepage so it shows the animation while the animation is below...for example?
It's just I visit your website often and it takes me 2s all the time until the buttons are visible when the only thing I want is to click on the `documentation` button 😅

I don't want to despise the animation. It's cool! 👍

**Comment by juliangarnier** [comment]
The website is about to change.

**Comment by juliangarnier** [comment]
Fixed :)
