### ISSUE TITLE
Stop and resume translate animation

### ISSUE THREAD

**Issue by dka09** [juliangarnier/anime#40]
Don't think this is a specific issue with the library (awesome so far by the way) but the way I'm using it but I'm not sure where to get support.

**What am I trying to do?**
I want to animate (translateX) some `.items` from right to left and be able to stop the animation on hover and resume it again when the mouse is no longer hovering. 

**What is the issue?**
I have managed to get the basic animation I want as well as pause by calling `anime.remove('.item');` on hover but it's the resume I cannot manage to work properly. When the resume occurs (I look through each `.item` element and add another animation to it) they slow down and move at different speeds and the items start overlapping. 

I maybe could of used the `play()` and `pause()` functions but I had a little trouble pausing animations by looping through the `anime.list`. Not all `.item` elements would pause and then calling `play()` function on each element didn't resume it.

Here is what I have so far: http://codepen.io/Safinn/pen/qNpdAO?editors=1010

So I need to be able to get the `.item` elements to resume at the same speed (no overlapping). Any ideas? Thanks for the help.

**Comment by safinn** [comment]
I feel like it might be something to do with the `translateX` value. Does it mean it will move so many units from the current position or to the set position in the document? It seems like they have different finishing positions which causes them to move at different speeds.

**Comment by juliangarnier** [comment]
Exactly, `translateX: 100` will move the element **by** `100px` from his current position, try using `left` instead, or calculate de difference between the end point and the current translateX value.

**Comment by safinn** [comment]
Thanks for getting back @juliangarnier 
I calculate the difference between the current left position and the finish position (unless my maths is wrong) and it does not work. Here is my resume function:

```
function resume() {
  // For each element with class '.item'
  $('.item').each(function(index, element) {
    // Calculate new translate and time values using current position (where it stopped).
    var translateValue = $(element).offset().left - finishPosition;
    var time = translateValue / velocity;
    
    animate(element, time, translateValue);   
  });
}
```

Am I doing something wrong?
This is the animate function:

```
function animate(item, time, translatePos) {
  // Animate using the anime library. Same as jQuery or Velocity.js
  anime({
    targets: item,
    translateX: -translatePos,
    duration: time,
    easing: 'linear',
    complete: function(animation) {
      // When the animation is finished, remove the dom element.
      item.remove();
    },
    update: function(animation) {
      // As the item is animating, check if the right position of the item is 50 pixels away 
      // from the end of the container
      if ($(item).position().left <= $('#container').width() - $(item).outerWidth() - 50) {
        // When the right positoon of the item is 50px to the left of the container edge
        // check if there data-done attribute is false
        if (!$(item).data('done')) {
          // If the data-done attribute is false set it to true
          $(item).data('done', true);
          // Add a new item.
          addItem();
        }
      }
    }
  });
}
```
