### ISSUE TITLE
TranslateX/TranslateY bug in Firefox

### ISSUE THREAD

**Issue by NicholasJohn16** [juliangarnier/anime#401]
I'm experimenting with anime and I'm not sure if I've found a potential bug, browser inconsistency or there's just an issue with my svg, but I thought I'd post it here.

I'm animating a circular path along a S shaped path. Everything looks and works great, except when the circle gets to the third curve in the S. Instead of angling along correctly, it seems to follow sort of a diagonal instead. After that point, it never seems to follow the path correctly and lags behind. This only seems to happen in Firefox and looks correct in Edge and Chrome. Not sure why it's happening, but any insight would be appreciated.

Here's an example:  [codepen.io](https://codepen.io/NicholasJohn16/pen/RJXabe)

**Comment by alexchantastic** [comment]
It might have something to do with alignment. I would pull out the circle from the SVG into a separate element like so: https://codepen.io/alexchantastic/pen/mjdKqj

**Comment by NicholasJohn16** [comment]
If you remove the red background and give the circle a red border instead, it's easier to see that it's still moving diagonally on that third curve. It looks like Firefox has an issue with calculating some curves. If you add .001 to each of the points for the curve tho, it fixes the problem. Another issue though is that the circle is offet by .5 in both the x & y for some reason.

**Comment by juliangarnier** [comment]
For questions related to animation problem or help regarding animation techniques, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
