### ISSUE TITLE
Timeline reports invalid and incorrect progress

### ISSUE THREAD

**Issue by ndm2** [juliangarnier/anime#405]
Using the latest 2.2.0 release, timelines seem to generally have some sort of progress calculation problem, as the initial progress is always `NaN`, two times in a row that is. With further animations added, more quirks appear, in the form of progress jumping up and down, like, `0`, `100`, `0`, `50`, `0`, etc. This seems to be affected by the `offset` too.

Here's an example:

```js
var obj1 = {charged: '0%'};
var obj2 = {charged: '0%'};
var obj3 = {charged: '0%'};

anime.timeline({
  update: function(anim) {
    console.log(anim.progress);
  }
})
  .add({
    targets: obj1,
    charged: '100%',
    duration: 100
  })
  .add({
    targets: obj2,
    charged: '100%',
    duration: 100,
    offset: '-=50'
  })
  .add({
    targets: obj3,
    charged: '100%',
    duration: 100,
    offset: '-=80'
  });
```

It will produce something like this:

```
NaN
NaN
50
0
46.666666666666664
0
0
19.64588235294119
29.451764705882344
39.26470588235294
49.02823529411766
58.819999999999986
68.64647058823526
78.4535294117647
88.32058823529411
98.09176470588234
100
```

https://codepen.io/anon/pen/zLKQqw

The problem exists in the latest `dev` branch too, the result is just a little different:

```
NaN
0
100
0
100
0
0
0
0
0
5.482333333333334
5.482333333333334
5.482333333333334
5.482333333333334
16.563333333333333
16.563333333333333
16.563333333333333
16.563333333333333
22.10966666666667
22.10966666666667
22.10966666666667
22.10966666666667
27.70966666666667
27.70966666666667
27.70966666666667
27.70966666666667
33.24033333333333
33.24033333333333
33.24033333333333
33.24033333333333
38.80866666666668
38.80866666666668
38.80866666666668
38.80866666666668
44.39433333333333
44.39433333333333
44.39433333333333
44.39433333333333
49.89366666666668
49.89366666666668
49.89366666666668
49.89366666666668
55.50900000000002
55.50900000000002
55.50900000000002
55.50900000000002
61.02733333333333
61.02733333333333
61.02733333333333
61.02733333333333
66.60300000000001
66.60300000000001
66.60300000000001
66.60300000000001
72.14833333333334
72.14833333333334
72.14833333333334
72.14833333333334
77.72033333333333
77.72033333333333
77.72033333333333
77.72033333333333
83.2466666666667
83.2466666666667
83.2466666666667
83.2466666666667
88.81566666666669
88.81566666666669
88.81566666666669
88.81566666666669
94.38066666666667
94.38066666666667
94.38066666666667
94.38066666666667
99.91766666666666
99.91766666666666
99.91766666666666
99.91766666666666
100
```

**Comment by ndm2** [comment]
So it looks like these update events are being emitted when seeking is applied initially, and `NaN` occours when the current instance time and the timeline duration are both `0`, which is the case before the first child is pushed onto the timeline, then a division by zero occours at https://github.com/juliangarnier/anime/blob/b14a3a963a008fed11620a031ed48284b630143b/anime.js#L806

Fixing the division by zero problem should be easy enough, not sure though what should be done about the update events, maybe during the initial seeking they shouldn't be emitted, or the `began` property shouldn't be `true`?

**Comment by juliangarnier** [comment]
I added a way to avoid callbacks on timeline initialisation on the dev branch.
Thanks for pointing this out !

**Comment by ndm2** [comment]
Works fine :+1:

Is the 2.x branch still receiving updates? If not, then this ticket can be closed I guess.

**Comment by juliangarnier** [comment]
I'll will close it after 3.0 is released.

**Comment by juliangarnier** [comment]
Should be fixed in V3 !
