### ISSUE TITLE
how do you trigger anime.js when it becomes visible?

### ISSUE THREAD

**Issue by iamalessiopaoletti** [juliangarnier/anime#409]
Hi, I do not understand how I can start animations when they are visible like aos.js

**Comment by magnusdahlstrand** [comment]
@iamalessiopaoletti If you set `autoplay: false` on the animation you can call `play` on the animation object when the element becomes visible, and it'll start the animation. This will play the animation only the first time it becomes visible. Swapping `play` for `restart` would make the animation replay from the start every time the element is scrolled into view.

How to determine whether the element is visible? Something like [Waypoints](http://imakewebthings.com/waypoints/) might be what you're after.

**Comment by cheestudio** [comment]
If WayPoints is too hefty, there's always the InView plugin:

https://github.com/protonet/jquery.inview

There are some vanilla JS versions of this floating around, as well. Waypoints is AWESOME, but can be overkill in some situations, especially if you only want it to fire once.

**Comment by juliangarnier** [comment]
For questions related to animation problem or help regarding animation techniques, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.

**Comment by ahsath** [comment]
@cheestudio 

I know this is not the place to comment but I just wanted to point out that you can use the [intersection observer api](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to animate on scroll, it would be a nice feature if was implemented out of the box in animejs since it's such a nice library
