### ISSUE TITLE
Flashing issue on opacity

### ISSUE THREAD

**Issue by CHEWX** [juliangarnier/anime#41]
Hi,

I'm getting a weird flashing issue.

Video here - http://quick.as/BW9OsDO8L

`
                anime({
                    targets: document.querySelector('.fp-section__bg--' + page),
                    opacity: 1,
                    elasticity: 0,
                    easing: 'linear'
                });
`

Thanks,
Tom

**Comment by juliangarnier** [comment]
You're probably using 2 animations, one with opacity: 1, and an other with opacity:0 right?
So this might be caused by an overlap between the two.
Try removing the target from the animation before re-animating it.
like this:`anime.remove('.fp-section__bg--' + page)`.
