### ISSUE TITLE
Border color not animating on IE11 or Edge

### ISSUE THREAD

**Issue by dasmikko** [juliangarnier/anime#413]
I'm trying to animate a border color on a div in a different project, and noticed that anime.js won't animate it when running Internet Explorer 11 or Edge.

It works fine in Chrome

I have created a codepen reproducing the bug, in the simplest way.

https://codepen.io/anon/pen/zLpKgw

**Html**

`<div class="circle"></div>`

**CSS**

```
.circle {
  background: #ccc;
  border-radius: 50%;
  border-width: 5px;
  border-style: solid;
  border-color: rgb(244, 65, 241);
  height: 100px;
  width: 100px;
}
```

**JavaScript**

```
var basicTimeline = anime.timeline();

basicTimeline.add({
  targets: '.circle',
  backgroundColor: '#6a41f4',
  borderColor: 'rgb(65, 244, 70)',
  duration: 10000
}); 
```

**Comment by pooya121** [comment]
Use `borderColor: ['rgb(244, 65, 241)','rgb(65, 244, 70)']` instade of  ` borderColor: 'rgb(65, 244, 70)'`

**Comment by dasmikko** [comment]
Awesome! 

Works as intended now.

Thanks for the help.
