### ISSUE TITLE
anime.js has option objet can follow mouse ?

### ISSUE THREAD

**Issue by matamune94** [juliangarnier/anime#416]
type is question , answer pls ^^ , thank all

**Comment by magnusdahlstrand** [comment]
@matamune94 anime.js has no option for following the mouse. It's unclear from your question how you'd like this to work so I'm unable to provide any more information. Have a search for "javascript follow mouse", there seems to be some good examples on the web.

**Comment by juliangarnier** [comment]
No sorry this is not currently possible.

**Comment by tguelcan** [comment]
you can use a bit of javascript code:

[Demo](https://codepen.io/tguelcan-the-sasster/full/ROoxWm)
