### ISSUE TITLE
Accurate timing when ticker slows down because of RAF

### ISSUE THREAD

**Issue by MYDIH** [juliangarnier/anime#417]
Hi,

When the tab is blurred, RAF ticker is slowing down, that's expected behavior. On the website I'm building (which is a kind of video game), the server stills updates the "game" at full speed, which means that other animations are firing because of events sent using socket.io. When the tab is focused again, every animations resume, and the page is blowing up ... I tried to pause the animations iterating anime.animations tab on focus event, but weirdly even if the animations are then restarted, they aren't working anymore ... Anyway, using this sort of workaround would be a real pain, being sure to handle each state of the game to restart each animations only once. A real fix here would be to be able to say, my animations should be time accurate, this way even if the ticker is slowing down the animation, on resume, the animations are in the expected state.

I didn't check the code yet, I don't even know if it's possible or already implemented. But I will now

Great lib by the way, was really disappointed by how big GSAP is, anime is a very good replacement

(PS: I could disable the RAF completely I guess, but this would be battery inefficient ... I hope I can find another solution)

**Comment by juliangarnier** [comment]
The ticker is now completely paused when a tab or window is not active.
This should results in more accurate timings.
Feel free to reopen this issue if V3 doesn't solve the problem.
