### ISSUE TITLE
Cannot use 'in' operator to search for 'Array' in undefined

### ISSUE THREAD

**Issue by alexandru-tomescu** [juliangarnier/anime#419]
Hi !

I'm trying to create a web component using Polymer 3 and when i import anime.js using `import 'animejs';` i got the following error message.
```
Uncaught TypeError: Cannot use 'in' operator to search for 'Array' in undefined
    at Object.$jscomp.polyfill (anime.min.js:113)
    at anime.min.js:128
```

**Comment by juliangarnier** [comment]
Should be fixed in V3 since it use a different build method.

**Comment by taysco** [comment]
I'm getting this error in materialize-css package -- would you be able to fix it in there and push an update? Or how can I get this error fixed without an update? I see this error everytime I run my angular app
