### ISSUE TITLE
Negative RGB values

### ISSUE THREAD

**Issue by ngokevin** [juliangarnier/anime#42]
## [test case](http://codepen.io/anon/pen/BzYNwd)

When interpolating a color value, the output of the RGB often goes negative, resulting in invalid values.

**Comment by ngokevin** [comment]
![test](https://cloud.githubusercontent.com/assets/674727/16902805/d1dbbaea-4c1e-11e6-8308-8c888fcd0b46.gif)

**Comment by juliangarnier** [comment]
I'm not sure of the effect you're trying to achieve using an elastic easing function on a color value, but this can not work.
Try using any other easing function (except the `...Back` and `...Elastic` ones), like `linear` or 'EaseOutQuad', and your color transition should works.

**Comment by ngokevin** [comment]
Thanks for the info! I would consider a console warning because `easeOutElastic` is the default easing function.

**Comment by ngokevin** [comment]
I was able to get it working with A-Frame: https://ngokevin.github.io/aframe-animation-component/basic/
