### ISSUE TITLE
Can't animate domAttributes input type="range" 

### ISSUE THREAD

**Issue by fariskas** [juliangarnier/anime#420]
If you try the following pen here, you'll see that it fails to animate the values of a 'range' slider.
However if i remove the type="range", you'll see that it'll animate a normal input field properly.

https://codepen.io/farisk/pen/MqmLjy

version 2.2.0

**Comment by juliangarnier** [comment]
After some tests I found that `setAttribute` doesn't always update the input value. I don't really understand why or when, but using `inputEl.value = 50` always works.

Thanks for pointing this, I'm pretty sure it was working before, maybe something change in the way Chrome handles values on inputs.

I changed the way to detect animation type in V3 that solve this issue.

**Comment by juliangarnier** [comment]
Should be fixed in V3 !
