### ISSUE TITLE
Easing through all morphing steps ?

### ISSUE THREAD

**Issue by NolanCrochot** [juliangarnier/anime#422]
Hi, 

I was trying to simulate a "wind on grass" effect with this wonderful libs. I created a curved line like this : 

``` 
<svg fill="transparent" id="curvedLine" width="128" height="128" viewBox="0 0 400 400">
        <path stroke="black" stroke-width="7" d='M260,297 C260,296 268,78 381,46' />
</svg>
```

After what I tried to animate the curve by adding some stapes to a morphing animation : 

```    
var svgAttributes = anime({
      targets: '#curvedLine path',
      d: [
        { value: 'M260,297 C260,296 260,64 260,0' },
        { value: 'M260,297 C260,296 268,78 139,46' }
      ],
      easing: 'easeInOutQuart',
      direction: 'alternate',
      loop: true,
      duration: 2000
    });
```

Unfortunately, the easing attribute is applied for each stape of the morphing. So I got a blade of grass which begins his movement on the left, stops on the middle, then starts again the movement to the right.

I wonder if it was possible to apply the "easing" and "duration" attribute for the entiere morphing movement (so on the three stapes like it was only one stape), in order to have an continuous movement.

Thank you in advance,

N.

*Edit* : _I managed to have a smooth effect by adding some stapes in order to slow the end of each side of the movement :_ 

```
      d: [
        { value: 'M260,297 C260,296 268,78 393,70' },
        { value: 'M260,297 C260,296 268,78 381,54' },
        { value: 'M260,297 C260,296 260,64 260,0' },
        { value: 'M260,297 C260,296 268,78 139,54' },
        { value: 'M260,297 C260,296 268,78 120,70' },
        { value: 'M260,297 C260,296 268,78 139,54' },
        { value: 'M260,297 C260,296 260,64 260,0' },
        { value: 'M260,297 C260,296 268,78 381,54' },
      ],
```
_However I still think it may exist a better alternative._

**Comment by juliangarnier** [comment]
No sorry, this is not currently possible.
