### ISSUE TITLE
Defect in MORPHING function

### ISSUE THREAD

**Issue by MartDSam** [juliangarnier/anime#423]
The morph function does not work correctly. I tested my svg in many ways, but none works. With morph da grensock it works perfectly, but paying 99 dolars a year is a bit complicated for those who live in Brazil.

greensock Morph:
[Codepen](https://codepen.io/Haisan/pen/LJeNYw)

I tried this way with the animejs:
[Codepen](https://codepen.io/Haisan/pen/jvYqmx)

**Comment by juliangarnier** [comment]
Anime's svg morphing is really basic and doesn't extrapolate missing points and things like that.
Both shapes needs to have the same number of points.

And I have no plan of improving this part in the next releases.

**Comment by MartDSam** [comment]
@juliangarnier Thanks for the reply Julian. I really enjoyed animejs, especially the examples part, it's really good to understand how it works, besides being very compact. A pity this is not a priority, but I understand that this part of morph should be pretty laborious. By chance do you know of any other library that is of the morphSVG level of greensock? I've looked at kutejs, but also only accept simple shapes.

I needed something free because I do not currently have a fixed job. I worked 4 years in a company that made only static websites, no animations and stuff like that. Now I am trying to perfect myself in this part and wanted to choose a library that has a good community and that does not risk being abandoned.
