### ISSUE TITLE
Disable on mobile or breakpoint

### ISSUE THREAD

**Issue by dongepulango** [juliangarnier/anime#429]
Is there a way to disable `anime.js` on mobile or on a set breakpoint? Example I want no animations `500px` and below. Thanks in advance.

**Comment by juliangarnier** [comment]
For help regarding animation techniques or general CSS / JS questions, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
