### ISSUE TITLE
Illustrator export SVG not working with line animation

### ISSUE THREAD

**Issue by Dranak** [juliangarnier/anime#439]
Hello,
I'm a newbie with Anime.js and I have some issues with it and I didn't find any solution.
So I want to animate one text like line animation (from SVG) like in the documentation.
I tried to  use the documentaion example and it's work (only after disable cache in my browser),
but with my SVG it didn't work :( 
The SVG is display ( without the "neon effect") but there is no animation and 0 JS errors in the console. 

There is my SVG in Illustrator with export's option 

[http://www.noelshack.com/2018-43-3-1540402293-exportsvgpng.png](url)

I think it's the export option  cause the issue but I don't know what  to change.
I don't if it's here i need to post my question, but if anyone have some hint to resolve my issue, thanks in advance :)

if you need  other informations to understand my issue tell me.

Dranak

Ps: I'm French so if my English is bad sorry about that :(

**Comment by juliangarnier** [comment]
For help regarding animation techniques or general CSS / JS questions, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
