### ISSUE TITLE
Q: motion path with random offsets

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [juliangarnier/anime#44]
Is there a possibility to add some randomness to the motion path movement? Obviously it is not as easy as in the random examples? Thanks for any help.

**Comment by juliangarnier** [comment]
It's not possible.
The path value uses the path total length, it cannot be random.

**Comment by nicgirault** [comment]
I struggled doing something similar. My need was to start and stop the motion at determined but various places on the path. I ended up altering the path returned by animejs:

```javascript
const adjustedPath = (path, from = 0, to = 1) => {
  const getPointAtLength = (l) => {
    return path.el.getPointAtLength((to - from) * l + from * path.totalLength)
  }
  return {
    ...path,
    el: {...path.el, getPointAtLength},
  }
}

anime({
  targets: '.follow-path',
  translateX: adjustedPath(path('x'), .1, .3),
  translateY: adjustedPath(path('y'), .1, .3),
  rotate: adjustedPath(path('angle'), .1, .3)
})
```
