### ISSUE TITLE
Question: Is it possible to make a image grid rotator with this js?

### ISSUE THREAD

**Issue by abhij89** [juliangarnier/anime#446]
I am looking for a modern solution for: https://tympanus.net/Development/AnimatedResponsiveImageGrid/
where I need to rotate images with animation. The following library is outdated it seems: https://github.com/codrops/AnimatedResponsiveImageGrid

I went through the examples and demos of anime js, but I couldn't find a replacement. Can you please help and suggest if it's possible with this js?

**Comment by juliangarnier** [comment]
For help regarding animation techniques or general CSS / JS questions, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
