### ISSUE TITLE
Avoid adding property if conditional.

### ISSUE THREAD

**Issue by hazzo** [juliangarnier/anime#448]
It's possible to avoid adding a style property if a condition is not meet in a functional property?

Example:

```
anime({
targets: 'div',
width: function (el, i) {
   If(i === 1) {
    return [0, 100]
   }
  }
})
```

This function will work well with the div index 1 but will add to every other div width 0px when it's not necessary.
It's possible to avoid adding the width property to the other divs?

Thanks !! Great library!

**Comment by juliangarnier** [comment]
You can us `anime.get()`to get the original element value instead of '0px'
No, it's probably easier to use a different .css selector than using a function for this.
