### ISSUE TITLE
border-width animation not working in firefox

### ISSUE THREAD

**Issue by Topograph** [juliangarnier/anime#450]
animating a div's border seems not to work on firefox. 

[This example](https://codepen.io/Topograph/pen/qQjgqO) does work in chrome but not in firefox. 

Animating the property with css-transitions however works in firefox, so i guess its a problem with anime.js?

**Comment by gaou-piou** [comment]
add borderWidth: ['0px', '40px'],

**Comment by Topograph** [comment]
thanks! that solved the issue!
