### ISSUE TITLE
Animations to do not fire on iOS Safari 10

### ISSUE THREAD

**Issue by garrettmaring** [juliangarnier/anime#451]
Is there documentation for supported / unsupported browsers or properties for animejs?

I'm animating the `bottom` property of certain elements. This works in Chrome but not in Safari 10.

I was able to get it working by adding explicit units to the values I was animating.

**Comment by juliangarnier** [comment]
For help regarding animation techniques or general CSS / JS questions, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
