### ISSUE TITLE
Bug in minified version

### ISSUE THREAD

**Issue by thimpat** [juliangarnier/anime#453]
Hi, I'm getting an error when I try to use the minified version of animejs from npm or bower:
vue.runtime.esm.js:1713 TypeError: Cannot read property 'arr' of undefined
    at anime.min.js:18
    at anime.min.js:21
    at b (anime.min.js:24)

It does not happen at all on the unminified one. Not a major issue but worth knowing maybe?

**Comment by damusix** [comment]
+1

I get the following when importing:

```
app.js:formatted:3486 Uncaught TypeError: Cannot use 'in' operator to search for 'Array' in undefined
    at Object.$jscomp.polyfill (app.js:formatted:3486)
    at app.js:formatted:3500
    at createCommonjsModule (app.js:formatted:3374)
    at app.js:formatted:3378
    at app.js:formatted:4433
```

<img width="687" alt="screen shot 2018-12-19 at 1 00 34 am" src="https://user-images.githubusercontent.com/4218587/50201799-8ae02a80-0329-11e9-8ea3-9ff88c1d137f.png">

**Comment by juliangarnier** [comment]
This should be fixed in V3.
