### ISSUE TITLE
MathML and anime.js

### ISSUE THREAD

**Issue by baylock** [juliangarnier/anime#454]
Hi,

I'm not a developper nor am I part of the Github community, so I just don't know in which way I have to format my question.

I just discovered anime.js and it feels like the right tool for what I need (animating some web tutorials in 2D).
The problem is that I'm using MathML (part of the HTML5 standard), which uses "math" tags.

```
<math>
	<mrow>
		<msqrt>
			<mrow>
				<msup class="ml4">
					<mi class="letter">b</mi>
                                        <mn>2</mn>
				</msup>
			</mrow>
		</msqrt>   
	</mrow>
</math>
```

```
<script type="text/javascript" src="anime.min.js"></script>
<script>
	anime.timeline({loop: true})
	.add({
		targets: '.ml4 .letter',
	        opacity: [0, 1],
		scale: [0.2, 1],
		duration: 800
	});
</script>
```

When I try to simply animate letters within a math tag (opacity, scale, duration), I get:

If I use anime.min.js (2.0)
- In Firefox a "TypeError: right-hand side of 'in' should be an object, got undefined" error. -> anime.min.js:9:136
- In Safari a "TypeError: a.style is not an Object. (evaluating 'b in a.style')" error. -> "B" -> anime.min.js:9:145

If I use anime.js (2.0)
- In Firefox a "TypeError: right-hand side of 'in' should be an object, got undefined" error. -> anime.min.js:346:5
- In Safari a "TypeError: a.style is not an Object. (evaluating 'b in a.style')" error. ->  "getCSSValue" -> anime.min.js:346

In both cases, the math formula appears just fine but the animation isn't working.
I tried previous versions of anime.js with the same result.

I toyed with the code and the animation comes back + the error message goes away on Firefox and Safari if I get rid of the "math" tag. But then, of course, the math formula is a mess, which is of no help.
But it seems the issue is related to this math tag alone.
I also tried to style, unstyle the math tag and the inner tags but the error remains.

I could understand that this tag is unsupported by animate.js but the animation works just fine and without any error within my Coda2 (web dev software) on Mac, on its own dedicated browser.
So this seems very browser dependent but so far it's the only browser that seems to consider the script as valid.

I haven't found anything on the web that is addressing both anime.js and the MathML so it's hard to say if it's a bug , a request or an error on my part.

Thank you.

**Comment by baylock** [comment]
Problem solved with some workarounds:

1) enclose the element within an "a" tag
2) give the "a" tag a "display:block" attribute and a color.
3) give the parent a "color:transparent" attribute.

https://jsfiddle.net/bt4u23rh/8/

The a tag gives the a.style needed fo the script to work but then the element becomes an inline tag which is a problem with translations and other transformations the element sticks to its original position).
Changing the "a" tag to a block element solves the rigid position problem but then, the element is visually duplicated for whatever reason (two instances of the letter appears on screen). So, I just hide the original element (color:transparent) so that we can only see the second one.

Giving the "a" tag a "display:inline-block" attribute works and doesn't need the color trick because there is only one instance of the element displayed BUT then the element is getting out of the flow and its position is offset, which forces the use of some margins/paddings and imply some other quirks that are way more complicated to manage than just hiding/showing elements on demand like I just did.

**Comment by brandonLi8** [comment]
@brandonLi8
