### ISSUE TITLE
Website has a render issue

### ISSUE THREAD

**Issue by vidjuheffex** [juliangarnier/anime#455]
![screen shot 2018-12-04 at 1 42 04 pm](https://user-images.githubusercontent.com/3157835/49468408-6e40e000-f7ca-11e8-9f78-b484394a37df.png)

might affect confidence in the library to have just an erratic render issue on it's main site.

**Comment by vidjuheffex** [comment]
![image](https://user-images.githubusercontent.com/3157835/50237518-bd6a4180-0382-11e9-9fd3-3081737e922a.png)

![image](https://user-images.githubusercontent.com/3157835/50237560-d83cb600-0382-11e9-933e-98422d08dbc4.png)

**Comment by vidjuheffex** [comment]
Only happens while scrolling/hovering over the site intermittently

**Comment by juliangarnier** [comment]
I just updated the website, can you please check if the problem remains?
Thanks

**Comment by vidjuheffex** [comment]
Looks great, haven't been able to recreate the issue

**Comment by juliangarnier** [comment]
Cool thanks !
