### ISSUE TITLE
Use color name as color

### ISSUE THREAD

**Issue by buckle2000** [juliangarnier/anime#456]
Currently, we cannot use color name as colors.

```js
anime({
  targets: '#el',
  color: 'yellow',
});
```

**Comment by RubenNijhuis** [comment]
Hi Buckle2000,

Even though color names would be a nice feature to have I do strongly advice to use hex or RGB. It is seen as a more professional approach and will help more in the long run as in variables and or changing the color. With RGB it is very easy whereas with named colors it would be very difficult or downright impossible.

**Comment by juliangarnier** [comment]
Thanks for your message, but I have no plans of adding this feature to anime.js
