### ISSUE TITLE
v3 Release date

### ISSUE THREAD

**Issue by gaou-piou** [juliangarnier/anime#457]
Is there any planning for the new version releasing?

**Comment by daniandl** [comment]
I don't wanna say it, but animejs is starting to look abandoned 😢

**Comment by juliangarnier** [comment]
V3 is ready, Just spending way too much time in the new website / docs.
But after months of redoing everything I'm finally happy with the design.
I don't think I'll be able to release v3 before Christmas though, BUT will be out for the new year !

**Comment by daniandl** [comment]
Christmas miracle 🎉

**Comment by jas99** [comment]
Hey @juliangarnier 
What are you focusing on for 3.x?

**Comment by juliangarnier** [comment]
I just updated the website, can you please check if the problem remains?
Thanks

**Comment by geri777** [comment]
Thank you for this awesome library.  Vor V3 could you please ...

- create a V3 changes page, which describes what's new in V3
- create a migration guide for existing projects which want to migrated to V3
- A link to V2 docs on the start page (like Twitter Bootstrap does)

Thank you for all your effort!
