### ISSUE TITLE
Need help with toggle animation

### ISSUE THREAD

**Issue by blisterrabbithutch** [juliangarnier/anime#459]
Hello. 
At first, I apologize for my not perfect English.
i have a little problem with logic of toggle animation. i have written a codepen to reproduct my issue. here it is - https://codepen.io/blisterrabbithutch/pen/EGmdLL

When I click on the button that starts the animation, it works, but when I press it again(second time), it does not start the animation in the reverse direction. If you see a debug, when at the second press, the animation simultaneously works together with the promise. but if you press the third time and all subsequent times, then everything starts working

i have read documentation from here - http://animejs.com/documentation/#reverseAnim but it is not working for me. can you help me with this? Thanks.

**Comment by juliangarnier** [comment]
For help regarding animation techniques or general CSS / JS questions, please use [https://stackoverflow.com/search?q=anime.js](stackoverflow.com).
GitHub issues should only be used for bug report and feature request.
Thanks.
