### ISSUE TITLE
Documentation anime.running count sometimes wrong

### ISSUE THREAD

**Issue by Cristy94** [juliangarnier/anime#466]
If you open this example: https://animejs.com/documentation/#running, it always says there are no instances running.

**LE:** It seems to happen if you switch to a new tab and come back, can't reproduce it exactly for now, it also sometimes shows 4 or 5 and I don't understand why, it seems broken.

![image](https://user-images.githubusercontent.com/1384885/50969550-26a32780-14df-11e9-9b88-9c57ef46bcaf.png)

**Comment by juliangarnier** [comment]
Looks like a bug, but I might just remove this helper since I can't remember the last time I used it..

**Comment by juliangarnier** [comment]
Fixed in v3.1.0!
