### ISSUE TITLE
fill: 'red' won't work. Results in `red0` and shows black

### ISSUE THREAD

**Issue by alvarotrigo** [juliangarnier/anime#469]
**Describe the bug**
When animating the `fill` property of a PATH it generates and invalid color if the color name is used instead of its HEX value.

```javascript
fill: 'red'  // ==> results in `fill="red0"` 
fill: '#00ddff' // ==> works as expected. `fill="#00ddff"`
```

**To Reproduce**
1. Go to https://jsfiddle.net/alvarotrigo/6yev2wc0/31/
2. Click on the 'click' button.
4. See error and the value of the `fill` attribute is invalid

**Expected behavior**
`fill="red"` instead of `fill="red0"`

**Comment by juliangarnier** [comment]
Hey thanks for the issue, but CSS color codes are simply not supported.
And I have no plan of adding support for it since it will almost double the size of the library for no real benefits.
I referenced the CSS color code incompatibility in the docs to reduce confusion.

**Comment by alvarotrigo** [comment]
Right I see. Fair enough.
I'll go for the CSS animation instead.

In case anyone else finds this useful:

```javascript
tl.add({
    d: getPath('M6.3 7.1 L 96.3 4.8 L 93.7 94.3 L 8.5 92.2 Z'),
    complete: function(anim) {
        $('#svg')[0].style.fill = options.sectionsColor[v.sectionIndex];
    }
}, '-=200');
```

Having:

```css
 #svg{
      transition: all 1s ease-out;
}
```
