### ISSUE TITLE
Generating SVG word paths

### ISSUE THREAD

**Issue by anthonychung14** [juliangarnier/anime#47]
I looked online for resources on generating SVG paths via words (love the anime.JS logo animation).

How did you go about generating this SVG? illustrator?

**Comment by juliangarnier** [comment]
I draw the letters myself using Sketch, but Illustrator or any other vector based drawing tool should work!

**Comment by skoll1** [comment]
<svg style="width:100vw;height:90vh" id="svg">
        <text x="10%" y="35%" class="text">I</text>
        <text x="30%" y="35%" class="text">❤</text>
        <text x="60%" y="35%" class="text">U</text>      
</svg>
anime({
                targets: '.text',
                strokeDashoffset: [anime.setDashoffset, 0],
                easing: 'easeInOutSine',
                duration: 1500,
                delay: function(el, i) { return i * 250 },
                direction: 'alternate',
                loop: true
                });
hello. I want to support text strokes in this way, will I support this way of writing in the future
