### ISSUE TITLE
Stagger Axis in the documentation

### ISSUE THREAD

**Issue by TomS-** [juliangarnier/anime#470]
**Is your feature request related to a problem? Please describe.**
https://codepen.io/juliangarnier/pen/MZXQNV?editors=0010

Axis is used here, it looks like a cool feature but it isn't really shown in the documentation anywhere. From what I can tell is it knows the location of which the animation starts and moves away from the origin? 

**Describe the solution you'd like**
Just a bit of an explanation of what axis does and it used in isolation

**Comment by juliangarnier** [comment]
Yes nice catch, added to the docs! https://animejs.com/documentation/#gridAxisStaggering
