### ISSUE TITLE
Change speed during animation

### ISSUE THREAD

**Issue by dka09** [juliangarnier/anime#48]
Is it possible to change the speed of the animation while it's already playing without having to remove the animation and re-animate the item with a different duration? Playing with `anime.speed` setting only applies this to new animations and not currently playing ones.

**Comment by juliangarnier** [comment]
Nope this is not possible.

**Comment by j0hnm4r5** [comment]
I ran into the issue today, albeit with wanting to change the playback speed of a keyframe animation while it is playing — is this still not possible as of 3.0.1?

**Comment by plagasul** [comment]
I would also like to know if the new version would allow, even if with a workaround, to change the perceived speed (duration?) of the animation while it is running. Doing that in plain CSS keyframe animations result in the animated property jumping from one value to another abruptly. Thank you

**Comment by HMH-CGZ-Shubhrit-Dhanawat** [comment]
I have a similar issue where the user can change the speed of the motion path object through button clicks. I'm able to change the speed but the animation starts from the beginning. Any way of fixing it? Thanks.
