### ISSUE TITLE
Opacity counts to long when animation is finished 

### ISSUE THREAD

**Issue by MariuzM** [juliangarnier/anime#482]
When running this code i have noticed that after opacity went from 0 to 1 the Dev Tools still shows Opacity counting causing high CPU usage. The count in Dev tools does count till 10 seconds and then stops but the actual (visual) fade in to 1 takes around 2 seconds. 

I'm on v3 + Chrome

```
document.addEventListener('DOMContentLoaded', () => {
	anime({
		targets: '.title',
		delay: 700,
		opacity: 1,
		duration: 10000,
	})
})
```

`	<div class="title">Test</div>
`

**Comment by juliangarnier** [comment]
The timing is good, but the easing applied to the opacity value will make the element appears more or less faster.

Try using the [`'linear'`](https://animejs.com/documentation/#linearEasing) easing.
