### ISSUE TITLE
Hover-Effect

### ISSUE THREAD

**Issue by juergengenser** [juliangarnier/anime#49]
Hi,

I'm trying to achieve a hover animation with Anime.js but this doesn't seem to work as intended. I've defined an animation with direction alternate and I'm trying to apply it to a hover function - at least this is how I thought it should work. but the animation seems to trigger multiple times, making the effect useless.

I've made a Codepen here: http://codepen.io/juergengenser/pen/XKzoQO

anything I'm doing wrong here? 

thanks,
Jürgen

**Comment by dka09** [comment]
Not sure what the effect you are going for is. What are you expecting the arrow to do?

**Comment by juergengenser** [comment]
it should behave like that (done with GSAP): http://codepen.io/juergengenser/pen/akYAGX

**Comment by juliangarnier** [comment]
Try this:

```
//var path = anime.path('#circle');
var logo_anim_in = anime({
  targets: ['#arrow_group'],
  rotate: 10,
  duration: 400,
  autoplay: false,
  easing: 'easeInOutSine',
  loop: false
});

function over(){
  logo_anim_in.play({
    rotate: 10,
  });
}

function out(){
  logo_anim_in.play({
    rotate: 0,
  });
}

$('#logo').hover(over, out);
```

**Comment by rasteiner** [comment]
How would we do this in the current version? `instance.play()` no longer takes any arguments :(

**Comment by rasteiner** [comment]
nevermind... it was too KISS to be understood... 

just create new instances and anime will figure it out...

**Comment by juliangarnier** [comment]
Two ways :

using one instance and `reverse()` http://codepen.io/juliangarnier/pen/NjXONp

or creating a new instance each time (give you more control on your animation) http://codepen.io/juliangarnier/pen/aWERWX
