### ISSUE TITLE
Play forward and backward

### ISSUE THREAD

**Issue by metalfox6383** [juliangarnier/anime#491]
Hi:

I love this library. It's GREAT!!! Thanks for the new update. God is with you.

I'd like two new functions:

1. timelineObject.playForward()
Similar to:
timelineObject.seek(0);
timelineObject.play();

2. timelineObject.playBackward()
Similar to:
timelineObject.seek(timelineObject.duration);
timelineObject.reverse();
timelineObject.play();

Currently I add this functions manually.

Greetings.

**Comment by juliangarnier** [comment]
I think it's too specific to be added to the API, but you can What about :

````
forwardButton.onclick = function() {
  tl.direction = "normal";
  tl.restart();
}

backwardButton.onclick = function() {
  tl.direction = "reverse";
  tl.restart();
}
````

**Comment by metalfox6383** [comment]
Hey! That help. I did not know it. The properties can change later of object created. Thanks.
