### ISSUE TITLE
Do we need Chinese translation of the document?

### ISSUE THREAD

**Issue by mcdongWang** [juliangarnier/anime#492]
As the title says, if we need it
I can provide some help

**Comment by juliangarnier** [comment]
Hey thanks! But I have no proper way to have both translations on the same document setup right now.
I use really a basic, pure HTML / JS website, and adding translation will be a pain.
But if I change the website in the future I might be interested !

**Comment by bofeiw** [comment]
A year has passed, do you need to add some translations? Users are growing. @juliangarnier
