### ISSUE TITLE
Allow easing to accept function(el, index, total)

### ISSUE THREAD

**Issue by Tyriar** [juliangarnier/anime#50]
In order to create the animation I'm going for using a single `anime` call (and the goodness that comes with that in regards to playback controls simplicity), I need to use different easing functions for different objects.

I'd like this to be possible:

```js
var myAnimation = anime({
  targets: ['.blue', '.green'],
  translateX: '13rem',
  rotate: 180,
  easing: function (el, index) {
    return index === 0 ? 'linear' : 'easeOutElastic';
  },
  borderRadius: '8px',
  duration: 2000,
  loop: true
});
```

**Comment by juliangarnier** [comment]
Interesting, I'll try to look into this this week end.

**Comment by Tyriar** [comment]
I think I may be trying to use the library to do something it wasn't designed to do; Animating multiple elements over a period of time using a single call to `anime`. I just realised that it's not possible to have multiple elements in `targets` being the same and animating the same property. I want to accomplish something similar to the anime.js logo animation [here](http://codepen.io/juliangarnier/pen/xOgyjB), but also provide playback controls.

I think I'm going to instead use an array of animations and use the longest one to check progress. Feel free to close the PR if you don't see it being useful to others.
