### ISSUE TITLE
seek documentation and actual working not matching

### ISSUE THREAD

**Issue by mubaidr** [juliangarnier/anime#500]
**Describe the bug**
Documentation and behavior is different for method `seek`

**To Reproduce**
https://codepen.io/mubaidr/pen/maNomb?editors=1111

**Expected behavior**
Documentation states that seek accepts time in `ms` where as it actually works like %

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 70

**Additional context**
https://animejs.com/documentation/#seekAnim

**Comment by juliangarnier** [comment]
`seek` works with `ms`.
Your CodePen example uses anime.js v1.1.2.
