### ISSUE TITLE
Animate backgroundSize

### ISSUE THREAD

**Issue by bitroost** [juliangarnier/anime#502]
**Is your feature request related to a problem? Please describe.**
Animating individual backgroundSize width and height values doesn't work but is sometimes needed if for example the width or height value needs to stay at 'auto'.

**Describe the solution you'd like**
```
myanim.add({
    targets: '#bgimage',
    backgroundSize: ['auto 100%', 'auto 200%']
});
```

**Describe alternatives you've considered**

As a workaround i could create an attribute and animate on update:
```
<div id="bgimage" data-bgy="100"></div>

myanim.add({
    targets: '#bgimage',
    "data-bgy": [100, 200],
    update: (anim) => {
        let bgy = anim.animatables[0].target.getAttribute('data-bgy');
        anim.animatables[0].target.style.backgroundSize = `auto ${bgy}%`;
        console.log(bgy);
    }
});
```

**Comment by juliangarnier** [comment]
Fixed in 3.1.0 !
