### ISSUE TITLE
Question about tools

### ISSUE THREAD

**Issue by Charuru** [juliangarnier/anime#505]
What do you guys use to create animejs animations? While you can write everything by hand just from your imagination it doesn't seem like the ideal process. You should have the animation already plotted out with a visual timeline tool, no? What tools do you use? Sketch with anima? Framerjs? Is there something that can export directly into animejs?

**Comment by kn0wn** [comment]
The most popular that I have seen designers using currently is either Figma or Framer. In terms of exporting directly to animejs - we're open to ideas and contributions from these products for possible integrations.

Closing this for now.
