### ISSUE TITLE
It's con't working with scale sometimes.

### ISSUE THREAD

**Issue by fangxianzheng** [juliangarnier/anime#52]
`<!DOCTYPE html>`
`<html lang="en">`
`<head>`
`    <meta charset="UTF-8">`
`    <title>Title</title>`
`    <script src="dynamics.js"></script>`
`    <script src="anime.js"></script>`
`    <style>`
`        div{`
`            width:200px;`
`            height:200px;`
`            margin-top:20px;`
`            margin-left:30px;`
`            background-color:#afa;`
`            transform:scale(0.1);`
`        }`
`    </style>`
`</head>`
`<body>`

`    <div id="test1"></div>`
`    <div id="test2"></div>`

`<script>`
`    anime({`
`        targets:'#test1',`
`        scale:1,`
`        duration: 5000`
`    });`

`    var test2 = document.getElementById('test2')`
`    dynamics.animate(test2,{`
`        scale:1,`
`        duration: 5000`
`    })`
`</script>`
`</body>`
`</html>`
It con't work ,But dynamics can do! please help me    \(•ㅂ•)/♥

**Comment by juliangarnier** [comment]
Use `scale: [.1, 1]` instead of `scale: 1`

**Comment by fangxianzheng** [comment]
thx , this is very good lib . I can't belive it only 634 line . Sorry , i poor in english (￣▽￣")
