### ISSUE TITLE
ERROR TypeError: animejs__WEBPACK_IMPORTED_MODULE_1__ is not a function

### ISSUE THREAD

**Issue by glemiere** [juliangarnier/anime#527]
**Describe the bug**
Using the version 3 of this library with TypeScript and WebPack, the console throws the following error:
`ERROR TypeError: animejs__WEBPACK_IMPORTED_MODULE_1__ is not a function`

I'm not exactly sure if the problem comes from the new version of this library, or if the type definition are outdated (@types/animejs).

**To Reproduce**
1. install angular (as it has TS enabled it's the fastest way to get to it) and run `ng new myProject`
2. Install animejs and the type definition (`@types/animejs`) using npm
3. Use the anime function in any component (`import * as anime from 'animejs';`)

**Expected behavior**
See animation without error.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: Latest

**Comment by christopher-harris** [comment]
I am seeing the same exact error....haven't been able to solve this.

**Comment by christopher-harris** [comment]
I was able to get rid of the error with Angular 7 by rolling anime.js back to version 2.2.0.

**Comment by glemiere** [comment]
@christopher-harris indeed, that's why I said 

> I'm not exactly sure if the problem comes from the new version of this library, or if the type definition are outdated (@types/animejs).

**Comment by ashhitch** [comment]
I had this issue too, to fix its I had to use the following import: `import anime from 'animejs/lib/anime.es';`

**Comment by NOPROD** [comment]
npm i animejs 
npm i @types/animejs
import anime from 'animejs/lib/anime.es';

use directly anime, work fine @ashhitch  +1

**Comment by snoozeDev** [comment]
Worked for me too ! +1 @ashhitch 😄

**Comment by defmeta** [comment]
Thanks, 
import anime from 'animejs/lib/anime.es';
works for me too.

**Comment by juliangarnier** [comment]
Fixed! Thanks

**Comment by subhamdas226** [comment]
> #527
> npm i animejs
> npm i @types/animejs
> import anime from 'animejs/lib/anime.es';
> 
> use directly anime, work fine on angular 7 @ashhitch +1

Thanks, working fine for me too
