### ISSUE TITLE
anime.path() results flipped and rotated?

### ISSUE THREAD

**Issue by Committing** [juliangarnier/anime#530]
**Describe the bug**
SVG Path follow path is incorrect. The path is flipped horizontally and rotated 180 degrees from the original SVG.

**To Reproduce**
1. Go to https://jsfiddle.net/8wvort9k/
2. Watch the red square - the path is the wrong way around from a simple path line

**Expected behavior**
A clear and concise path along the svg 

**Screenshots && Evidence**
- https://jsfiddle.net/8wvort9k/1/
- https://i.gyazo.com/f300536791a65d3364bb7057de630c52.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 71.0.3578.98

**Comment by alexchantastic** [comment]
You'll probably need to recreate your path in the correct direction and orientation.

**Comment by Committing** [comment]
Hi, sorry I forgot I made this issue. The problem was that the program I exported the SVG from flipped the image vertically and horizontally. I removed the attributes within the SVG and all working fine.

Loving anime.js, thanks!
