### ISSUE TITLE
 anime.stagger is not a function

### ISSUE THREAD

**Issue by jagadishg1** [juliangarnier/anime#543]
` anime({
        targets: '.anim',
        translateX: 270,
        delay:anime.stagger(100) // increase delay by 100ms for each elements.
      });`
It is throwing error 

> Uncaught TypeError: anime.stagger is not a function
    at HTMLDocument.<anonymous> (design.js:6)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)

**Comment by jagadishg1** [comment]
Solved , i was using old version of anime.js

**Comment by jrandria** [comment]
For those who need to use stagger with angular:
 Step 1: npm install animejs --save
 Step2: import anime from 'animejs'; not import * as anime from 'animejs'
**Dont install**  @types/animejs  it is outdated.
Step3: 
  ngAfterViewInit(): void {
    anime({
      targets: '.basic-staggering-demo .el',
      translateX: [-250, 10],
      delay: anime.stagger(100, {start: 500}) // increase delay by 100ms for each elements.
    });
  }
