### ISSUE TITLE
3.x doesn't support parallel morphing the same way as in v2.x ?

### ISSUE THREAD

**Issue by baermathias** [juliangarnier/anime#559]
**Describe the bug**
The animation of multiple triangles doesn't perform in parallel as in version <= 3.x. Every step runs sequentially and waits until the former step has finished.

**To Reproduce**
1. Open this link to see the original animation: https://codepen.io/ainalem/pen/VWJRav
2. Now open JavaScript Settings
3. Paste this link: https://unpkg.com/animejs@3.0.1/lib/anime.js
4. See the error

**Expected behavior**
I am expecting the same bevahiour as with animejs <= v3.x.x

I have also tried to change `offset` into `timelineOffset` according to the API changes in v3.x, but it still doesn't work. What else has to be changed?

**Comment by p-vogt** [comment]
Use `https://unpkg.com/animejs@3.0.1/lib/anime.min.js` to get rid of the error.
Instead of using `timelineOffset` do the following:

```
  timeline
  .add({
    targets: path.id,
    d: {
      value: path.d,
      duration: 1000,
      easing: 'easeInOutQuad'
    }
  }, 1000 + 10 * index); // <----
```
See [docs](https://animejs.com/documentation/#timelineOffsets).

Hope this helps.

**Comment by kn0wn** [comment]
Hi @baermathias, @p-vogt's solution works on my side. If you are still having an issue please re-create the issue report.
