### ISSUE TITLE
Animating svg `x`

### ISSUE THREAD

**Issue by alexzaworski** [juliangarnier/anime#56]
Hey there.

Is there a way to animate the `x`/`y` attributes on svg rects/patterns? I tinkered with it for a bit but I only managed to add `style="x: ... "` which of course doesn't work.

**Comment by juliangarnier** [comment]
Did you try animating the x and y values?
Works perfectly on rect.

````
var myAnimation = anime({
  targets: 'rect',
  x: 100,
  y: 200,
  duration: 2000,
  loop: true
});
````

http://codepen.io/juliangarnier/pen/qNQEGd

**Comment by alexzaworski** [comment]
Here's a reduced test case showing the problem I'm having:
http://codepen.io/alexzaworski/pen/e27ec9e62aa960ffcd4ae36add78d8eb/

It looks like the issue could be the `pattern` element, which seems to only support `x` as an attribute and not as a css property. I thought I had tested on a plain old `rect` but I guess not.
