### ISSUE TITLE
Is it possible to reset all the animated properties to beginning state after completion?

### ISSUE THREAD

**Issue by FateRiddle** [juliangarnier/anime#565]
**Is your feature request related to a problem? Please describe.**
I wanna do a page flip on my **Page** component, but after the animation I want **Page** to return to its initial state, so I can reuse it. 

There're so many cases imaginable, that you want to play the animation, then have the target return to its initial state.

Is it possible to do so with anime.js? I couldn't find the api for it. Only way I can think of is to reverse the animation played in 0 ms.

**Comment by alandickinson** [comment]
You could use the `complete` callback to reset your object's parameters to their initial values using `anime.set`

Something like this:

```javascript
anime({
  targets: '.box',
  scale: 1.5,
  complete: function() {
    anime.set({
      targets: '.box',
      scale: 1.0
    });
  }
});
```

**Comment by FateRiddle** [comment]
@alandickinson I find a better way. Using `timeline.seek(0)`
