### ISSUE TITLE
Can we turn off elasticity? I have it set to 0 and I still see it happening on 'linear' animations...

### ISSUE THREAD

**Issue by SeanJM** [juliangarnier/anime#57]
Can we turn off elasticity? I have it set to 0 and I still see it happening on 'linear' animations...

**Comment by juliangarnier** [comment]
Can you provide a code example?
`elasticity` only affects elastic easings functions.

**Comment by SeanJM** [comment]
![theGif](http://i.imgur.com/BJUwqgX.gif)

```javascript
    anime({
      targets : logo.node,
      delay : 500,
      duration : 1200,
      bottom : [600, 0],
      elasticity : 0,
      ease : 'linear',
    });
```

It's that secondary action, you know what I mean?

**Comment by alexchantastic** [comment]
`ease: 'linear'` should be `easing: 'linear'`.

**Comment by SeanJM** [comment]
Ah, so the problem is that I'm ignorant. Got it, easy fix.
