### ISSUE TITLE
Replacing previous version of anime.js with the latest breaks all animations

### ISSUE THREAD

**Issue by gentle-media** [juliangarnier/anime#572]
I've noticed the new version of anime.js and I'm particularly interested in the new staggering option, but replacing the previous version with the latest on my WIP site breaks all my animations.
Had anyone else this issue? Is there a huge change compared to the previous version?

**Comment by slavanossar** [comment]
Major version jumps (e.g. 2.x to 3.x) are used to indicate that there are incompatible changes to the API. You can read more about semantic versioning [here](https://semver.org/).

**Comment by gentle-media** [comment]
Thanks @slavanossar! That must be it then :) I've sticked to the old version, but will use in new projects the latest version.
