### ISSUE TITLE
here is a bug

### ISSUE THREAD

**Issue by zwz27837644** [juliangarnier/anime#575]
when i use like this 
anime({
            targets: this.dv,
            top:[0,400],
            easing: 'easeInQuad',
            delay:0,
            duration: 5000
            });
            anime({
            targets: this.dv,
            top:[400,250],
            easing: 'easeInQuad',
            delay:5000,
            duration: 2000
            });
here is a bug
at setAnimationsProgress function
i think you need to add a line code
if(tween.delay > insTime)return;    behind var tween = tweens[tweenLength];

**Comment by juliangarnier** [comment]
Sorry but can you provide a more comprehensible example of your problem?
Thanks

**Comment by kn0wn** [comment]
Hi @zwz27837644, I'm going to close this for now, if you have the issue again, please create a new issue.
