### ISSUE TITLE
elasticity not woking on Anime 3

### ISSUE THREAD

**Issue by Haojen** [juliangarnier/anime#578]
Anime does a great job, and I use it with my team. However, after upgrading to the anime 3 version, we found that the elasticity attribute has failed. I did not find a solution after querying the document. Can you help me see this problem?

`Anime({
        targets: 'someEl',
        opacity: 1,
        translateY: [-100, 0],
        delay: 1000,
        elasticity: 100, // Not Working
      })
`

**Comment by LukeCarlThompson** [comment]
The properties have changed for elastic easing and now there is a spring easing too.

Check the docs.

https://animejs.com/documentation/#elasticEasing
