### ISSUE TITLE
Starting an animation at a seek point?

### ISSUE THREAD

**Issue by alexchantastic** [juliangarnier/anime#59]
Is it possible to start an animation at a certain seek point? I was thinking I could use the `.seek()` method for this, but I tried it on a motion path animation and it didn't seem to work. I'm not sure if this is the right way to approach it.

What I'm trying to do is stagger elements being animated along the same motion path. I initially tried to use `delay` to stagger, but that caused them to show at the first point, wait, and then animate.

**Comment by juliangarnier** [comment]
I tried to seek and start an animation with a motion path, and seems to works fine.
Here is an example: http://codepen.io/juliangarnier/pen/ZOkmzr

**Comment by alexchantastic** [comment]
Must've been a bug on my end. Thanks for following up! 👍
