### ISSUE TITLE
Version 3.x on CDN/Codepen

### ISSUE THREAD

**Issue by guettli** [juliangarnier/anime#595]
Hi,

Is there are a reason why the 3.x version is not available on codePen or cdnjs.com?

Thank you very much for the lib and the nice docs.

**Comment by web2033** [comment]
Alternative
https://cdn.jsdelivr.net/npm/animejs@3.1.0/lib/anime.min.js

**Comment by juliangarnier** [comment]
Waiting for the people at cdnjs to update the path... https://github.com/cdnjs/cdnjs/issues/13255 https://github.com/cdnjs/cdnjs/pull/13256

**Comment by kn0wn** [comment]
cdnjs has been updated [https://cdnjs.com/libraries/animejs](https://cdnjs.com/libraries/animejs)
