### ISSUE TITLE
Global Pause Feature

### ISSUE THREAD

**Issue by butlericjoey** [juliangarnier/anime#598]
If this already exists, I'm sorry, but I could not find it in the documentation.

I would like to request for a function that would allow you to instantly pause all existing animations, such as anime.pauseAll(), which can either work as a toggle or just as a pause functionality, as well as anime.resumeAll(), which will conversely instantly resume all existing animations.

**Comment by web2033** [comment]
I think you can pause all using
https://animejs.com/documentation/#running

`anime.running.forEach(a => a.pause());`

**Comment by butlericjoey** [comment]
@web2033 ahh, okay. Thank you!

**Comment by butlericjoey** [comment]
@web2033 oh, but what about resuming? It seems like they're moved away from anime.running when you pause them?
