### ISSUE TITLE
How to use Complete event

### ISSUE THREAD

**Issue by arnoudcommandeur** [juliangarnier/anime#601]
Hi, I try to use the Complete event after running multiple timelines.

When I use: 

```
            anime({
                complete: function(anim) {
                    animeCompleted();
                }
            });
```
the event is triggered just before the 1st timeline instead of calling the event after the last timeline. Anyone an idea how to solve this?

Thanks!

**Comment by arnoudcommandeur** [comment]
Hi @starql, thanks. I will try this.

**Comment by kn0wn** [comment]
@arnoudcommandeur Did @starql comment this fix your issue?

**Comment by kn0wn** [comment]
I'm going to close this for now.
