### ISSUE TITLE
Interest in Web Animations API port ?

### ISSUE THREAD

**Issue by laurentperez** [juliangarnier/anime#602]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a question.
https://caniuse.com/#feat=web-animation is maturing, latest Safari and IE (Blink) do support it, Chrome and Firefox have some work to do with playback controls

@juliangarnier do you have plans/experimental branch to support WAAPI by porting the code to KeyFrameEffects ?

**Comment by kn0wn** [comment]
Hi @laurentperez, thanks for raising an issue about this. It's a very interesting API but I think it still needs to more supported before any thoughts are on integrating this to the main branch. But you are right an experimental branch is a good idea.

**Comment by Momijiichigo** [comment]
Hi!
[many browsers support the Web Animation API](https://caniuse.com/web-animation) now.
Any updates to this? thx!
