### ISSUE TITLE
Direction for width animations

### ISSUE THREAD

**Issue by dangelion** [juliangarnier/anime#603]
Hi
I'm animating the `width` of an element but I can't specify the direction. 

```
anime({
  targets: '.el',
  width: "0%",
  duration: 1300,
});
```

Example: 
I want to animate an element from `width:100% `to `width:0%` **from left to right** but by default the animation is from right to left. Then, I need to specify the direction from left to right.
Is it possible?

**Comment by dangelion** [comment]
Any news on this? I think it's a very important feature

**Comment by dangelion** [comment]
No one can help? Any workaround to achieve that?

**Comment by juliangarnier** [comment]
This is a CSS related question, not anime.js.

In order to get the animation from left to right, the element should be aligned to the right (flexbox?)

**Comment by dangelion** [comment]
Thanks for the input, I solved changing alignment from `begin` callback:

```
...
.add({
  targets: '.js-transition-el',
  width: '0%',
  translateZ: 0,
  easing: 'easeInOutExpo',
  duration: 2000,
  begin: () => {
    // Change align of the element to right
    $('.js-transition-el').css({
      'right': 0,
      'left': 'initial'
    })
  },
})
...
```
