### ISSUE TITLE
Overlap Div with SVG path

### ISSUE THREAD

**Issue by Uranbold** [juliangarnier/anime#607]
Hello,

Quick question. How can i set the z-index value on the the Moving dots. Please check the Example on this.
https://codepen.io/Uranbold/pen/VwZMLgK

Thanks.

**Comment by Uranbold** [comment]
You saw the Moving dots overlapping the white road on the above example.

**Comment by kn0wn** [comment]
Hi @Uranbold, unfortunately this isn't something that is in scope for anime.js
