### ISSUE TITLE
Support for queue

### ISSUE THREAD

**Issue by cho-is** [juliangarnier/anime#61]
Really like it because is lightweight and would be great to support queue.

In addition, transition does not continue were it was if you fire animation twice, but resets?

**Comment by juliangarnier** [comment]
I'm not sure to understand what you mean by firing the animation twice.
But, if you need to pause and then continue the animation were it stopped, use the playback API: http://codepen.io/juliangarnier/pen/RRKpgq

**Comment by cho-is** [comment]
Thanks for your answer. I mean for instance, for transitions that run between states and depends on user clicks. 

Just wondering would be nice to support something like VelocityJS where you got your `queue` boolean. But anyways, apart from this, Velocity does not interrupt animations if you give a different property value when the element has not finished the animation. 

As I said, I really like the fact that Anime is lightweight.

**Comment by juliangarnier** [comment]
Ok I see, but I don't plan to implement this anytime soon.
This looks too specific for Anime, and I really want to keep the library super lightweight.
