### ISSUE TITLE
PARAMETERS THAT CAN BE INHERITED

### ISSUE THREAD

**Issue by web2033** [juliangarnier/anime#613]
Seems like docs do not have a full list of what can be inherited in a timeline.

Example in docs include these:

```
easing: 'easeOutExpo',
direction: 'alternate',
loop: true
```

but they are not in the table:

![2019-09-14_223858](https://user-images.githubusercontent.com/11320080/64913003-ae14fa80-d740-11e9-85fd-ac1c652e3a29.jpg)

I'm trying this and not sure whether it should work or not according to docs:

`opacity: {
        value: [0, 1],
        easing: 'linear'
      }`

**Comment by juliangarnier** [comment]
Thanks for pointing this out, I forgot the easing parameter in the docs.
I fixed that and hopefully made this section a little bit clearer.
