### ISSUE TITLE
What about JS Objects?

### ISSUE THREAD

**Issue by khanh2003** [juliangarnier/anime#62]
I want to ANIMATE JS OBJECTS like this:
from {br: 1, brr: 2}
to {br: 1000, brr: 10034}
Is there any way? I can't find it in README

**Comment by juliangarnier** [comment]
Yes you are I should add a simple example in the documentation.

Simply use your object as a target, and add the properties like any other properties:

```
var myObject = {br: 1, brr: 2 }

anime({
  targets: myObject,
  br: 1000,
  brr: 10034,
  round: true, // optionally you can round the values
  easing: 'linear'
});
```

Live example here:
http://codepen.io/juliangarnier/pen/wWbYjK

**Comment by khanh2003** [comment]
Wow, thanks!
I'm going to use it for my project.
Also, what's your email? I'll give you a GitHub link of my project when I
finish it.

**Comment by matthiasg** [comment]
@juliangarnier the naming is not quite clear to me. What about properties that have a naming conflict with the properties accepted by anime ? Also I could not find a list of all 'reserved' properties already used by AnimeJs (at least not in the documentation). Your documentation is outstanding to understand how to use it, but it is missing a short reference of all properties I think.
