### ISSUE TITLE
Blinking issue, second round

### ISSUE THREAD

**Issue by MYDIH** [juliangarnier/anime#623]
**Describe the bug**
This issue is just a reopen of #512 . The problem is still there on v3.1.0.

**To Reproduce**
Create an animation : 

```js
anime.timeline({
  autoplay: false,
  duration: 800
}).add({
  targets: icon,
  translateY: '-50px'
}).add({
  targets: pitch,
  opacity: 1
})
```

Reverse it (for instance, onHover):

```js
if (!this.hoverAnimation.reversed) {
  // this.hoverAnimation.completed = false -> This workaround is indeed working
  this.hoverAnimation.reverse()
}
this.hoverAnimation.play()
```
**Expected behavior**
The animation is reversing smoothly

**Current behavior**
The animation blinks on the first reversed frame

**Desktop (please complete the following information):**
 - OS: [linux]
 - Browser [chromium]
 - Version  [77.0.3865.120]

**Additional context**
As you can see in my setup, I use a timeline, I don't think it was the case in the closed bug. I'm also using Vue, if it's important.

Thanks

**Comment by Cedric-ruiu** [comment]
+1

**Comment by yymmm9** [comment]
@MYDIH

Hi, I've reproduced it on jsfiddle with no problems, see the following link.

[https://jsfiddle.net/exvcmjt5/](url)

**Comment by kn0wn** [comment]
@MYDIH Does the solution @yymmm9 provided solve your use case?

**Comment by Silver-Von** [comment]
> @MYDIH
> 
> Hi, I've reproduced it on jsfiddle with no problems, see the following link.
> 
> [https://jsfiddle.net/d0qbfxkj/](url)

It works! Thank you for this solution. I just add `this.animation.completed = this.animation.reversed ? false : true;` and the animation runs like a charm. 


[https://codepen.io/silver-von/pen/yLNdwQb](url)
