### ISSUE TITLE
easing: 'steps(n)' is much faster in first step ?

### ISSUE THREAD

**Issue by littlee** [juliangarnier/anime#625]
**Describe the bug**
when using steps easing, the first step always takes less time to finish, compare to every other steps.

**To Reproduce**
https://codesandbox.io/s/hopeful-austin-fuvv6
open this demo, and it looks like the first step (from 1 to 2) takes less time than other steps.

**Expected behavior**
every step should take same time to finish.

**Desktop (please complete the following information):**
 - OS:  macOS Catalina
 - Browser: Google Chrome 78
 - Version:  animejs@3.1.0

**Comment by mracette** [comment]
fixed here: https://github.com/juliangarnier/anime/pull/670

**Comment by kn0wn** [comment]
@mracette Amazing, thanks for the contribution, will close this once it has been tested/merged

**Comment by kn0wn** [comment]
This is fixed in v3.2.0
