### ISSUE TITLE
Importance of sequence of anime's argument attributes

### ISSUE THREAD

**Issue by mkermani144** [juliangarnier/anime#63]
I have found something in the library that is not mentioned in the documentation, and I think is somehow important: 
__The sequence of anime's argument attributes affects animation__, that is, for example, if you use `scale` property before `translate` property, you may get different result than if use `translateX` before `scale` property. Live comparison here:
[1. `scale` before `translate`](http://codepen.io/mkermani144/full/NAVQpO/)
[2. `scale` after `translate`](http://codepen.io/mkermani144/full/Pzgpbx/)
However this is not a bug related to this library, but I recommend this tip to be mentioned.

**Comment by juliangarnier** [comment]
This is the expected behaviour of the CSS transforms, I don't see the need of adding this to the documentations.
If you were developing the animation using pure CSS, the problem would have been the same.
