### ISSUE TITLE
CSS hover effects stop working in CHROME 

### ISSUE THREAD

**Issue by Timme777** [juliangarnier/anime#630]
All my css hover effects stop working in Chrome while my animation is playing. I'm only doing a scale transform and my animation is on loop. The version of Chrome that I'm using is Version 78.0.3904.108.

I don't have this issue in FF and Safari.

(I work on a Macbook Pro)

**Comment by kn0wn** [comment]
Hi @Timme777, can you post this example in a codesandbox and I will take a look.

**Comment by kn0wn** [comment]
Hi @Timme777, I'm going to close this for now as it's been inactive for a while. Please re-open another issue if you are still getting the output
