### ISSUE TITLE
How many fps AnimeJs Works?

### ISSUE THREAD

**Issue by Damien2k9** [juliangarnier/anime#631]
**Is your feature request related to a problem? Please describe.**
Hi guys

It is not a problem and not a request, but a doubt that I have for some time.
How many frames per second does Anime JS work with?
 Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TomS-** [comment]
It targets 60FPS, but quality of code and number of elements animating can effect FPS.

**Comment by kn0wn** [comment]
As @TomS- stated, anime.js tends to run at 60FPS depending on code quality. If you follow standard css animation best practices you'll be able to achieve this. Smashing magazine has a really interesting [article](https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/) on it
