### ISSUE TITLE
Anime js not working with used inside a Class in es6 javascript

### ISSUE THREAD

**Issue by TheComputerM** [juliangarnier/anime#632]
Anime js is not working when I use it inside a class such as:
```js
class Modal{
    constructor(){ ... }
    _open () {
        anime({
	        targets: this.el,
		opacity: 1,
		easing: "easeOutQuad",
		duration: this.settings.animInDuration,
		begin: function () {
			this.isAnimationDone = false;
			this.isOpen = true;
			this.el.style.display = "none";
		},
		complete: function() {
			this.isAnimationDone = true;
			this.el.style.display = "block";
	        }
	});
    }
    _addEventHandlers (){
        element.addEventListener('click', this._open);
    }
}
```

When element is click it shows an error 
`
Uncaught TypeError: Cannot read property 'animInDuration' of undefined
`

The properties such as `this.el` are properly defined, when I replace this.* with proper test strings it works properly but when using this keyword inside `anime({})` it throws an error saying it is undefined.

## Environment
I an using Babel v7.4.0 and rollup to build my modules.

**Desktop**
 - OS: Windows x64
 - Browser Chrome

**Comment by kn0wn** [comment]
Hi @TheComputerM, Are you still having this issue? From what I can see, it's the `settings` that is undefined.

**Comment by TheComputerM** [comment]
No, I am no longer having this problem. And sorry as it was a problem with me and not anime js.
When I attached this function to an event listener, I forgot to bind `this` to the function, I later forgot to close this issue.
