### ISSUE TITLE
support for 'transform matrix' value

### ISSUE THREAD

**Issue by ne2030** [juliangarnier/anime#636]
**Is your feature request related to a problem? Please describe.**
I wanted to use matrix property for my animation but it doesn't work!
What i wanted to use was scaling element just horizontally. i know i can use width or padding for that but as you know, its not good for performance. 

**Describe the solution you'd like**
I checked anime set supported transform values, [validTransforms] array, and when i add 'matrix' to that, it worked!
I guess there's some issue or complicated calculation for merging translate values. but it would be great if anime support matrix transform value!

**Describe alternatives you've considered**
Just add matrix property and write warnings for probable issue for matrix value..?

**Additional context**
I also found that anime seems not support for order of transform values. Is there any plan for supporting transform values order..? I did use initial values to set order, but is there any feature?

**Comment by kn0wn** [comment]
Referencing the `validTransforms` https://github.com/juliangarnier/anime/blob/master/src/index.js#L26

**Comment by ne2030** [comment]
I checked source. And there's not 'matrix' value. Is there any problem with supporting 'matrix' ?

**Comment by juliangarnier** [comment]
@ne2030 I think we can support matrix and matrix3d if for some reason you want to work with matrices values, but in you case, why didn't you use :
`scale: 10`
instead of :
`transform: 'matrix3d(10,0,0.00,0,0.00,1,0.00,0,0,0,1,0,0,0,0,1)'`
?

**Comment by juliangarnier** [comment]
@kn0wn Hey can you check your mail server ? Looks down again !
Thanks

**Comment by kn0wn** [comment]
@juliangarnier I think you're right, I've sent you an email using my other one, but it may turn up in your spam if you could take a look!
