### ISSUE TITLE
Scaling is jerky on Firefox

### ISSUE THREAD

**Issue by dangelion** [juliangarnier/anime#637]
Hi
I'm using the following animation:

```
  anime({
    targets: el,
    scale: [1.1, 1],
    opacity: [0, 1],
    rotate: '-0.001deg', // also tried // ['0.001deg', '0.001deg'], //'0.001deg', // [0.01, 0.01], // 0.01
    translateZ: 0,
    easing: 'cubicBezier(.215,.61,.355,1)',
    duration: 500,
    begin: () => {
      el.style.display = "block";
    },
    complete: () => {}
  })
```

It's smooth on Chrome and Safari but it's awful (really awful) on Firefox. It's jerky and choppy.

I know of this known bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=739176
and as you can see above I already tried the `rotate` workaround (https://github.com/juliangarnier/anime/issues/358#issuecomment-381287947) and also added `will-change: transform; `on the element but it's near the same. Not yet acceptable for production.

Anyone has solved this annoying issue?

**Comment by kn0wn** [comment]
Hi @dangelion, I've tried to replicate the issue on my side but having no luck. I'm going to close this for now, but if you are still having the issue please create a new one with an attached codepen example!
