### ISSUE TITLE
How to use absolute or window relative positioning?

### ISSUE THREAD

**Issue by boan-anbo** [juliangarnier/anime#639]
How does one set translateX/Y to [x,y] which is relative to the window, rather than to the current position of the animated element?

**Comment by BrisaBoards** [comment]
AnimeJS doesn't change the way the browser renders, so I don't think you can do that. A little more detail about what you're trying to do could help.

I use absolute positioning and change left/top coords in my animations.

Some options require creative thinking, or a bunch of math!
