### ISSUE TITLE
animation radius not working IE & firefox 

### ISSUE THREAD

**Issue by amera7md** [juliangarnier/anime#64]
when we create our anime obj for example : 

```
anime({
  targets: 'div',
  width: '70%', 
   borderRadius: 8,
  duration: 3000,
  loop:false 
});
```
 the animation will stay not curved with Firefix & IE +10 , `borderRadius` works 100% with chrome

**Comment by juliangarnier** [comment]
Try using `'8px'` or `['0px', '8px']` instead, to force the unit or the initial value.
The way the initials styles values are calculated vary depending of the browser.

**Comment by amera7md** [comment]
`8px `works well ! , thanks
