### ISSUE TITLE
Rotate Radius issue

### ISSUE THREAD

**Issue by yangbe** [juliangarnier/anime#641]
**Screenshots**
![image](https://user-images.githubusercontent.com/9880101/71555226-ab76b080-2a64-11ea-919f-867f77ec295a.png)

**check it here**
https://jsrun.pro/RmWKp/edit

**Desktop (please complete the following information):**
 - OS: [macOSX]
 - Browser [chrome]
 - Version [78.0.3904.108]

**Comment by borodadada** [comment]
yes, how i can rotate svg object from center ?
```
            const rotate = obj.attr('transform',function(){
                var me = obj.node()
                var x1 = me.getBBox().x + me.getBBox().width/2;
                var y1 = me.getBBox().y + me.getBBox().height/2;
                return `rotate(180, ${x1}, ${y1})`;
            }); 
```

**Comment by kn0wn** [comment]
Hi @yangbe - Maybe I have missed what issue you are having, but the rotation is off as you have the translateX which is moving it around the center.

**Comment by kn0wn** [comment]
Hi @yangbe, I'm going to close this issue for now, please open a new issue if you are still getting this output.
