### ISSUE TITLE
Cannot find module 'anime'

### ISSUE THREAD

**Issue by ericmorand** [juliangarnier/anime#644]
When requiring animejs using the require syntax available in the npm documentation (https://www.npmjs.com/package/animejs), I get the following error:

> Cannot find module 'anime'

That is when using:

`require('anime')`

**Comment by iamlasse** [comment]
I believe it should be animejs and not anime. I had a similar issue with import from statement.

**Comment by ericmorand** [comment]
Looks that this was fixed a few months ago but was never pushed to npm:

https://github.com/juliangarnier/anime/pull/604/files

**Comment by kn0wn** [comment]
This has been updated on npm
