### ISSUE TITLE
svg element rotate

### ISSUE THREAD

**Issue by borodadada** [juliangarnier/anime#648]
hello, library cool but no have simple function rotate by center for svg elements in container svg

**Comment by IpsumLorem16** [comment]
This is a [known problem](https://css-tricks.com/transforms-on-svg-elements/) when animating SVG. From my searching, I don't think that this library has the support for 'normalising' `transform-origin` across browsers for SVG.  Greensock has done it, but I think it is trickier than it looks to add support for in libraries. 

SVGs `transform-origin` for its elements is from the top left 0,0 of the SVG, for browser wide support you need to set this value in PX on the element you want to rotate. You need to find the co-ordinates of the center of the shape you wish to rotate within the SVG. like this:
https://codepen.io/ipsumlorem16/pen/vYOLLQL. This can be tricky to find that point depending on where the element is, you might need to open it back up in an editor to find it.

**Comment by kn0wn** [comment]
Thanks @IpsumLorem16 for the workaround - this will be taken into consideration in the upcoming versions
