### ISSUE TITLE
Multiple items using selector doesn't work

### ISSUE THREAD

**Issue by xgiovio** [juliangarnier/anime#649]
anime({
		  targets: '#cncimage , #3dprintimage',
		  rotateX: [
		  	{value: 360,duration: 600,easing: 'easeInOutSine',delay: 1000},
		  ],
		  direction: 'normal',
  		  loop:true
		});

It seems doesn't work.

**Comment by stotoma** [comment]
I am not entirely certain how to use Id's to reference the object. But this should solve your problem.
`targets: [document.getElementById('cncimage'), document.getElementById('3dprintimage')]`

The targets are enclosed by an array indicated by the square-brackets. This will also work with any combination of multiple objects.

Ie:
`targets: [document.getElementById('cncimage'), '.foo']`
`targets: ['.foo', '.bar', '.moreFoo .moreBar', '.somethingElseAsWell']`

**Comment by kn0wn** [comment]
As @stotoma stated, use `document.getElementById` for elements with an ID
