### ISSUE TITLE
Reversing animation not working in Animejs 3.1.0

### ISSUE THREAD

**Issue by dnspnjrs** [juliangarnier/anime#652]
Hey,

Perhaps im not understanding the reversing of animations entirely but stumbled upon a bug when reversing svg animations.

**Describe the bug**
SVG animation is not reversing correctly. There seems to be a difference in anime 2.2.0 and 3.1.0 with this.

**To Reproduce**
Click on the "Toggle" button in the example to toggle the animation in forward or reverse. Both scripts are the same, only difference is animejs version.

[Example with Anime 3](https://next.plnkr.co/edit/bogN91CK4KKRjHrS?open=lib%2Fscript.js&preview)
[Example with Anime 2](https://next.plnkr.co/edit/ozK8TAwy2GfVTM8z?open=lib%2Fscript.js&preview)

**Expected behavior**
It should reverse the animation correctly.

**Desktop:**
 - Mac OS X
 - Chrome 76

**Comment by sid3r** [comment]
here's a solution : 

https://github.com/juliangarnier/anime/issues/577#issuecomment-573292680

**Comment by dnspnjrs** [comment]
> here's a solution :
> 
> [#577 (comment)](https://github.com/juliangarnier/anime/issues/577#issuecomment-573292680)

Hi @sid3r, thanks for your response.

Ive forked the [plunker](https://next.plnkr.co/edit/b5SKM0eZpRufAz7O?open=lib%2Fscript.js&preview) with the proposed solution with anime 3. As you can see the solution is not working for anime 3.

**Comment by sid3r** [comment]
@dnspnjrs your welcome, I thought it may help.

same for me didn't work as expected. _ani.began_ and _ani.paused_ aren't trustworthy finally.

**Comment by slavanossar** [comment]
> > here's a solution :
> > [#577 (comment)](https://github.com/juliangarnier/anime/issues/577#issuecomment-573292680)
> 
> Hi @sid3r, thanks for your response.
> 
> Ive forked the [plunker](https://next.plnkr.co/edit/b5SKM0eZpRufAz7O?open=lib%2Fscript.js&preview) with the proposed solution with anime 3. As you can see the solution is not working in this example.

Removing `loop: false` in your example makes it work, since [the default value for `loop` is actually `1`](https://github.com/juliangarnier/anime/blob/4d3cae8474d88aaf1b0f8beb3c4473d28d8c0d54/src/index.js#L12).

**Comment by kn0wn** [comment]
Thanks for the help @slavanossar, maybe this can be made more clear on the documentation

**Comment by dnspnjrs** [comment]
> > > here's a solution :
> > > [#577 (comment)](https://github.com/juliangarnier/anime/issues/577#issuecomment-573292680)
> > 
> > 
> > Hi @sid3r, thanks for your response.
> > Ive forked the [plunker](https://next.plnkr.co/edit/b5SKM0eZpRufAz7O?open=lib%2Fscript.js&preview) with the proposed solution with anime 3. As you can see the solution is not working in this example.
> 
> Removing `loop: false` in your example makes it work, since [the default value for `loop` is actually `1`](https://github.com/juliangarnier/anime/blob/4d3cae8474d88aaf1b0f8beb3c4473d28d8c0d54/src/index.js#L12).

Yes, that seems to be the issue. I see in the docs it accepts `true` so automatically assumed it accepts `false`. My bad and thanks!
