### ISSUE TITLE
Draggable, Inertia 

### ISSUE THREAD

**Issue by coolemur** [juliangarnier/anime#656]
**Description**
I wonder if there are drag-drop and inertia features implemented in animejs already ?

For example if you want to create a draggable gallery which spins for a while after you release (throw) it with your mouse or touch gestures

**Solution**
It would be nice to have some kind of plugin that adds drag-drop, inertia features.

**Alternatives**
GSAP's Draggable and ThrowPropsPlugin

**Additional**
-

**Comment by kn0wn** [comment]
Hi @coolemur, thanks for the suggestion, but this is currently out of scope for anime.js

**Comment by yellow1912** [comment]
@coolemur try popmotion it has inertia (used to be called decay on their documents)
