### ISSUE TITLE
pause() control not working for an element

### ISSUE THREAD

**Issue by fehernandez12** [juliangarnier/anime#668]
**Description**
I have set up an animation that translates a container div and its content across the screen. It is supposed to work in such a way that, when you hover with your mouse over the container (triggering the .onmouseenter event), the animation is paused and a small span appears over it. However, when I hover with the mouse over it, nothing happens.

Here's the code for both the container and the whole animation and its controls.

HTML:
`<div class="submarine-container">
        <span>(ง ͠° ͟ل͜ ͡°)ง</span>
        <img class="submarine" src="img/submarine.png" alt="Submarine">
    </div>`
JS:
```
function ready(fn) {
    if (document.attachEvent ? document.readyState === "complete" : document.readyState !== "loading") {
        fn();
    } else {
        document.addEventListener("DOMContentLoaded", fn);
    }
}
var submarineAnim = anime({
    targets: ".submarine-container",
    translateX: [-50, 1800],
    translateY: [200, 200],
    duration: 50000,
    easing: "linear",
    loop: true,
    delay: 20000
  });

ready(function(){
    var submarineEl = document.querySelectorAll(".submarine-container");
    var submarineTooltip = document.querySelectorAll(".submarine-container span");
    submarineEl.onmouseenter = function() {
      submarineAnim.pause();
      submarineTooltip.style.display = "inline";
    };
    submarineEl.onmouseleave = function() {
      submarineAnim.play();
      submarineTooltip.style.display = "none";
    }
})
```

**Comment by kn0wn** [comment]
Hi @fehernandez12, It seems as though your issue is coming from how you're listening to the mouseenter/mouseleave event. DocumentQuerySelectorAll returns a nodelist with all elements found, therefore you need to either attach the event listener to all nodes, or just use DocumentQuerySelector to get one node. 

```
  var submarineEl = document.querySelector(".submarine-container");
  var submarineTooltip = document.querySelector(".submarine-container span");
```
