### ISSUE TITLE
Why anime.js "targets" not work with jQuery parameter?

### ISSUE THREAD

**Issue by duboloms** [juliangarnier/anime#672]
I'am tried to point to property "targets" jquery selector: 
```
const $btn = $('.home-block__btn-login');

$btn.on('click', function() {
  anime({
    targets: $btn,
    translateX: 250
  });
});
```

**Comment by JeronimasDargis** [comment]
Hi duboloms change to: 
"
const $btn = $('.home-block__btn-login');

$btn.on('click', function() {
  anime({
    targets: ('.home-block__btn-login'),
    translateX: 250
  });
});
"

**Comment by kn0wn** [comment]
Hi @duboloms, the jquery item selector isn't supported, please use the class selector that @JeronimasDargis provided
