### ISSUE TITLE
How to perform a Bezier animation with smooth transition between points

### ISSUE THREAD

**Issue by karliky** [juliangarnier/anime#683]
I'm trying to migrate my Machinima Tool from GSAP to animate.js as I find the API quite simpler.

For that, I need to perform a Bezier animation among all the keyframes. I'm using GSAP 2, and their BezierPlugin which accepts a "soft" parameter https://greensock.com/docs/v2/Plugins/BezierPlugin described as this:

> "soft" - the values that you provide in the array act almost like magnets that attract the curve towards them, but the Bezier doesn't typically travel through them. They are treated as control points on a Quadratic Bezier and the plugin creates the necessary intermediate anchors. The target's current/starting values are used as the initial anchor.

When using Anime.js I see no way to specify how the points should be treated, I need the points to be moved smoothly between the whole path. 

**I've recorded this video to show the result with _Anime_.js:**
https://youtu.be/Up9WoLOHNhE [starts at 00:11]

It looks like the animation with Anime goes like this: Move one point to another. Stop. Move one point to another. Stop... etc.

I would expect the movement to be like GSAP soft's type of bezier movement, if you take a look at this video, you'll see how the camera moves smoothly between all the points, instead of going from one to another like with Anime.js:
https://youtube.com/watch?v=zYT7G2qqds0

My anime code:
```
    const cinematicValues = {
      x: firstStep.position.x,
      y: firstStep.position.y,
      z: firstStep.position.z,
      yawCos: Math.cos(firstStep.yaw),
      yawSin: Math.sin(firstStep.yaw),
      pitch: firstStep.pitch,
      roll: firstStep.roll,
    };

    const keyframes = cinematicSteps.map((step) => {
      return {
        x: step.position.x,
        y: step.position.y,
        z: step.position.z,
        yawCos: Math.cos(step.yaw),
        yawSin: Math.sin(step.yaw),
        pitch: step.pitch,
        roll: step.roll,
      };
    });

    const cinematicSpeed = Number(speed || 10);

    tween = anime({
      targets: cinematicValues,
      duration: cinematicSpeed * 1000,
      easing: 'linear',
      keyframes,
      update: function() {
...
      }
    });
```

**Comment by juliangarnier** [comment]
There is no plugin equivalent to gsap Bezier plugin in Anime.
But looking at your code, you should try using something different from `easing: 'linear'`, maybe something like `easing: 'cubicBezier(.5,0,.5,1)',` although this will only ease out the timings between each points.

**Comment by karliky** [comment]
Yeah so I already tried that and it eases out the timings between each point as you said. So I guess there is no way to make it with Anime, thank you!
