### ISSUE TITLE
Split up the sources in multiple files.

### ISSUE THREAD

**Issue by twoco** [juliangarnier/anime#685]
Currenlty the [source code](https://github.com/juliangarnier/anime/tree/v3.1.0/src) is just one big file with over 1260 lines.
Consider to split it up into multiple files which is easier to manage and better scalable. It's better to contribute. Don't worry, the bundler Rollup (or Webpack or what you prefer.) will handle it and build it in a single file. - Or is there a reason to holding a mono file?

**Comment by kn0wn** [comment]
Hi @twoco, this will be worked on in the next major release. I'll close this for now.
