### ISSUE TITLE
Animating Multiple Elements when passed one element

### ISSUE THREAD

**Issue by rz-0605** [juliangarnier/anime#691]
**Describe the bug**
Anime is animating multiple elements when only passing one element to targets.
```
const target = document.getElementById(notification._id);
console.log(notification._id);
console.log(target);
anime({
	targets: target,
	opacity: [1,0],
	duration: 500,
});
```

**Expected behavior**
    Only one element should be animated, not all sibling elements.
![image](https://user-images.githubusercontent.com/56363473/82849266-1a95eb00-9ec5-11ea-8c70-dfed987c69b2.png)

https://gfycat.com/ficklefrayedclownanemonefish

Also, I am using React and the function above is called upon deletion of a component.

**Comment by Ridvanovskyy** [comment]
Looks like that this is issue in your component. Can you show code of component? Mb animation triggers on `componentDidUpdate` or `anime()` in render function?
