### ISSUE TITLE
Reverse and Delay don't work properly together

### ISSUE THREAD

**Issue by abusedmedia** [juliangarnier/anime#693]
When using `delay` together with `direction:'reverse'` the animation starts immediately instead of waiting the delay amount.
Ideally, it should work as `gsap.from`, the property should be set immediately and the reversed animation should start after the provided delay.

Here the example:
https://codepen.io/abusedmedia/pen/dyYEZxW?editors=0010

**Comment by edreesjalili** [comment]
Since it's reversed, I believe you actually want to use `endDelay` instead of `delay`.

**Comment by abusedmedia** [comment]
That's correct indeed. It works as expected. I was misled by how `gsap` actually works. Thanks for the tip.
