### ISSUE TITLE
Documentation for elastic seems wrong in many ways

### ISSUE THREAD

**Issue by tieTYT** [juliangarnier/anime#694]
I am talking about this page: https://animejs.com/documentation/#elasticEasing

- The code sample at the bottom doesn't seem to relate to the visual example on the left
- There is a table with headers of In, Out, In-Out. I think the value of this is trying to tell you the name of the easing, but these are not the names of the easing. `outElastic `should be called `easingOutElastic `. All of the values have this typo
- The parameters could be described in a more helpful way. `Controls the overshoot of the curve` -> `Controls the overshoot of the curve. The larger this number, the more overshoot there is. ` `Controls how many times the curve goes back and forth ` -> `Controls how many times the curve goes back and forth. The smaller this number, the more times the curtain goes back and forth. `

**Comment by juliangarnier** [comment]
Thank you for pointing this out, I'll change the doc accordingly with a more clear code example explicitly using each easings.
