### ISSUE TITLE
Seek doesnt seem to work in timeline

### ISSUE THREAD

**Issue by sagive** [juliangarnier/anime#697]
I created a timeline with multiple "add' points and i am trying to return to a specific point in time using seek (if that's the best way)

Here is a very simple clean example of the problem 
only the 'first' button works
https://jsfiddle.net/sagive/6m1xy47L/15/

Here is the more complex live example inside a site
i am creating (the icons are should lead to the timeframe)
https://bit.ly/2YaiK3Y

I'm using a timeline (and not frames) because other callback functions run on each of the timeline "add sections" on complete / update

Thank you ;)

**Comment by Pulse-Git** [comment]
looks like there is a problem with looping try `loop: false` on the timeline 
also `1.25 * duration` is not possible, you cant seek higher than the duration, it will then seek to the max duration.

if you still need the loop function, here is a small workaround:
 
```
    $('.stage3').click(function() {
      tl2.pause();
      tl2.seek( .5 * tl2.duration )
      tl2.play();
    });
```
(Pause, than seek, than play)

**Comment by sagive** [comment]
Awesome man... that workaround seems to work great
thanks a lot for your help ;)
