### ISSUE TITLE
Text not animating

### ISSUE THREAD

**Issue by Devloper906** [juliangarnier/anime#698]
Hello to all GitHub users

the thing is not working as expected, I have downloaded the main lib and invoked it into my HTML code, but it doesn't work,
Please help!!!

**Comment by Ridvanovskyy** [comment]
@Devloper906 
Сan you please describe in more detail the problem you have and if you can attach a link to the playground (codepen etc).

**Comment by kn0wn** [comment]
Hi @Devloper906, can you please recreate this issue report using the templates provided and we can look into it more. Closing for now.
