### ISSUE TITLE
Is there a way to smooth the animation when using seek?

### ISSUE THREAD

**Issue by yellow1912** [juliangarnier/anime#703]
**Is your feature request related to a problem? Please describe.**
Hello, I'm trying to replicate the smooth effect found on Webflow animation:
https://university.webflow.com/article/interpolation-easing-smoothing

It allows you to kind of smooth out the animation (nice parallax effect) when scroll the page.

**Describe the solution you'd like**
I see spring easing has this kind of damping parameter, can we have something similar with the overall animation.

**Comment by yellow1912** [comment]
I now have an initial working code, just need some hints to tweak it.

The code is inspired by an example with GSAP, they did 2 things:
1. They create a proxy animation and inside the scroll event they "seek" the proxy animation
2. They have a "tick" event callback, inside that callback they "seek" the real animation (using the progress from the proxy animation)

The codepen is:
https://codepen.io/Sahil89/pen/XyJQQr?editors=1111

I made an animejs version, but I don't know if we have anything similar to their's tick event, so I created a loop with requestAnimationFrame. 

The codepen is:
https://codepen.io/raineng/pen/WNrJbep?editors=1112

As you can see, the effect is close to what GSAP has, but there are 2 major issues:
1. I'm using a very naive timeout to stop the requestAnimationFrame loop. I figured I should somehow calculate the diff between the 2 progresses and stop the animation frame based on that.
2. The animated object does not go to complete 0 and 100 percent sometime (probably caused by 1). I think I need to do some roundup/down here because unlike in gsap our diff never reachs 0.

If anyone has any idea, please let me know. I'm willing to try anything.

**Comment by aquaductape** [comment]
So still no anime.js solution?

**Comment by mattheri** [comment]
I used animejs to tween the value I used to seek another animation/timeline. Just make sure that you seek your animation in the update function of the animation that transition the value.

Would that cover your usecase?

In retrospect, my way seems very naive but it worked for my usecase.
