### ISSUE TITLE
[Bug] Autoplay bug with duration 0

### ISSUE THREAD

**Issue by yellow1912** [juliangarnier/anime#705]
**Describe the bug**

When autoplay is set to false, the animation should not start before we call play manually.

**To Reproduce**

Using property keyframes, if the duration of the keyframe is set to 0, it is automatically applied even with autoplay set to false.

Go to: 
https://codepen.io/raineng/pen/MWKGGqq

**Expected behavior**
Background should not be turned into black in this case

**Additional context**
Animejs version is 3.2.0

**Comment by Pulse-Git** [comment]
That's not directly a "Bug", Duration: 0 is always the start point of the animation, its like a Video the first image (frame 0)
and you have set the Background black on duration 0, and 0 is the start point, simple right?

**Comment by yellow1912** [comment]
I see, I think it's a bit unexpected if I may put it that way. In my case, I create anime instance for later use (callback on click event etc), so my expectation was that when I haven't played then nothing happens yet. 

Anyhow, I will close this issue now since it's not a bug. Perhaps a clarification to the doc is useful (or perhaps it's there and I miss it?)
