### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [juliangarnier/anime#709]
**Describe the solution you'd like**

## Remove Google Analytics

If you must have an analytics system, might I suggest either:
- Plausible: https://plausible.io (offers a 50% discount for FOSS projects)
- Goatcounter: https://goatcounter.com
- Matomo: https://matomo.org
- Fathom: https://usefathom.org

These solutions are all well-tested and open-source. This, of course, means they
can be independently audited for privacy and security. Instead of using a proprietary
nonfree system such as Google Analytics, perhaps we could work together to replace
it with something slightly more ethical?

Furthermore, the majority of privacy features in evergreen browsers *block* Google
Analytics from being run. I can not say the same for solutions such as Plausible,
which suggests they are trusted for their privacy by independent persons.

If you need any more information, please contact me!

**Comment by kn0wn** [comment]
Hi @resynth1943, Thanks for the alternatives. 

I will have a chat with Julian about what we can implement. I will get back to you once a decision is made.

**Comment by resynth1943** [comment]
Thanks a *bunch*, kn0wn! Can't wait to see what happens...
