### ISSUE TITLE
Animations choppy when interacting with images?

### ISSUE THREAD

**Issue by ndimatteo** [juliangarnier/anime#71]
I'm not sure if I'm missing something inherent here, but I noticed when I run an animation and it's either:

a) On an element overtop an image that's loading, or;
b) On an element that contains an image

the animation ends up becoming choppy as hell, until the page loads more. Seems to be if I use traditional css3 animations/transitions and even jquery's $.animate() this doesn't happen so I don't understand how using anime is causing this issue. Am I doing something wrong here?

**Comment by juliangarnier** [comment]
Can you provide a live example?

Thanks
