### ISSUE TITLE
Extra `0 ` added at the end of it keyframe innerHTML

### ISSUE THREAD

**Issue by DhruvaSambrani** [juliangarnier/anime#710]
**Describe the bug**
When a keyframe animation is used by updating `innerHTML` of a `div` by some text

**To Reproduce**
```javascript
anime({
    targets: '.landing-name',
    keyframes: [
        { innerHTML: "a" },
        { innerHTML: "b" },
        { innerHTML: "c" },
        { innerHTML: "d" },
        { innerHTML: "e" },
        { innerHTML: "f" },
    ],
    duration: 3000,
    easing: 'easeInOutSine',
    update: function (anim) {
        var obj = document.getElementsByClassName('landing-name')[0]
        obj.innerHTML = obj.innerHTML.slice(0, obj.innerHTML.length - 2)
    }
}).play()
```
**Expected behavior**
Animation moving from `a` to `f`

**Screenshots**
![image](https://user-images.githubusercontent.com/44899822/87723018-bf9eb700-c7d6-11ea-94ad-56fd38085e77.png)
![image](https://user-images.githubusercontent.com/44899822/87723028-c3323e00-c7d6-11ea-8fea-cde9f2a0b838.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Vivaldi
 - Version: 3.1.1929.45

**Smartphone (please complete the following information):**
Unchecked

**Additional context**
I'm using the `#master anime.min.js` downloaded and linked to html using `<script>`
This can be circumvented by simply adding an update function to set `innerHTML = innerHTML.splice(0, innerHTML.length-2)`

**Comment by juliangarnier** [comment]
Anime.js was designed to animate numerical values, not text.
So hard to tell why the 0 appears in your example without a proper example, but it looks like a fallback to 0 when no numerical values are provided.
