### ISSUE TITLE
Documentation for rangeValueStaggering requires update

### ISSUE THREAD

**Issue by YunzheZJU** [juliangarnier/anime#715]
**Describe the bug**
API info table for rangeValueStaggering at https://animejs.com/documentation/#rangeValueStaggering seems not matching the given example.

**Screenshots**
![0](https://user-images.githubusercontent.com/23452609/91587132-f137a000-e988-11ea-9525-b8738246b2c0.png)

**Comment by juliangarnier** [comment]
Fixed #568
