### ISSUE TITLE
Made with Anime.js

### ISSUE THREAD

**Issue by kennetpostigo** [juliangarnier/anime#72]
Hey, just wanted to say thank you for creating `animejs`! Because of your work we were able to make animations in react simpler and easier with [react-anime](https://github.com/stelatech/react-anime) than they used to be. Making our lives wayy easier because of your animation engine.

**Comment by juliangarnier** [comment]
Wow cool!
I don't have a lot of experience working with React, but I'm happy to see Anime being integrated in project like this!
Keep it up!
