### ISSUE TITLE
anime transition conflict with css transtion

### ISSUE THREAD

**Issue by hatem-mazid** [juliangarnier/anime#722]
animation doesn't run well if the element has a transition in css

maybe we should reset some css properties from JavaScript

**Comment by Losses** [comment]
Yep, you should avoid using JavaScript animation and CSS animation together if you don't know what ur really doing, same thing happens to anime.js.

I don't think this is a bug.

**Comment by AcademyOfF** [comment]
I don't know if it's a bug, but I also don't know how to work around these issues. Some libraries use JavaScript animation. Others use CSS animation. Both can be extremely useful. How do I use both of them on one project?
