### ISSUE TITLE
Use function-based parameters to modify the animation without re-creating the timeline. Possible?

### ISSUE THREAD

**Issue by Eketol** [juliangarnier/anime#724]
Hi,
I'm trying to create a basic animation editor (using AnimeJS and ThreeJS), where the user can do things like changing an object's position on each keyframe or changing keyframes' duration.
For example: at keyframe 2, the user could move an object to a different position. Then he could use a Slider control to seek/play the animation back and forward, with the new changes updated "in real-time".

I thought I could create a timeline and add keyframes with function-based parameters. This way I would not need to re-create the timeline each time the user makes a change.
But it seems the parameters' values are calculated and stored the first time I add the keyframes to the timeline, so the new changes are not updated in the animation.

I'm new with AnimeJS, so I'm not sure if I'm doing something wrong or missing some settings.

Is it possible to achieve this or is there a better way than re-create the timeline on each change?

**Comment by juliangarnier** [comment]
No each animation have pre-defined values, even function based values.
If you need an animation with different values, you have to create a new one.

Interesting project, curious to see how it works when you have something to show!
