### ISSUE TITLE
Animation flickering

### ISSUE THREAD

**Issue by fabrikatdigital** [juliangarnier/anime#725]
See here: https://codepen.io/DennisYo/pen/ZEWNjEJ

or here: https://codepen.io/DennisYo/pen/rNegrWd

Seems like the bug described here hasn't been fixed yet: https://github.com/juliangarnier/anime/issues/577

Any suggestions on how to fix it?

**Comment by iliedaniel** [comment]
I don't think it's a bug; try to set easing: 'linear'

**Comment by juliangarnier** [comment]
not a bug, the `easeOutElastic(1, .5)` values will oscillate between > 1 and < 1 before reaching 1.
Try visualising the easings here https://animejs.com/documentation/examples/anime-ease-visualizer.html
