### ISSUE TITLE
Inconsistent behavior while adding scaling before translateX and translateY.

### ISSUE THREAD

**Issue by ksr89-magic** [juliangarnier/anime#728]
(https://codepen.io/ksr89-magic/pen/Vwjvzdx)

STR:
When the above codepen page is loaded then first click on the "Animate scaling" button then click on the "Animate All Properties" button then you can see inconsistent behavior while the object is moving and scaling.

Expected Output:
Reload the codepen page then click on the "Animate All Properties" button, the object should move in a straight path with scaling.

**Comment by juliangarnier** [comment]
The order in which your animating the transforms properties matters (this is not related to Anime.js, but to the way CSS transforms work).

So if you want to make sure to always have consistent behaviour I recommend setting all the transforms properties in the order you want, even if you're only animating one.

So your scaling animation should look like this:
`
  anime({
    targets: '.square',
    translateX: 0, // Or '+=0'
    scale: 0.8,
    duration: 3000,
    easing: "linear"
  });
`

That way next time you're animating the transforms, the translateX property will always be set before scale.
