### ISSUE TITLE
SVG Motion Path broken with latest version.

### ISSUE THREAD

**Issue by FractalHQ** [juliangarnier/anime#729]
**Describe the bug**
SVG Motion Path is not working in the latest version.

**To Reproduce**
Go to [https://codepen.io/Fractal-HQ/pen/yLJeXvq](https://codepen.io/Fractal-HQ/pen/yLJeXvq)
Change animejs version to 1.1.2 and it works again.

**Expected behavior**
The div to animate along the motion path.

**Screenshots**
<img width="303" alt="Screenshot 2020-10-14 at 9 48 14 PM" src="https://user-images.githubusercontent.com/55504972/96067097-f8e2d380-0e66-11eb-8b1c-6c75deffdc42.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Latest

**Additional context**
I would use the earlier version of anime, but it breaks the other animations my site.

**Comment by juliangarnier** [comment]
The API changed a bit since v1.x, see the docs https://animejs.com/documentation/#motionPath
