### ISSUE TITLE
Getting amine is not defined

### ISSUE THREAD

**Issue by nomanaadma** [juliangarnier/anime#743]
**Describe the bug**
Getting error message in console anime is not defined
![Screenshot_7](https://user-images.githubusercontent.com/47977013/103378891-b051c280-4b05-11eb-91e6-1411573b31fa.png)

**To Reproduce**
1. Include Anime JS
![Screenshot_6](https://user-images.githubusercontent.com/47977013/103378863-987a3e80-4b05-11eb-9155-257db97f076a.png)

I tried to call the anime function in window.load and setTimeout and tried including anime.es6.js, anime.js, anime.min.js nothing worked 

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome 87.0.4280.88

**Comment by irfan-zahir** [comment]
friend, you have type there, shud be anime and not amine

**Comment by nomanaadma** [comment]
My Bad
I copied this code from somewhere never noticed it.
Thanks for your help
