### ISSUE TITLE
Animate a Array of Objects as the target?

### ISSUE THREAD

**Issue by zning** [juliangarnier/anime#759]
I went through the document but didn't found an example or solutions. Could someone please help to see if that's even possible. 

Try to animate an Array of objects to a different Array of objects.

For example:
Target: 
let target = [{...obj},{...obj},{...obj},{...obj}...];
To:
let final = [{...obj},{...obj},{...obj},{...obj}...];

The Objs inside of the array could be the result of Array.map().
The Objs inside of the array has similar structures(same properties)but the output values are all different.

Any idea how or possible? Thanks a lot!

**Comment by Amit-Morade** [comment]
Maybe I can do this if you could tell me what language are you using?

**Comment by zning** [comment]
> Maybe I can do this if you could tell me what language are you using?

Thanks, I'm using JS and react. The data is in JSON format.

**Comment by juliangarnier** [comment]
Not without iterating over each object of the targets array and create an anime() instance with all the properties animating to the final values.
Although not possible in the current API, animating automatically between two states is an interesting concept and I will keep this in my notes for an eventual future implementation :)
