### ISSUE TITLE
[Feature request] play a segment of animation

### ISSUE THREAD

**Issue by lihsai0** [juliangarnier/anime#760]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when seek() doesn't have transition animation.

**Describe the solution you'd like**

I would like there is a method can paly a segement of animation.

For example:

``` javascript
segment({ from='now', to }) {
  //...
}
```

The `segment` can play a sement in timeline.

If duration is 10s(10 000ms):

When call `segment({ from: 5000, to: 8000 })`, play animation from 5s to 8s.
When call `segment({ from: 'now', to: 8000 })`, play animation from current state to 8s state. This may complex, I am thinking.

**Additional context**

I am new about animejs. If it can be implemented in current framework, I would like to follow up this feature and try a PR.

**Comment by juliangarnier** [comment]
> I'm always frustrated when seek() doesn't have transition animation.

I'm not sure what you mean by adding a transition to seek(), can you expand on this a bit more?

> When call segment({ from: 5000, to: 8000 }), play animation from 5s to 8s.

This can be achieve quite easily with a little helper function like this:

```js
function segment(animation, from, to) {
  anime({
    duration: to - from,
    update: anim => animation.seek(from + anim.currentTime)
  });
}

segment(animation, 5000, 8000);
```

From there it wouldn't be to hard to segment from 'now' as well.

**Comment by lihsai0** [comment]
@juliangarnier

> I'm not sure what you mean by adding a transition to seek(), can you expand on this a bit more?

Basing on [the seek demo in documentation](https://animejs.com/documentation/#seekAnim), if click a point on input[type="range"], it will blink to the target state.

The effect wanted when click a point on input[type="range"] is just like dragging handle of input[type="range"].

---

The helper function `segment(animation, from, to)` is great! I will try to implament above with it.
