### ISSUE TITLE
Artifact lines left over after animation

### ISSUE THREAD

**Issue by swilkewitz** [juliangarnier/anime#761]
**Describe the bug**
Hi, I really love this library!

I'm getting some artifact lines left over after animations: https://imgur.com/a/80Wrr7G

As far as I can tell it only happens when animating to and (sometimes from) a matrix3d target. Also. it is much more noticeable when the element is translating upward, so the bottom edge of the element is leaving the artifacts behind. Although I think other sides can leave them too.

**To Reproduce**

body background-color is #181a1b

First animation:
{
  color: "#1A8C8A",
  duration: 600,
  easing: "easeOutBounce",
  height: 236,
  matrix3d: "1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 318, 540, 0, 1",
  targets: ".animated-color-square-parent",
  width: 256
}

Second animation:
{
  color: "#695FC8",
  duration: 600,
  easing: "easeOutBounce",
  height: 236,
  matrix3d: "1.16435, 0, -0.241922, 0, -0.366877, 1.2, 0, 0, 0.290306, 0, 0.970296, 0, 598, 20, 0, 1",
  targets: ".animated-color-square-parent",
  width: 256
}

**Expected behavior**
No artifacts

**Screenshots**
https://imgur.com/a/80Wrr7G

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome version 90.0.4430.212 (Official Build) (64-bit)

**Comment by juliangarnier** [comment]
I remember seeing similar artefacts on Safari iOS with CSS transforms animations, but I'm not exactly sure why or how to fix them. Does adding `will-change: transforms` has any effect on the problem?

**Comment by swilkewitz** [comment]
That seems to have fixed it, thanks!
