### ISSUE TITLE
Transform order not respected

### ISSUE THREAD

**Issue by saminton** [juliangarnier/anime#764]
With the following code

```
const tl = anime.timeline({
    easing: 'easeInOutQuad',
    duration: 1000,
})

tl.add({
    targets: target,
    translateY: [0, '-15rem'],
    scale: [1, 0],
}, 0)
```

No matter the order that I declare `translateY` and `scale` the scale is outputted first in my html as `style="transform: scale(0) translateY(-15rem);"`

 - OS: MacOS 10.15.4
 - Browser: Chrome 91.0.4472.77
 - Version: animejs 3.2.1

**Comment by juliangarnier** [comment]
It's hard to tell where the problem comes from without the other parts of your code.
Can you provide a live example of your problem?
Thanks

**Comment by saminton** [comment]
I can't seem to replicate the bug with a codepen. I guess it must be a conflict with some other code I have and not a problem the the library itself.
