### ISSUE TITLE
Question (not a bug)

### ISSUE THREAD

**Issue by patchthecode** [juliangarnier/anime#766]
I want to know if animejs is the right library that can accomplish something like this ->

![slowed image](https://user-images.githubusercontent.com/2439146/123526323-1aa68280-d6a5-11eb-9ab7-cad900ca3b8a.gif)

```
1. There are cards on screen. 
2. Cards can be dismissed in 2 ways. Swipe up, or Swipe down. Swipe down to dismiss a card by _skipping_. Swipe up to dismiss a card by _promoting_ it. 
3. If you do not _swipe up_ all the way, the card snaps back to original position. If you do not _swipe down_ all the way, the card snaps back to original position. 
4. If i Swipe up quickly, I will dismiss the card with 1 promotion point. However, 
   If i swipe up slowly, it gives the user a chance choose how many points they will dismiss the card with. 
5. The swipe up color is yellow. The higher up you swipe, the yellow color fades into a lighter yellow color.  
```

Is animejs a library that help with something like this? Or maybe something else..?

**Comment by sadeghbarati** [comment]
these link might helps

https://github.com/davidkpiano/flipping
https://hammerjs.github.io

a repository example which use hammer js

https://github.com/ericktatsui/Touch-Menu-Like-Android
http://ericktatsui.github.io/Touch-Menu-Like-Android/


**close your issue after this**

**Comment by patchthecode** [comment]
ok i guess animejs cant do it?
will close this then

**Comment by sadeghbarati** [comment]
anime can do this such thing but you have to integrate it with touch libs or native `touchmove` or `mousemove` or `pointer` events

https://tympanus.net/codrops/
look this website most of example are using anime js
