### ISSUE TITLE
Trying to alternate between two background colors

### ISSUE THREAD

**Issue by carlosbtlr** [juliangarnier/anime#768]
Trying to alternate between two background colors, white always gets in the middle of the transition even though the default background-color of the element is set as black. 

`anime({
    targets: 'div',
    easing: 'easeInOutQuad',
    duration: 1900,
    loop: true,
    direction: 'alternate',
    keyframes: [
      {background: '#eb4034'},
      {background: '#0ddb44'},
    ]
  })`

**Comment by zjjjjjjjjjjd** [comment]
useless
