### ISSUE TITLE
One-way animation

### ISSUE THREAD

**Issue by cangSDARM** [juliangarnier/anime#773]
**Is your feature request related to a problem? Please describe.**
A common animation is a one-way transform. From a state to another state and stay it forever.
But animejs seems is not supported yet, see: [Issue, L32/L43, mouse down/up animation](https://codepen.io/AllenEyes/pen/bGWRvNw?editors=0010)

**Describe the solution you'd like**
Add a configure property to toggle it's one-way or not.

**Describe alternatives you've considered**
I considered using fixed value to manually set the finished state in `complete` callback but it's duplicate for other properties, I must store it in a const value.

**Additional context**
[Similarly, in GASP](https://greensock.com/docs/v3/GSAP/gsap.to())
[Question, StackOverflow](https://stackoverflow.com/questions/6092239/css3-one-way-transition)

**Comment by sadeghbarati** [comment]
https://codepen.io/sadeghbarati/pen/qBmjvjw

I wonder why you use both animation engine in same project

**Comment by sadeghbarati** [comment]
looks like it's conflict with older version

look your forked demo here I just update `gsap` to latest version
and use css variable instead but i think previous way work as well

https://codepen.io/sadeghbarati/pen/vYmZME


**close issue after this**

**Comment by cangSDARM** [comment]
Because I want to test the difference between animejs and gsap, so that I can recommend other alternatives to my project manager.
Thanks for pointing out my mistake, I will close this issue
