### ISSUE TITLE
What should happen when applying opacity less than 1 to a node with descendants?

### ISSUE THREAD

**Issue by trusktr** [juliangarnier/anime#80]
Hello Julian,

I'd like your opinion:

If we have a node (in a 3D scene graph), and it has many descendants (a sub tree), what should happen when we apply opacity with a value less than `1` to it?

1. It, and all of it's children should become transparent, multiplying opacities down the scene graph.
1. It's content should become transparent but not that of its descendants.
1. Same as (1), but the whole object should be flattened into a plane.

The reason I want your opinion is because the new specs for CSS 3D (css-transforms) [state here](https://drafts.csswg.org/css-transforms/#grouping-property-values) that the answer is (3).

To see what I mean, view these two examples in Chrome 53 or higher:

- https://jsfiddle.net/trusktr/ymonmo70/16
- https://jsfiddle.net/trusktr/ymonmo70/17

The second example has opacity applied to the node that contains all the sub-nodes which compose the car. The opacity, according to spec, flattens the car into a plane (turns it into paper!).

I'm asking various 3D engine authors for opinions of what the correct or most expected behavior should be.

All the best,
~ Joe

**Comment by thisolivier** [comment]
As a CSS dev, 3 seems to make sense. 1 would present some really interesting options, and ideally would also be available (for example if you explicitly set transform-style: preserve-3d), but as the default would make it much more complex to control the opacity of anything (and would have strange effects with occlusions changing on its children)- it's also a lot less taxing on the rendering engine.

**Comment by juliangarnier** [comment]
1 makes more sense to me.
Applying opacity to an element should not change the way it looks, except of course the opacity of this node and his children.
To me 3 looks more like a workaround to avoid complex 3D opacity rendering.
