### ISSUE TITLE
a problem about svg path anime

### ISSUE THREAD

**Issue by semi-xi** [juliangarnier/anime#81]
First of all, great library, thanks for the awesome work! :)

i find that in the example the attribute can change is like `d` `dx` `dy` `transform` or other common attribute，but if i want to change the attribute like `stroke-dashoffset`,it can't work.

```
object.path1.style['strokeDasharray'] = object.path1.getTotalLength();
object.path1.style['strokeDashoffset'] = object.path1.getTotalLength();
function a1(){
    anime({
        targets:object.path1,
        strokeDashoffset:0,
        duration:3000,
        loop:0,
        easing:'linear',
        complete:function(){
            anime({
                targets:object.path2,
                strokeDashoffset:object.path2.getTotalLength(),
                duration:3000,
                loop:0,
                easing:'linear',
                complete:function(){
                    a1();
                }
            })
        }

    })
}
```

how can i do  for work?

thank u!

**Comment by alexchantastic** [comment]
Seems to work fine for me: http://codepen.io/alexchantastic/pen/BLmZry

Can you post the full example you're working with?

**Comment by juliangarnier** [comment]
I confirm that animating strokeDashoffset works perfectly.
Thanks @alexchantastic for the example!

**Comment by semi-xi** [comment]
thanks @alexchantastic  for the example，
it need to set options`strokeDashoffset:[object.path1.getTotalLength(),0] `,but not `strokeDashoffset :0`
