### ISSUE TITLE
Trying to achieve different delay times

### ISSUE THREAD

**Issue by elliottmangham** [juliangarnier/anime#82]
Hello,
I am trying to achieve a very simple loading animation similar to the following:
http://codepen.io/elliottmangham/pen/XKqxmZ

Here is my existing experiment... but I can't quite figure out how to get the delay function so the second target starts when the first one ends... Please advise?
http://codepen.io/elliottmangham/pen/RGjrBa

Great JS library though, love the examples.

Kind regards

**Comment by alexchantastic** [comment]
If I understand what you're trying to achieve, you'll want to change your delay function to this:

```
function(el, index) {
    return index * 1500;
}
```

This essentially makes it so each subsequent animated element will be delayed 1500ms from the previous animated element.

**Comment by elliottmangham** [comment]
Hi, that's superb! Thanks for explaining.

Is it possible to target a specific element by name (class/ID) instead of
each subsequent one?

Kind regards

**Comment by alexchantastic** [comment]
Sure, you can use the `el` parameter in the delay function which will return the element's DOM node.

**Comment by elliottmangham** [comment]
Sorry could you give me an example? Say a class .one .two and .three?

Thank you

**Comment by juliangarnier** [comment]
Like this @elliottmangham :

````
var myAnimation = anime({
  targets: ['.one', '.three'],
  translateX: '13rem',
  rotate: 180,
  duration: 2000,
  loop: true,
  delay: function(el) {
    if (el.classList.contains('one')) {
      return 0;
    } else {
      return 200;
    }
  }
});
````
