### ISSUE TITLE
Useage of the Web Animations API

### ISSUE THREAD

**Issue by Pulse-Git** [juliangarnier/anime#822]
Are there any plans in the future to add an option that anime will use the [Web Animations API](https://developer.mozilla.org/de/docs/Web/API/Web_Animations_API) ?

Benefits:

- Better Performance? (Since <element>.animate uses native code, it may perform better?)
- the <element>.animate function will not modify the style attribute of the element which resolves several conflicts in some projects

.. this feature will also drop IE support but maybe only allow this in non IE environments

**Comment by juliangarnier** [comment]
It's not something planned for V4.

The main benefit of the Web Animation API is to update CSS properties on a separate thread, this prevents the animations from being interrupted if the main thread is under pressure.

But it comes with a lot of drawbacks, the main one to me is the limitation to only animate CSS properties, that means no regular JS objects and so no WebGL.

I was thinking about maybe doing an hybrid code base that fallback to RAF based animation for non supported targets like js Object, but the performances are actually not that good, even for CSS.
In my tests the frame rate starts to drop drastically above 1000 WAAPI animations, where the next version of anime.js can handle 2000 animations with multiple CSS Transforms properties at 60fps.
