### ISSUE TITLE
Import in a Nuxt3 project

### ISSUE THREAD

**Issue by Theo-Rige** [juliangarnier/anime#825]
**Describe the bug**
When I try to import into a page in a Nuxt 3 project like this :
`import anime from 'animejs/lib/anime.es.js'`

I got this error : 
`Le fichier de déclaration du module 'animejs/lib/anime.es.js' est introuvable. 'G:/projets/stwd/nuxt/node_modules/animejs/lib/anime.es.js' a implicitement un type 'any'.
  Essayez 'npm i --save-dev @types/animejs' s'il existe, ou ajoutez un nouveau fichier de déclaration (.d.ts) contenant 'declare module 'animejs/lib/anime.es.js';'ts(7016)`

I already try : 
- import anime from 'animejs'
- npm i --save-dev @types/animejs
- "type": "module" in package.json related to #https://github.com/nuxt/framework/issues/4936
- add animejs to transpile in nuxt.config.ts like this : 
`
export default defineNuxtConfig({
	build: {
		transpile: ['animejs'],
	},
	modules: ['@nuxtjs/tailwindcss', 'nuxt-graphql-client'],
	runtimeConfig: {
		public: {
			GQL_HOST: 'http://localhost:1337/graphql', // overwritten by process.env.GQL_HOST
		},
	},
})`

**Comment by slavanossar** [comment]
`animejs` doesn't support TypeScript, it's just a warning saying that there are no type declarations available so the return value for `anime` is implicitly being set to `any`.

Also [the `package.json` for `animejs` already defines the script entry point](https://github.com/juliangarnier/anime/blob/3ebfd913a04f7dc59cc3d52e38275272a5a12ae6/package.json#L7-L9), so you can just do

```js
import anime from 'animejs'
```

Another option is to create a [plugin](https://v3.nuxtjs.org/guide/directory-structure/plugins), which will be automatically registered by Nuxt

```js
// plugins/anime.client.js
import anime from 'animejs'

export default defineNuxtPlugin(() => ({
  provide: { anime },
}))
```

which you can then access via `useNuxtApp`, for example in an SFC:

```vue
<template>
  <span ref="text">Some text</span>
</template>

<script setup>
const { $anime } = useNuxtApp()
const text = ref(null)

onMounted(() => {
  $anime({
    targets: unref(text),
    opacity: [0, 1],
    duration: 1000,
    easing: 'linear'
  })
})
</script>
```
