### ISSUE TITLE
Tween between css classes

### ISSUE THREAD

**Issue by yspb** [juliangarnier/anime#83]
Can this library morph between classes on an element?
For example:

```
.class1 {
	color: red;
	font-size: 25px;
}

.class2 {
	color: #cccccc;
	font-size: 45px;
}
```

red = rgb(255, 0, 0) 
#ccccc = rgb(204, 204, 204)

So transitions will be:

red 255 -> 244
green 0 -> 204
blue 0->244
font-size 25->45

It all about properties that are generally tweenable.

**Comment by alexchantastic** [comment]
anime supports animations between numerical values not CSS classes. You can find examples of properties that it can animate [here](https://github.com/juliangarnier/anime#list-of-valid-animatable-properties).

In your case, while you cannot tween from class name to class name, you can animate the `color` and `font-size` properties. Here is an example: http://codepen.io/alexchantastic/pen/yaPkBy

**Comment by yspb** [comment]
Thanks!
