### ISSUE TITLE
How can I use animejs GLOBALLY on my wordpress website? (sffinit.com)

### ISSUE THREAD

**Issue by patko1727** [juliangarnier/anime#838]
Hello,
I would like to figure out how to use animejs globally on my wordpress website. 
Code obviously works when I use it in a specific file with <script> tags.
I added animejs folder to the theme directory and added this code to functions.php:

add_action( 'wp_enqueue_scripts', 'my_theme_scripts' );
function ti_custom_javascript() {
	wp_enqueue_script( 'example-script', get_template_directory_uri() . '/anime-master/lib/anime.min.js');
}
This custom file doesn't work for global dev:
add_action('wp_enqueue_scripts', 'ti_custom_javascript');

function finit_js() {
	wp_enqueue_script( 'example-script', get_template_directory_uri() . '/js/script-finit.js', array( 'jquery' ), '1.0.0', true );
}
add_action('wp_enqueue_scripts', 'finit_js');

Could you help me or create a simple tutorial for me, please?

**Comment by different55** [comment]
Do you actually want help? Far as I can tell, you don't really need much if any.

If you've successfully included the script, if you can open up your browser console and access the anime object, then all you need to do use it is write JavaScript to call animejs according to the [documentation](https://animejs.com/documentation/). So if you're already that far, you've basically already completed your tutorial.
