### ISSUE TITLE
anime with pixi.js

### ISSUE THREAD

**Issue by acmoles** [juliangarnier/anime#85]
anime generally seems to work nicely with pixi.js

pixi holds several properties as 'pixi points' (position, pivot etc.) it would be really nice if they could be accessed through the anime as so:

`
var testAnim = anime({
      targets: graphics,
      position.x: 10,
      position.y: 10,
      duration: function() { return anime.random(100, 1800); },
      easing: 'easeOutExpo',
      direction: 'alternate',
      loop: true
    });
`

Instead it throws an error 'unexpected token .'

A workaround would be targeting graphics.postion but then other attributes of graphics (rotation, alpha etc.) can't be Tweened at the same time.

**Comment by juliangarnier** [comment]
I never used pix.jsi, but from what I see in your example, it's more a JS syntax problem than a something relative to Anime.

You can't define object property with a "." inside the name, that's where the  'unexpected token .' comes from.

I think your workaround is the only way to animate the different attributes.
Simply create multiple anime instances:

```
anime({
  targets: pixiObj.position,
  x: 100,
  y: 200
});

anime({
  targets: pixiObj.rotation,
  x: 360
});
```
