### ISSUE TITLE
Search bar in documentation.

### ISSUE THREAD

**Issue by sarojregmi200** [juliangarnier/anime#860]
**Problem that I faced:**
I was trying to implement the anime js but found it hard to navigate through the documentation, I don't mean to say the docs is not good or anything just that it lacks search feature which can be a great time saver.

**Solution:**
To build the search functionality or to provide the scope of the search and assign some one in the community.

PS: I can build the search, and will be free after 2 weeks.

**Comment by juliangarnier** [comment]
Hi, I agree with you and already added search to the upcoming V4 documentation as part of a major redesign.

**Comment by sarojregmi200** [comment]
Hey, thanks for a quick response. Is it possible that I can work on this ?

**Comment by juliangarnier** [comment]
Thanks for offering your help.
The search functionality Is already complete.
The only thing left to do is on the design side and I prefer to control this part.

**Comment by sarojregmi200** [comment]
No worries.
I agree with the decision of taking more control over the design.
As the issue is addressed, I am closing this issue.
