### ISSUE TITLE
Just a question about line drawing in the docs

### ISSUE THREAD

**Issue by rushkii** [juliangarnier/anime#875]
Hello, sorry for asking in the issue section, I just wondering, is this line drawing created manually or generated using tools? if it using tools can you give me the tools name?

![image](https://github.com/juliangarnier/anime/assets/47179236/b6785f39-2712-4bbf-a1ad-da626f9cd2ce)

**Comment by juliangarnier** [comment]
Hi, this has been drawn in Sketch if I remember correctly.
But any vector graphics editor that supports SVG export works, like Figma or Illustrator for example.

**Comment by rushkii** [comment]
> Hi, this has been drawn in Sketch if I remember correctly.
> But any vector graphics editor that supports SVG export works, like Figma or Illustrator for example.

oke, thanks.
