### ISSUE TITLE
Why a cant use play/pause buttons?

### ISSUE THREAD

**Issue by TreeFall1** [juliangarnier/anime#876]
JS:
```
let elements = document.querySelectorAll(".el");
    let playBtn= document.querySelector('.play');
    let pauseBtn= document.querySelector('.pause');
    const circle = anime({
	    targets: elements,
	    left: "240px",
	    borderRadius: ["0%", "50%"],
	    duration: 1000,
	    easing: 'easeInOutQuad',
	    autoplay: false,
	    // loop: true,
    });
playBtn.onclick = animation.play;
pauseBtn.onclick = animation.pause;
```
HTML:

> <body>
	<div class="el"></div>
	<div class="btns-container">
		<button class="play">Play</button>
		<button class="pause">Pause</button>
	</div>
	<script src="animejs/lib/anime.min.js"></script>
	<script src="script.js"></script>
</body>

Why my play/pause buttons doesnt work? Its says: Uncaught ReferenceError: animation is not defined

**Comment by juliangarnier** [comment]
It's because the `animation` variable is never declared, your animation variable is `circle`.
```
playBtn.onclick = circle.play;
pauseBtn.onclick = circle.pause;
```
Should work
