### ISSUE TITLE
Is there a way to += values?

### ISSUE THREAD

**Issue by paulous** [juliangarnier/anime#89]
Thanks!

**Comment by achugaev93** [comment]
+1. This is must-have feature

**Comment by juliangarnier** [comment]
What is the expected behaviour?

**Comment by achugaev93** [comment]
It should calculate destination value like *destination = currentValue + deltaValue*, where *deltaValue* is at the right side of "+=..." expression. You can see such technic in jQuery animations. In general, it's just a shorcut.

**Comment by paulous** [comment]
yes it is just a a shortcut , just saves a step or two that's all. I use velocity a fair bit so just trying to do  stuff I am used to having. Great work and thanks again!

**Comment by juliangarnier** [comment]
I added support for relative values in V2, you can see it in action here: http://anime-js.com/v2/documentation/#relativeValues

It supports +=, -= and *=

The documentation is still WIP, and I didn't have the time to write a proper change log yet, but the code is available for testing here : https://github.com/juliangarnier/anime/blob/v2.0/anime.js

Feedback is welcome!

**Comment by paulous** [comment]
Very nice interface!

**Comment by hinok** [comment]
@juliangarnier Just wanted to say that documentation for v2 is great.

**Comment by juliangarnier** [comment]
Added to V2.
