### ISSUE TITLE
Blurry results when scale

### ISSUE THREAD

**Issue by tinchox5** [juliangarnier/anime#90]
Hi, Julian
Is there a way to obtain crispy results after animate things with scale? I'm doing a kind of zoomable interface, but the problem is that the results are blurry and stay in that way even when animation has finished.
I saw that anime removes will-change property after performs an animation. Is there a way to "re render" the result to show crispy again?

**Comment by juliangarnier** [comment]
I'm working on this.
Will change appears to be the problem here, and I am considering to completely remove the will-change support in 2.0, it's causing problems than benefits.

**Comment by juliangarnier** [comment]
I removed will-change support on V2, you can try it here : https://github.com/juliangarnier/anime/blob/v2.0/anime.js

**Comment by hinok** [comment]
@tinchox5 @juliangarnier I encountered today this problem. I'm using already my small wrapper around anime and this is a quick fix that works for me.

```javascript
import anime from 'animejs';
import isArray from 'lodash/isArray';
import isObject from 'lodash/isObject';

const animeAnimationProps = {
  rotate: 'transform',
  translateX: 'transform',
  translateY: 'transform',
  scale: 'transform',
  opacity: 'opacity',
};

const getWillChangeProps = (options) => {
  const props = Object.keys(options)
    .filter(key => !!animeAnimationProps[key])
    .map(key => animeAnimationProps[key]);

  const propsWithoutDuplicates = [...new Set(props)];

  return propsWithoutDuplicates
    .reduce((acc, prop) => `${acc}${prop},`, '')
    .slice(0, -1);
};

const setWillChange = (targets, options) => {
  /* eslint-disable no-underscore-dangle, no-param-reassign */
  const _targets = !isArray(targets) ? [targets] : targets;

  _targets.forEach((target) => {
    if (!isObject(target)) {
      return;
    }

    const willChangeProps = getWillChangeProps(options);

    target.style.willChange = willChangeProps.length ? willChangeProps : 'inherit';
  });
};

const unsetWillChange = (targets) => {
  setWillChange(targets, {});
};

const tween = options => new Promise((resolve) => {
  const { targets } = options;

  setWillChange(targets, options);

  anime({
    ...options,
    complete: () => {
      unsetWillChange(targets);
      resolve();
    },
  });
});

```

**Comment by juliangarnier** [comment]
v2 doesn't use will-change anymore, that should fix most of the "blurry" results you got with 1.x

**Comment by tinchox5** [comment]
Julian, 
Today I implemented your new version of Anime. It is awesome!. It runs very smoothly and the scale is not blurry anymore.
On the other hand, I think the new documentation section is very clear, powerful and useful to  follow and understand.
Congratulations! 
Martin
