### ISSUE TITLE
Path animation cannot be reversed

### ISSUE THREAD

**Issue by tameroski** [juliangarnier/anime#92]
Hi,

Looks like applying `direction: 'reverse'` to a svg path animation doesn't work. 
Is there a workaround for that (except drawing the path the other way) ?

**Comment by benjibee** [comment]
I have the same issue. I dug around the source a bit, but I can't see any reason it wouldn't work here. I popped [my code into a CodePen here](http://codepen.io/benjibee/pen/oYGRdj), if you have any ideas it would be great.

**Comment by juliangarnier** [comment]
Unfortunately this is not possible with the current codebase, but will be fixed in 2.0.
Sneak peek: 
![image](https://dl.dropboxusercontent.com/u/7203383/shared/motion-path-playback.gif)

**Comment by juliangarnier** [comment]
There is a new anime.path API in V2, and it now supports 'reverse' and 'alternate' direction.
See an example here : http://anime-js.com/v2/documentation/#motionPath

The documentation is still WIP, and I didn't have the time to write a proper change log yet, but the code is available for testing here : https://github.com/juliangarnier/anime/blob/v2.0/anime.js

**Comment by thisolivier** [comment]
I had actually written a little mod with reverse functions, was on here to see if it would be useful! I'm glad the project continues to develop.

**Comment by juliangarnier** [comment]
Fixed in V2.
