### ISSUE TITLE
Animating dynamically created elements

### ISSUE THREAD

**Issue by rafaelferreiraql** [juliangarnier/anime#94]
When targets are assigned, they stay like that. If I assign any ".animate" class and then dynamically create new .animate elements, they won't be included and I see no way to refresh the selection. Maybe I'm not being creative enough, but the only way I thought of was to reapply the entire animation via repeating anime({}) and overwriting the previous assignment. How can I just refresh the selection instead?

**Comment by juliangarnier** [comment]
You can't refresh the targets parameters without restarting the animation.
Dynamically added elements must be animated separately.
One way to do it is to wrap the `anime` call and the element creation together : 

```
function createElement() {
  var el = document.createElement('div');
  anime({
    targets: el,
    width: ['0px', '100px'],
    duration: 3000
  });
  document.body.appendChild(el);
}
```

http://codepen.io/juliangarnier/pen/mOGpzP
