### ISSUE TITLE
example.html

### ISSUE THREAD

**Issue by Nayysphytonnn** [juliangarnier/anime#960]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by different55** [comment]
What are you trying to say here because you just submitted a blank bug report.

**Comment by juliangarnier** [comment]
@Nayysphytonnn please feel free to re-open with a clear and concise description of what the bug is.
Thanks
