### ISSUE TITLE
Animating svg path, how to export or prepare svg code

### ISSUE THREAD

**Issue by hinok** [juliangarnier/anime#99]
Hey,
I'm trying to morph shapes with `anime`, like in example https://github.com/juliangarnier/anime/blob/master/examples/svg-path.html

Should I export SVG files in a special way? How should I prepare them to make them "compatible with anime"?. If I use standard export method in Sketch, I get code below

```html
<?xml version="1.0" encoding="UTF-8"?>
<svg width="300px" height="300px" viewBox="0 0 300 300" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 41.2 (35397) - http://www.bohemiancoding.com/sketch -->
    <title>Morph</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <path d="M300,300 L150,300 L0,300 L0,150 L0,0 L150,0 L300,0 L300,150 L300,300 Z" id="Shape" fill="#000000"></path>
        <path d="M275.510204,275.510204 C275.510204,275.510204 218.571429,300 150,300 C70.2040816,300 24.4897959,275.510204 24.4897959,275.510204 C24.4897959,275.510204 0,237.040816 0,150 C0,78.5061224 24.4897959,24.4897959 24.4897959,24.4897959 C24.4897959,24.4897959 70.4081633,0 150,0 C236.734694,0 275.510204,24.4897959 275.510204,24.4897959 C275.510204,24.4897959 300,63.7040816 300,150 C300,231.271429 275.510204,275.510204 275.510204,275.510204 Z" id="Shape" fill="#000000"></path>
    </g>
</svg>
```

What I would like to do is the animation between first and second path but when I use these paths, animation is broken - look at https://jsfiddle.net/1abuxzg3/

I attach also `Morph.sketch` that contains shapes and SVG code that was pasted above.

[Morph.sketch.zip](https://github.com/juliangarnier/anime/files/659131/Morph.sketch.zip)

**Edit**

If I use `Snap.svg` and animate between these paths then copy path's code created by Snap.svg, `animate` works properly.

https://jsfiddle.net/1abuxzg3/1/

I would like to avoid using Snap.svg as a kind of tool for preparing SVG files for `animate` and I have that feeling that I'm doing something completely stupid 💃

**Comment by floq-design** [comment]
@hinok I'm also struggling to find a 'clean' morph with anime.

I see your second jsfiddle example is working really well with anime.js - did you work out how to export the shapes?

**Comment by hinok** [comment]
> If I use Snap.svg and animate between these paths then copy path's code created by Snap.svg, animate works properly.

This is how I deal with that kind of animations at the moment
http://jsbin.com/tusuvay/edit?html,js,output

It shows almost step by step how I prepare points to transform with `anime`. For some SVG I have to also firstly optimize them by [svgomg](https://jakearchibald.github.io/svgomg/). Please don't look at the code quality because it's terrible, I just made it as fast as I could for demo purposes 🔪 

Here is the source of svg exported from Sketch

```html
<svg width="220" height="310" viewBox="0 0 220 310" xmlns="http://www.w3.org/2000/svg">
  <title>
    Scene
  </title>
  <g id="Page-1" fill="none" fill-rule="evenodd">
    <g id="Scene">
      <path d="M19.892 87.427L133.017 0 99 135.836l51.583-36.74.378 44.118H220l-3.347 40.093h-25.277s-48.832-60.132-48.832-9.994 62.43 44.502 62.43 44.502l.37 51.323-45.18.38S86.01 305.815 78.118 231.93C70.228 158.05 40.696 310 40.696 310L0 229.472s76.275-64.2 48.084-75.23c-28.192-11.028-28.192-66.815-28.192-66.815z" id="Path" fill="#F90000"/>
      <path d="M110.5 237c33.966 0 61.5-47.534 61.5-81.5S144.466 74 110.5 74 49 121.534 49 155.5 76.534 237 110.5 237z" id="Oval" fill="#0056FF"/>
    </g>
  </g>
</svg>
```

Look that points after Snap transformations look different

```
M19.891999999999996,87.42700000000002C19.891999999999996,87.42700000000002,133.017,0,133.017,0C133.017,0,99,135.836,99,135.836C99,135.836,150.583,99.096,150.583,99.096C150.583,99.096,150.96099999999998,143.214,150.96099999999998,143.214C150.96099999999998,143.214,220,143.214,220,143.214C220,143.214,216.653,183.30700000000002,216.653,183.30700000000002C216.653,183.30700000000002,191.37599999999998,183.30700000000002,191.37599999999998,183.30700000000002C191.37599999999998,183.30700000000002,142.54399999999998,123.17500000000001,142.54399999999998,173.31300000000002C142.54399999999998,223.45100000000002,204.974,217.81500000000003,204.974,217.81500000000003C204.974,217.81500000000003,205.344,269.13800000000003,205.344,269.13800000000003C205.344,269.13800000000003,160.164,269.51800000000003,160.164,269.51800000000003C160.164,269.51800000000003,86.01,305.815,78.118,231.93C70.228,158.05,40.696,310,40.696,310C40.696,310,0,229.472,0,229.472C0,229.472,76.275,165.272,48.084,154.24200000000002C19.891999999999996,143.21400000000003,19.891999999999996,87.42700000000002,19.891999999999996,87.42700000000002C19.891999999999996,87.42700000000002,19.891999999999996,87.42700000000002,19.891999999999996,87.42700000000002
```

```
M110.5,237C144.466,237,172,189.466,172,155.5C172,121.53399999999999,144.466,74,110.5,74C76.53399999999999,74,49,121.534,49,155.5C49,189.466,76.534,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237C110.5,237,110.5,237,110.5,237
```

I remember that it's very easy to morph SVG if number of points is the same in paths. Unfortunately in real life we don't deal with shapes which have equal number of points. `Snap` makes transformations that just add "missing points".

I hope it will help you.

**Comment by floq-design** [comment]
@hinok Thanks so much for your reply and comprehensive demo..

I misread your original post regarding **using snap.svg for it's output**, *apologies*.

I've used your jsBin demo with my SVG data and my morph is now works cleanly.
You've created a great tool to convert exported SVG points into morphable ones.

**Nice work.**

**Comment by hinok** [comment]
Nice to hear that it works for you 👍

**Comment by juliangarnier** [comment]
Can be tricky in some cases.
I often slightly start moving the points of the initial shape.
Like this :
![SVG COORDS](https://dl.dropboxusercontent.com/u/7203383/shared/svg-coordinates.png)
That way I'm sure the coordinates will follow the same direction.
